// Demo seed: fills the store with sample candidates + generated PDF CVs
// so the platform can be explored before connecting a real Zoho account.
const fs = require('fs');
const path = require('path');
const { loadDb, saveDb, CV_DIR } = require('./store');

// Build a minimal valid single-page PDF containing a few lines of text.
function makePdf(lines) {
  const content = lines
    .map((l, i) => `BT /F1 14 Tf 60 ${760 - i * 24} Td (${l.replace(/[()\\]/g, '')}) Tj ET`)
    .join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((body, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i <= objects.length; i++) pdf += String(offsets[i]).padStart(10, '0') + ' 00000 n \n';
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, 'latin1');
}

const SAMPLE_CANDIDATES = [
  { name: 'Sara Al-Harbi', email: 'sara.alharbi@example.com', role: 'Senior Graphic Designer', years: 7, subject: 'Application: Senior Graphic Designer - Sara Al-Harbi' },
  { name: 'Omar Khalid', email: 'omar.khalid@example.com', role: 'Production Supervisor', years: 5, subject: 'CV for Production Supervisor position' },
  { name: 'Lina Mansour', email: 'lina.mansour@example.com', role: 'Accountant', years: 4, subject: 'Applying for Accountant role - CV attached' },
  { name: 'Yousef Al-Amri', email: 'y.alamri@example.com', role: 'Sales Executive', years: 6, subject: 'Sales Executive Application' },
  { name: 'Huda Nasser', email: 'huda.nasser@example.com', role: 'HR Coordinator', years: 3, subject: 'HR Coordinator - Huda Nasser CV' },
  { name: 'Fahad Al-Otaibi', email: 'fahad.otaibi@example.com', role: 'Color Lab Technician', years: 8, subject: 'Resume - Color Lab Technician' },
];

function seedDemo() {
  const db = loadDb();
  if (db.candidates.length) return db;

  let t = Date.now() - 1000 * 60 * 60 * 5;
  for (const [i, c] of SAMPLE_CANDIDATES.entries()) {
    const id = 'demo-' + (1000 + i);
    const fileName = `${id}-${c.name.replace(/\s+/g, '_')}_CV.pdf`;
    const pdf = makePdf([
      c.name, c.role, '',
      `Email: ${c.email}`,
      `Experience: ${c.years} years`, '',
      'This is a demo CV generated by People Desk (demo mode).',
    ]);
    fs.writeFileSync(path.join(CV_DIR, fileName), pdf);
    db.candidates.push({
      id,
      from: c.email,
      fromName: c.name,
      subject: c.subject,
      summary: `Dear HR team, please find attached my CV for the ${c.role} position. Best regards, ${c.name}`,
      receivedTime: (t -= 1000 * 60 * 137),
      attachments: [{ name: `${c.name.replace(/\s+/g, '_')}_CV.pdf`, size: pdf.length, file: fileName }],
      source: 'demo',
      status: 'new',
    });
    db.seenMessageIds[id] = 'imported';
  }
  db.lastSync = Date.now();
  saveDb(db);
  return db;
}

module.exports = { seedDemo };
