// Attachment storage abstraction.
// Rules enforced here (see docs/DECISIONS.md):
//  * files live OUTSIDE public/ and are never served statically
//  * internal names are opaque random keys (unguessable), extension-free
//  * every read goes through the authorized API route, never a direct path
//  * size limit + path traversal guard + SHA-256 recorded on write
// LocalStorage is the default backend; an S3-compatible backend implements
// the same interface (put/getStream/exists) and plugs in via MADAR_STORAGE.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

class LocalStorage {
  constructor(rootDir, { maxBytes }) {
    this.root = rootDir;
    this.maxBytes = maxBytes;
    fs.mkdirSync(this.root, { recursive: true, mode: 0o700 });
  }

  _resolve(key) {
    // keys are generated by put(); reject anything that isn't a plain hex key
    if (!/^[0-9a-f]{48}$/.test(String(key))) throw new Error('Invalid storage key');
    const full = path.join(this.root, key.slice(0, 2), key);
    if (!full.startsWith(this.root + path.sep)) throw new Error('Path traversal blocked');
    return full;
  }

  // returns { key, sha256, size }
  put(buffer) {
    if (!Buffer.isBuffer(buffer)) throw new Error('put() expects a Buffer');
    if (buffer.length > this.maxBytes) {
      throw new Error(`Attachment exceeds size limit (${buffer.length} > ${this.maxBytes} bytes)`);
    }
    const key = crypto.randomBytes(24).toString('hex'); // 48 hex chars, unguessable
    const full = this._resolve(key);
    fs.mkdirSync(path.dirname(full), { recursive: true, mode: 0o700 });
    fs.writeFileSync(full, buffer, { mode: 0o600 });
    return { key, sha256: crypto.createHash('sha256').update(buffer).digest('hex'), size: buffer.length };
  }

  exists(key) { try { return fs.existsSync(this._resolve(key)); } catch { return false; } }
  getStream(key) { return fs.createReadStream(this._resolve(key)); }
}

let instance = null;
function getStorage() {
  if (instance) return instance;
  const backend = process.env.MADAR_STORAGE || 'local';
  const { ATTACH_DIR } = require('./db');
  const maxBytes = Number(process.env.MAX_ATTACHMENT_MB || 25) * 1024 * 1024;
  if (backend === 'local') instance = new LocalStorage(ATTACH_DIR, { maxBytes });
  else throw new Error(`Storage backend "${backend}" not implemented yet (add it here — same put/getStream/exists interface).`);
  return instance;
}

module.exports = { getStorage, LocalStorage };
