# -*- coding: utf-8 -*-
# Al Maysari Family Cookbook - recipe data
# Each ingredient: (name, qty_1_person, qty_2_persons)
# tl = Tagalog key reminders (short, critical points only)

MAINS = [
{
 "id":1,"name":"Chicken Biryani","ar":"برياني دجاج","emoji":"🍛","time":"1 h 15 min","difficulty":"Medium",
 "video":"https://www.youtube.com/watch?v=rngAYfGgVGw","video_lang":"Tagalog","video_title":"Simple Chicken Biryani (Pinoy Style) - Maine Cooks",
 "img":"https://images.pexels.com/photos/37404187/pexels-photo-37404187.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Layered basmati rice with marinated chicken, fried onions and saffron. Cooked on 'dum' (sealed pot, low heat) so the steam finishes the rice.",
 "ingredients":[
  ("Chicken (thigh/leg, bone-in)","300 g (2 pcs)","600 g (4 pcs)"),
  ("Basmati rice, washed, soaked 30 min","1 cup (200 g)","2 cups (400 g)"),
  ("Plain yogurt","3 tbsp","6 tbsp"),
  ("Onion, thinly sliced","1 medium","2 medium"),
  ("Tomato, chopped","1 small","1 large"),
  ("Ginger-garlic paste","1 tsp","2 tsp"),
  ("Biryani masala","1 tbsp","2 tbsp"),
  ("Turmeric","1/4 tsp","1/2 tsp"),
  ("Kashmiri red chili powder (mild)","1/2 tsp","1 tsp"),
  ("Whole spices: cinnamon stick, 3 cardamom, 2 cloves, 1 bay leaf","1 set","1 set"),
  ("Fresh mint + coriander, chopped","2 tbsp","4 tbsp"),
  ("Saffron in 2 tbsp warm milk","small pinch","big pinch"),
  ("Ghee or oil","2 tbsp","4 tbsp"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Marinate chicken with yogurt, ginger-garlic, biryani masala, turmeric, chili, salt. Minimum 30 min (overnight is best).",
  "Fry sliced onion in ghee on medium heat until deep golden and crispy (10-12 min). Remove half for topping.",
  "Add marinated chicken to the pot with the remaining onion. Cook 10 min until chicken is sealed and sauce thick. Add tomato, cook 5 min.",
  "In another pot boil 6 cups water with salt and whole spices. Add soaked rice. Boil 5-6 min until rice is 70 percent cooked (still firm in center). Drain.",
  "Layer: chicken at bottom, rice on top, then fried onion, mint, coriander and saffron milk.",
  "Cover pot with a clean cloth then the lid (seal). Cook LOW heat 20 min. Turn off. Rest 10 min without opening.",
  "Serve from the side with a flat spoon so layers stay. Serve with raita (yogurt + cucumber).",
 ],
 "tl":[
  "Rice ay 70% lang luto bago i-layer. Kung lutong-luto na, magiging lata (mushy).",
  "Huwag buksan ang takip sa 20 min na dum. Pinakamababang apoy.",
  "Sibuyas dapat golden brown talaga, hindi sunog (mapait).",
 ],
},
{
 "id":2,"name":"Lamb Biryani","ar":"برياني لحم","emoji":"🍖","time":"2 h","difficulty":"Medium",
 "video":"https://www.youtube.com/watch?v=eWe1Mjzvf9w","video_lang":"English","video_title":"Arabic Mutton Biryani - Food Fusion",
 "img":"https://images.pexels.com/photos/32986470/pexels-photo-32986470.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Same method as chicken biryani but the lamb is cooked first until tender. Lamb needs more time than chicken; never rush it.",
 "ingredients":[
  ("Lamb with bone, cut in pieces","300 g","600 g"),
  ("Basmati rice, washed, soaked 30 min","1 cup","2 cups"),
  ("Plain yogurt","3 tbsp","6 tbsp"),
  ("Onion, thinly sliced","1 large","2 large"),
  ("Tomato, chopped","1","2"),
  ("Ginger-garlic paste","1 tsp","2 tsp"),
  ("Biryani masala","1 tbsp","2 tbsp"),
  ("Turmeric + mild red chili","1/4 tsp + 1/2 tsp","1/2 tsp + 1 tsp"),
  ("Whole spices (cinnamon, cardamom, cloves, bay leaf)","1 set","1 set"),
  ("Mint + coriander, chopped","2 tbsp","4 tbsp"),
  ("Saffron in warm milk","pinch","big pinch"),
  ("Ghee","2 tbsp","4 tbsp"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Marinate lamb with yogurt, ginger-garlic, masala, turmeric, chili, salt. Minimum 1 hour.",
  "Fry onion in ghee until deep golden. Remove half for topping.",
  "Add lamb with marinade to the pot. Cook on medium 10 min, add tomato and 1 cup water. Cover and simmer 60-75 min until lamb is tender (fork goes in easily). Sauce should be thick, not watery.",
  "Par-boil rice in salted water with whole spices 5-6 min (70 percent cooked). Drain.",
  "Layer lamb at the bottom, rice on top, fried onion, herbs, saffron milk.",
  "Seal with cloth and lid. LOW heat 25 min. Rest 10 min.",
  "Serve with raita and salad.",
 ],
 "tl":[
  "Lamb dapat malambot na bago i-layer ang rice. Kung matigas pa, dagdagan ng tubig at pakuluan pa.",
  "Alisin ang labis na mantika sa ibabaw ng lamb bago ilagay ang rice.",
 ],
},
{
 "id":3,"name":"Chicken Maqluba","ar":"مقلوبة دجاج","emoji":"🍚","time":"1 h 30 min","difficulty":"Medium",
 "video":"https://www.youtube.com/watch?v=Fs0Nyg9hayY","video_lang":"English","video_title":"How to make Chicken Maqluba - Recipes are Simple",
 "img":"https://images.pexels.com/photos/37324505/pexels-photo-37324505.png?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Palestinian 'upside-down' rice. Fried eggplant, cauliflower and potato are layered with chicken and rice, then the whole pot is flipped onto a tray.",
 "ingredients":[
  ("Chicken pieces, bone-in","350 g","700 g"),
  ("Basmati rice, washed, soaked 20 min","1 cup","2 cups"),
  ("Eggplant, sliced 1 cm","1/2 medium","1 medium"),
  ("Cauliflower florets","1 cup","2 cups"),
  ("Potato, sliced 1 cm","1 small","1 large"),
  ("Tomato, sliced","1","2"),
  ("Onion, chopped","1/2","1"),
  ("Maqluba / 7-spice (baharat)","1 tsp","2 tsp"),
  ("Turmeric","1/4 tsp","1/2 tsp"),
  ("Cinnamon stick, 2 cardamom, 1 bay leaf","1 set","1 set"),
  ("Chicken stock (from boiling chicken)","1.5 cups","3 cups"),
  ("Oil for frying","as needed","as needed"),
  ("Toasted almonds / pine nuts for topping","1 tbsp","2 tbsp"),
  ("Salt + black pepper","to taste","to taste"),
 ],
 "steps":[
  "Boil chicken with onion, whole spices and salt for 25 min. Keep the stock. Brown the chicken pieces in a little oil.",
  "Salt eggplant slices 10 min, pat dry. Fry eggplant, cauliflower and potato separately until golden. Drain on paper.",
  "Mix drained rice with baharat, turmeric, salt.",
  "In a deep pot, put a layer of tomato slices at the bottom, then chicken, then fried vegetables, then rice on top. Press gently.",
  "Pour hot stock slowly down the side until it just covers the rice. Bring to boil, then cover and cook LOW 35-40 min until liquid is absorbed.",
  "Turn off, rest 10 min. Put a large tray on top of the pot and flip it over in one quick move. Wait 2 min, lift the pot.",
  "Top with toasted nuts and parsley. Serve with yogurt and salad.",
 ],
 "tl":[
  "Prituhin ang gulay hanggang golden, hindi mantikang-mantika. Patuluin sa paper towel.",
  "Pag ibabaliktad, isang mabilis na galaw. Huwag mag-alinlangan.",
  "Rice sa ibabaw lang, tubig (stock) dapat abot lang sa rice, hindi sobra.",
 ],
},
{
 "id":4,"name":"Lamb Maqluba","ar":"مقلوبة لحم","emoji":"🥩","time":"2 h","difficulty":"Medium",
 "video":"https://www.youtube.com/watch?v=-JwapADzlRA","video_lang":"English","video_title":"Maqluba with Lamb - Cooking Gorgeous",
 "img":"https://images.pexels.com/photos/7469422/pexels-photo-7469422.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Same as chicken maqluba, but lamb is simmered first until tender and its rich stock cooks the rice.",
 "ingredients":[
  ("Lamb with bone, pieces","350 g","700 g"),
  ("Basmati rice, washed, soaked","1 cup","2 cups"),
  ("Eggplant, sliced","1/2","1"),
  ("Cauliflower florets","1 cup","2 cups"),
  ("Potato, sliced","1 small","1 large"),
  ("Tomato, sliced","1","2"),
  ("Onion","1/2","1"),
  ("7-spice (baharat) + turmeric","1 tsp + 1/4 tsp","2 tsp + 1/2 tsp"),
  ("Cinnamon, cardamom, bay leaf","1 set","1 set"),
  ("Lamb stock","1.5 cups","3 cups"),
  ("Oil for frying","as needed","as needed"),
  ("Toasted nuts","1 tbsp","2 tbsp"),
  ("Salt, pepper","to taste","to taste"),
 ],
 "steps":[
  "Boil lamb with onion, whole spices and salt 60-75 min until tender. Skim the foam in the first 10 min. Keep the stock.",
  "Fry eggplant, cauliflower and potato until golden. Drain.",
  "Season rice with baharat, turmeric and salt.",
  "Layer in pot: tomato slices, lamb, fried vegetables, rice. Pour hot stock to cover rice.",
  "Boil, then cover and cook LOW 35-40 min. Rest 10 min. Flip onto tray.",
  "Top with nuts. Serve with yogurt.",
 ],
 "tl":[
  "Alisin ang bula (foam) habang pinakukuluan ang lamb para malinis ang stock.",
  "Lamb dapat malambot BAGO i-layer.",
 ],
},
{
 "id":5,"name":"Yellow Rice with Peri-Peri Chicken (Nando's style)","ar":"أرز أصفر مع دجاج بيري بيري","emoji":"🍗","time":"1 h (plus marinating)","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=aI5f6PM590I","video_lang":"Tagalog","video_title":"Roasted Peri-Peri Chicken with Yellow Rice - Chef RV Manabat",
 "img":"https://images.pexels.com/photos/24866509/pexels-photo-24866509.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Grilled chicken in a tangy peri-peri marinade with turmeric yellow rice. Use MILD peri-peri for Einas; medium for Mohamed.",
 "ingredients":[
  ("Chicken thighs or half chicken","350 g","700 g"),
  ("Peri-peri sauce (Nando's bottle) MILD","3 tbsp","6 tbsp"),
  ("Lemon juice","1 tbsp","2 tbsp"),
  ("Garlic, minced","2 cloves","4 cloves"),
  ("Paprika + oregano","1/2 tsp each","1 tsp each"),
  ("Olive oil","1 tbsp","2 tbsp"),
  ("Basmati rice, washed","1 cup","2 cups"),
  ("Turmeric","1/2 tsp","1 tsp"),
  ("Butter","1 tbsp","2 tbsp"),
  ("Water","1.5 cups","3 cups"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Score the chicken with a knife. Mix peri-peri sauce, lemon, garlic, paprika, oregano, oil, salt. Coat chicken. Marinate 1 hour minimum (overnight best).",
  "Oven 200 C. Place chicken on a tray skin side up. Bake 35-40 min, brush more sauce halfway. Last 5 min grill setting for char. Juices must run clear.",
  "Rice: melt butter, add turmeric and rice, stir 1 min. Add water and salt. Boil, cover, LOW 15 min. Rest 5 min, fluff with fork.",
  "Serve chicken on rice with extra sauce on the side and a green salad or corn.",
 ],
 "tl":[
  "Para kay Einas: MILD peri-peri lang, walang extra chili.",
  "Chicken luto kapag malinaw ang katas (hindi pula) sa pinakamakapal na parte.",
 ],
},
{
 "id":6,"name":"Lamb Kabsa","ar":"كبسة لحم","emoji":"🍖","time":"2 h","difficulty":"Medium",
 "video":"https://www.youtube.com/watch?v=HfnTOP4p_ek","video_lang":"Tagalog","video_title":"How to cook Saudi Kabsa Lamb (Tagalog) - madam kikay cooking",
 "img":"https://images.pexels.com/photos/32986473/pexels-photo-32986473.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"The classic Gulf rice. Lamb is simmered with tomato, dried lime (loomi) and kabsa spices; the rice cooks in the same stock.",
 "ingredients":[
  ("Lamb with bone","350 g","700 g"),
  ("Basmati rice, washed, soaked 20 min","1 cup","2 cups"),
  ("Onion, chopped","1","2"),
  ("Tomato, grated or chopped","1 large","2 large"),
  ("Tomato paste","1 tbsp","2 tbsp"),
  ("Garlic, minced","2 cloves","4 cloves"),
  ("Kabsa spice mix","1 tbsp","2 tbsp"),
  ("Dried lime (loomi), pierced","1","2"),
  ("Cinnamon stick, 3 cardamom, 2 cloves, 1 bay leaf","1 set","1 set"),
  ("Carrot, grated (optional)","1/2","1"),
  ("Ghee / oil","2 tbsp","4 tbsp"),
  ("Water","2.5 cups","5 cups"),
  ("Raisins + toasted almonds for topping","1 tbsp each","2 tbsp each"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Fry onion in ghee until golden. Add garlic, lamb. Brown 5 min.",
  "Add tomato, tomato paste, kabsa spice, loomi, whole spices, salt. Stir 3 min.",
  "Add water. Boil, skim foam, cover, simmer 60-75 min until lamb is tender.",
  "Take out lamb pieces, keep warm. Measure the stock: you need 1.5 cups stock per 1 cup rice (add water if less).",
  "Add rice and carrot to the stock. Boil 2 min, cover, LOW 18-20 min. Rest 5 min.",
  "Optional: put lamb under the oven grill 5 min for colour. Serve lamb on rice, top with raisins and almonds. Serve with daqoos (tomato chili sauce) and salad.",
 ],
 "tl":[
  "Sukatin ang stock: 1.5 cups stock = 1 cup rice. Ito ang sikreto ng magandang kabsa.",
  "Butasin ang loomi (dried lime) para lumabas ang lasa.",
 ],
},
{
 "id":7,"name":"Chicken Kabsa","ar":"كبسة دجاج","emoji":"🍗","time":"1 h 15 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=JhTIBKOpUEY","video_lang":"Tagalog","video_title":"Kabsa Rice with Chicken (Saudi / Tagalog) - Yamyam Arabicfood",
 "img":"https://images.pexels.com/photos/17650193/pexels-photo-17650193.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Same as lamb kabsa with chicken; faster. Chicken is finished under the grill for golden skin.",
 "ingredients":[
  ("Chicken pieces, bone-in (leg + thigh)","350 g","700 g"),
  ("Basmati rice, washed, soaked","1 cup","2 cups"),
  ("Onion, chopped","1","2"),
  ("Tomato, chopped","1","2"),
  ("Tomato paste","1 tbsp","2 tbsp"),
  ("Garlic","2 cloves","4 cloves"),
  ("Kabsa spice","1 tbsp","2 tbsp"),
  ("Dried lime (loomi)","1","2"),
  ("Cinnamon, cardamom, cloves, bay leaf","1 set","1 set"),
  ("Carrot, grated","1/2","1"),
  ("Ghee","2 tbsp","4 tbsp"),
  ("Water","2 cups","4 cups"),
  ("Raisins + almonds","1 tbsp each","2 tbsp each"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Fry onion in ghee until golden. Add garlic and chicken, brown 5 min each side.",
  "Add tomato, paste, kabsa spice, loomi, whole spices, salt. Stir 3 min. Add water. Cover, simmer 25 min.",
  "Remove chicken. Put chicken on a tray in the oven, grill 200 C 10 min until golden.",
  "Measure stock (1.5 cups per cup of rice). Add rice and carrot. Boil 2 min, cover, LOW 18 min. Rest 5 min.",
  "Serve chicken on rice with raisins, almonds, daqoos sauce and salad.",
 ],
 "tl":[
  "Huwag masyadong matagal ang chicken sa kaldero, 25 min lang, tapos sa oven para hindi matunaw.",
  "Rice: LOW heat, takip, huwag haluin habang niluluto.",
 ],
},
{
 "id":8,"name":"Chicken Bukhari Rice","ar":"رز بخاري بالدجاج","emoji":"🍚","time":"1 h 15 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=FKP7Cuvo2tM","video_lang":"English","video_title":"Bukhari Rice with Chicken - The cookbook",
 "img":"https://images.pexels.com/photos/18698228/pexels-photo-18698228.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Lightly spiced rice with carrot, raisins and tomato paste, served with grilled chicken and the Bukhari tomato salsa.",
 "ingredients":[
  ("Chicken pieces","350 g","700 g"),
  ("Basmati rice, washed, soaked","1 cup","2 cups"),
  ("Onion, chopped","1","2"),
  ("Carrot, cut in thin sticks","1","2"),
  ("Tomato paste","1.5 tbsp","3 tbsp"),
  ("Garlic","2 cloves","4 cloves"),
  ("Cumin + coriander powder","1/2 tsp each","1 tsp each"),
  ("Cinnamon stick, 3 cardamom, 2 cloves","1 set","1 set"),
  ("Raisins","2 tbsp","4 tbsp"),
  ("Chicken stock / water","1.5 cups","3 cups"),
  ("Ghee / oil","2 tbsp","4 tbsp"),
  ("Chicken marinade: yogurt 2 tbsp, lemon, garlic, paprika, salt","1 set","2 sets"),
  ("Salsa: 2 tomatoes, 1 green chili (skip for Einas), garlic, coriander, lemon, salt","1 set","1 set"),
 ],
 "steps":[
  "Marinate chicken 30 min. Bake at 200 C for 35 min, grill the last 5 min.",
  "Fry onion in ghee until golden. Add garlic, carrot, whole spices, cumin, coriander. Cook 3 min.",
  "Add tomato paste, stir 2 min. Add rice, stir gently 1 min.",
  "Add stock and salt. Boil, cover, LOW 18 min. Add raisins on top for the last 5 min. Rest 5 min.",
  "Blend salsa ingredients roughly (not smooth). Serve chicken on rice with salsa and cucumber-yogurt.",
 ],
 "tl":[
  "Carrot dapat manipis (matchstick) para maluto kasabay ng rice.",
  "Salsa: walang sili para kay Einas. Hiwalay na lalagyan.",
 ],
},
{
 "id":9,"name":"Lamb Bukhari Rice","ar":"رز بخاري باللحم","emoji":"🍖","time":"2 h","difficulty":"Medium",
 "video":"https://www.youtube.com/watch?v=JjuCxo2Jwco","video_lang":"Tagalog","video_title":"Bukhari Rice with Lamb (Tagalog) - Rebecca Cooking Channel",
 "img":"https://images.pexels.com/photos/17650169/pexels-photo-17650169.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Bukhari rice cooked in lamb stock, served with the tender boiled-then-grilled lamb.",
 "ingredients":[
  ("Lamb with bone","350 g","700 g"),
  ("Basmati rice, washed, soaked","1 cup","2 cups"),
  ("Onion","1","2"),
  ("Carrot, thin sticks","1","2"),
  ("Tomato paste","1.5 tbsp","3 tbsp"),
  ("Garlic","2 cloves","4 cloves"),
  ("Cumin, coriander, black pepper","1/2 tsp each","1 tsp each"),
  ("Cinnamon, cardamom, cloves, 1 bay leaf","1 set","1 set"),
  ("Raisins","2 tbsp","4 tbsp"),
  ("Ghee","2 tbsp","4 tbsp"),
  ("Water for boiling lamb","4 cups","6 cups"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Boil lamb with half the onion, whole spices and salt 60-75 min until tender. Skim foam. Keep stock.",
  "Take lamb out. Grill in oven 200 C 10 min for colour.",
  "Fry the other onion in ghee golden. Add garlic, carrot, spices, tomato paste. Cook 3 min. Add rice, stir 1 min.",
  "Add 1.5 cups stock per cup rice, salt. Boil, cover, LOW 18 min. Raisins last 5 min. Rest 5 min.",
  "Serve lamb on rice with tomato salsa and yogurt.",
 ],
 "tl":[
  "Lamb malambot muna bago gawin ang rice.",
  "Stock ang gamitin sa rice, hindi plain water, para malasa.",
 ],
},
{
 "id":10,"name":"Chicken Curry with Boiled Eggs","ar":"كاري دجاج مع بيض مسلوق","emoji":"🥚","time":"50 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=LnmiOuZqZNk","video_lang":"English","video_title":"How to Cook Chicken Curry with Boiled Eggs - Enjoy Cooking with AL",
 "img":"https://images.pexels.com/photos/35267285/pexels-photo-35267285.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Home-style mild curry with chicken, potato and halved boiled eggs. Served with white rice.",
 "ingredients":[
  ("Chicken pieces (boneless or bone-in)","300 g","600 g"),
  ("Eggs, hard boiled (9 min), peeled","2","4"),
  ("Potato, cubed","1 small","1 large"),
  ("Onion, finely chopped","1","2"),
  ("Tomato, chopped","1","2"),
  ("Ginger-garlic paste","1 tsp","2 tsp"),
  ("Curry powder (mild)","1 tbsp","2 tbsp"),
  ("Turmeric","1/4 tsp","1/2 tsp"),
  ("Coconut milk (optional, for creamy)","1/2 cup","1 cup"),
  ("Oil","2 tbsp","3 tbsp"),
  ("Water","1 cup","2 cups"),
  ("Fresh coriander","1 tbsp","2 tbsp"),
  ("Salt","to taste","to taste"),
  ("White rice (cooked) to serve","1 cup","2 cups"),
 ],
 "steps":[
  "Fry onion in oil until soft and golden (6-8 min). Add ginger-garlic 1 min.",
  "Add curry powder, turmeric, stir 30 seconds. Add tomato, cook until soft (5 min).",
  "Add chicken, coat in masala, cook 5 min. Add potato, water, salt. Cover, simmer 20 min until potato is soft.",
  "Add coconut milk if using. Simmer 5 min. Sauce should be thick enough to coat a spoon.",
  "Cut boiled eggs in half, place gently on top, spoon sauce over. 2 min more. Top with coriander. Serve with white rice.",
 ],
 "tl":[
  "Mild lang ang curry. Walang extra chili (si Einas ay hindi kumakain ng maanghang).",
  "Eggs: 9 minuto kumukulo, tapos malamig na tubig para madaling balatan.",
 ],
},
{
 "id":11,"name":"Chicken with Vegetables in the Oven","ar":"دجاج بالخضار في الفرن","emoji":"🍗","time":"1 h 20 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=4jEgNMqNw6Q","video_lang":"Tagalog","video_title":"Filipino Style Roasted Chicken with Vegetables - Food Bae PH",
 "img":"https://images.pexels.com/photos/6210933/pexels-photo-6210933.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"One-tray roast: chicken pieces with potato, carrot, onion and bell pepper. Simple and healthy.",
 "ingredients":[
  ("Chicken pieces, bone-in (or half chicken)","400 g","800 g"),
  ("Potato, large chunks","1","2"),
  ("Carrot, chunks","1","2"),
  ("Onion, wedges","1","2"),
  ("Bell pepper, chunks","1/2","1"),
  ("Zucchini (optional)","1/2","1"),
  ("Garlic, minced","3 cloves","5 cloves"),
  ("Lemon juice","1 tbsp","2 tbsp"),
  ("Olive oil","2 tbsp","4 tbsp"),
  ("Paprika, dried oregano/thyme, black pepper","1/2 tsp each","1 tsp each"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Oven 200 C. Mix oil, lemon, garlic, paprika, herbs, salt, pepper.",
  "Rub half of the mix on the chicken (under the skin too). Toss the vegetables with the rest.",
  "Spread vegetables in a tray in one layer, chicken on top skin side up. Cover with foil.",
  "Bake 40 min covered. Remove foil, bake 20-25 min more until chicken is golden and juices run clear.",
  "Rest 5 min. Serve with the tray juices.",
 ],
 "tl":[
  "Isang layer lang ang gulay para ma-roast, hindi ma-steam.",
  "Foil muna 40 min, tapos alisin para gumintong ang balat.",
 ],
},
{
 "id":12,"name":"Chicken Salona","ar":"صالونة دجاج","emoji":"🍲","time":"50 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=CkJ57o5iWv8","video_lang":"Tagalog","video_title":"How to cook Chicken Salona - Marilou Recipes",
 "img":"https://images.pexels.com/photos/37505669/pexels-photo-37505669.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Emirati everyday chicken and vegetable stew with tomato, loomi and bzar spice. Served with white rice.",
 "ingredients":[
  ("Chicken pieces","350 g","700 g"),
  ("Onion, chopped","1","2"),
  ("Tomato, chopped","2","4"),
  ("Tomato paste","1 tbsp","2 tbsp"),
  ("Potato, cubed","1","2"),
  ("Carrot, cubed","1","2"),
  ("Zucchini or green beans","1/2 cup","1 cup"),
  ("Garlic","2 cloves","4 cloves"),
  ("Bzar / Emirati spice (or curry + cumin + coriander)","1 tbsp","2 tbsp"),
  ("Turmeric","1/4 tsp","1/2 tsp"),
  ("Dried lime (loomi)","1","2"),
  ("Oil","2 tbsp","3 tbsp"),
  ("Water","2 cups","4 cups"),
  ("Salt","to taste","to taste"),
  ("White rice to serve","1 cup","2 cups"),
 ],
 "steps":[
  "Fry onion in oil until golden. Add garlic, chicken, brown 5 min.",
  "Add bzar, turmeric, tomato paste. Stir 2 min. Add tomato, cook 5 min.",
  "Add water, loomi, salt. Cover, simmer 15 min.",
  "Add potato and carrot, simmer 15 min. Add zucchini / beans last 7 min. Sauce should be medium-thick.",
  "Serve hot with white rice.",
 ],
 "tl":[
  "Potato at carrot sa gitna ng pagluluto; zucchini sa huli para hindi malambot masyado.",
  "Hindi dapat lata (watery) ang sabaw; pakuluan ng walang takip kung sobra ang tubig.",
 ],
},
{
 "id":13,"name":"Lamb Salona","ar":"صالونة لحم","emoji":"🍲","time":"1 h 40 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=v2XMC2IOE3Y","video_lang":"Tagalog","video_title":"How to cook Salona Laham - Marilou Recipes",
 "img":"https://images.pexels.com/photos/20350170/pexels-photo-20350170.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Same stew with lamb. The lamb simmers first so it becomes tender before the vegetables go in.",
 "ingredients":[
  ("Lamb with bone, pieces","350 g","700 g"),
  ("Onion","1","2"),
  ("Tomato","2","4"),
  ("Tomato paste","1 tbsp","2 tbsp"),
  ("Potato, carrot, zucchini","1 each","2 each"),
  ("Garlic","2 cloves","4 cloves"),
  ("Bzar spice + turmeric","1 tbsp + 1/4 tsp","2 tbsp + 1/2 tsp"),
  ("Loomi","1","2"),
  ("Oil","2 tbsp","3 tbsp"),
  ("Water","3 cups","5 cups"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Fry onion golden, add garlic and lamb, brown 5 min.",
  "Add spices and tomato paste, stir 2 min, add tomato 5 min.",
  "Add water, loomi, salt. Cover, simmer 60-70 min until lamb is tender. Skim foam at the start.",
  "Add potato, carrot 15 min, zucchini last 7 min.",
  "Serve with white rice.",
 ],
 "tl":[
  "Lamb malambot muna (60-70 min) bago ilagay ang gulay.",
 ],
},
{
 "id":14,"name":"Mahshi Malfouf (Stuffed Cabbage Rolls)","ar":"محشي ملفوف","emoji":"🥬","time":"1 h 45 min","difficulty":"Medium",
 "video":"https://www.youtube.com/watch?v=8lVHVC6YXww","video_lang":"Tagalog","video_title":"How to make Cabbage Rolls / Malfouf - Kitchen with Sorayda",
 "img":"https://images.pexels.com/photos/32604524/pexels-photo-32604524.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Cabbage leaves rolled thin like a finger around rice and minced meat, cooked slowly in lemon-garlic broth.",
 "ingredients":[
  ("White cabbage","1/2 small head","1 small head"),
  ("Short-grain rice (Egyptian rice), washed","1/2 cup","1 cup"),
  ("Minced lamb or beef","150 g","300 g"),
  ("Tomato, finely chopped","1","2"),
  ("Tomato paste","1 tbsp","2 tbsp"),
  ("Garlic, crushed","4 cloves","8 cloves"),
  ("Dried mint","1 tsp","2 tsp"),
  ("7-spice + black pepper","1 tsp + 1/4 tsp","2 tsp + 1/2 tsp"),
  ("Lemon juice","2 tbsp","4 tbsp"),
  ("Olive oil","1 tbsp","2 tbsp"),
  ("Water or stock","2 cups","3.5 cups"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Cut the core from the cabbage. Boil whole cabbage in salted water 5-7 min, removing leaves as they soften. Cut out the thick vein of each leaf.",
  "Filling: mix raw rice, minced meat, tomato, half the garlic, 7-spice, pepper, salt, olive oil.",
  "Put 1 tablespoon filling along a leaf, fold sides, roll tightly into a thin cigar.",
  "Line the pot with leftover leaves. Pack rolls tightly in layers. Put a plate on top to hold them down.",
  "Mix water, tomato paste, remaining garlic, lemon, dried mint, salt. Pour until it just covers the rolls.",
  "Boil, then cover and simmer LOW 50-60 min. Rest 10 min. Serve with yogurt and lemon.",
 ],
 "tl":[
  "Manipis at masikip ang pag-roll, 1 kutsara lang ang laman (lalaki ang rice).",
  "Plato sa ibabaw habang niluluto para hindi lumutang at bumukas.",
 ],
},
{
 "id":15,"name":"Cajun Chicken with Lobia (Black-eyed Peas) and White Rice","ar":"دجاج كاجن مع لوبيا ورز أبيض","emoji":"🍗","time":"1 h 15 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=9qW7bqSpTNo","video_lang":"English","video_title":"Easy Cajun Grilled Chicken - Simple Living with Ms Tania",
 "video2":"https://www.youtube.com/watch?v=LoCbOF7PuFY","video2_title":"Black-eyed beans (Lobia) Egyptian way",
 "img":"https://images.pexels.com/photos/39414658/pexels-photo-39414658.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Cajun-spiced grilled chicken breast, served with black-eyed peas in tomato sauce and plain white rice. For Mohamed only when lobia is served (Einas avoids beans; give her the chicken with rice and salad).",
 "ingredients":[
  ("Chicken breast or thighs","250 g","500 g"),
  ("Cajun spice (mild)","1 tbsp","2 tbsp"),
  ("Olive oil + lemon","1 tbsp + 1 tbsp","2 tbsp + 2 tbsp"),
  ("Black-eyed peas, soaked overnight (or 1 can)","1/2 cup dry","1 cup dry"),
  ("Onion, chopped","1","2"),
  ("Tomato, chopped + tomato paste","2 + 1 tbsp","4 + 2 tbsp"),
  ("Garlic","3 cloves","5 cloves"),
  ("Cumin + coriander powder","1/2 tsp each","1 tsp each"),
  ("Water","2 cups","3.5 cups"),
  ("White rice, cooked","1 cup","2 cups"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Lobia: boil soaked beans in water 40-50 min until soft (canned: rinse, no boiling).",
  "Fry onion in oil golden, add garlic, tomato paste, cumin, coriander. Add tomato, cook 5 min.",
  "Add beans and 1 cup water, salt. Simmer 20 min until thick like a stew.",
  "Chicken: coat with cajun, oil, lemon, salt. Grill pan on high, 5-6 min each side (breast) until cooked. Rest 3 min, slice.",
  "Serve chicken slices with rice and lobia on the side.",
 ],
 "tl":[
  "Si Einas: WALANG lobia (beans). Chicken + rice + salad lang.",
  "Cajun spice: mild lang.",
 ],
},
{
 "id":16,"name":"Grilled Chicken with Molokhia and White Rice","ar":"دجاج مشوي مع ملوخية ورز","emoji":"🥬","time":"1 h","difficulty":"Medium",
 "video":"https://www.youtube.com/watch?v=vgyfk9PCN-Q","video_lang":"Tagalog","video_title":"Molokhia with Chicken (Saluyot sa Tagalog) - Mohd & Ley Omari",
 "img":"https://images.pexels.com/photos/20004982/pexels-photo-20004982.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Egyptian green jute-leaf soup (saluyot) in chicken stock with fried garlic and coriander. Served with grilled chicken and white rice. Molokhia must not boil after the leaves go in.",
 "ingredients":[
  ("Chicken pieces","350 g","700 g"),
  ("Frozen chopped molokhia (or 2 cups fresh, finely minced)","200 g","400 g"),
  ("Chicken stock (from boiling the chicken)","2 cups","4 cups"),
  ("Garlic, crushed","4 cloves","8 cloves"),
  ("Ground coriander","1 tsp","2 tsp"),
  ("Ghee or butter","1.5 tbsp","3 tbsp"),
  ("Onion, cardamom, bay leaf for the stock","1 set","1 set"),
  ("Lemon","1/2","1"),
  ("White rice, cooked","1 cup","2 cups"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Boil chicken with onion, cardamom, bay leaf, salt 30 min. Keep the stock. Grill the chicken in the oven 200 C 15 min for colour.",
  "Bring 2 cups stock to a simmer. Add frozen molokhia, stir until melted and combined. Keep on LOW, do NOT boil hard (it separates).",
  "Ta'leya: fry garlic in ghee until golden, add coriander 20 seconds. Pour immediately into the molokhia. Stir, cook 2 min, off.",
  "Serve molokhia in a bowl with lemon, rice and chicken on the plate.",
 ],
 "tl":[
  "HUWAG pakuluan nang malakas pagkalagay ng molokhia. Mahina lang. Kung kumulo nang malakas, maghihiwalay ang tubig at dahon.",
  "Bawang dapat golden, hindi sunog.",
 ],
},
{
 "id":17,"name":"Okra (Bamia) with Lamb and White Rice","ar":"بامية باللحم مع رز","emoji":"🫘","time":"1 h 40 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=yypa-uNFKr0","video_lang":"Tagalog","video_title":"Marag Bamya with Lamb - Angeline Canja",
 "img":"https://images.pexels.com/photos/6063320/pexels-photo-6063320.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Lamb stew with baby okra in garlic-tomato sauce. Okra stays whole and is added late so it does not become slimy.",
 "ingredients":[
  ("Lamb with bone","350 g","700 g"),
  ("Baby okra (fresh or frozen), whole","250 g","500 g"),
  ("Onion","1","2"),
  ("Tomato, grated","2","4"),
  ("Tomato paste","1 tbsp","2 tbsp"),
  ("Garlic, crushed","4 cloves","8 cloves"),
  ("Ground coriander + 7-spice","1 tsp + 1/2 tsp","2 tsp + 1 tsp"),
  ("Lemon juice","1 tbsp","2 tbsp"),
  ("Oil / ghee","2 tbsp","3 tbsp"),
  ("Water","3 cups","5 cups"),
  ("Salt","to taste","to taste"),
  ("White rice, cooked","1 cup","2 cups"),
 ],
 "steps":[
  "Fry onion golden, add lamb, brown 5 min. Add tomato paste, spices, tomato. Cook 5 min.",
  "Add water, salt. Cover, simmer 60-70 min until lamb is tender.",
  "Fry okra quickly in a little oil 3 min (keeps it firm). Add okra to the stew.",
  "Fry garlic in ghee golden with coriander, add to the pot with lemon juice. Simmer 15-20 min uncovered until sauce is thick.",
  "Serve with white rice.",
 ],
 "tl":[
  "HUWAG hiwain ang okra; buo lang. Huwag haluin nang madalas para hindi maging malapot (slimy).",
  "Okra sa huli lang (20 min), hindi kasabay ng lamb mula umpisa.",
 ],
},
{
 "id":18,"name":"Fried Chicken with Okra Stew and White Rice","ar":"دجاج مقلي مع بامية ورز","emoji":"🍗","time":"1 h","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=sc4QnMwS2V8","video_lang":"Tagalog","video_title":"Okra / Bamia with Chicken Salona - Marilou Recipes",
 "img":"https://images.pexels.com/photos/6063320/pexels-photo-6063320.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Okra in tomato-garlic sauce (no meat inside) served next to crispy fried chicken and white rice.",
 "ingredients":[
  ("Chicken pieces (leg, thigh)","350 g","700 g"),
  ("Marinade: yogurt 2 tbsp, garlic, paprika, salt","1 set","2 sets"),
  ("Flour for coating","1/2 cup","1 cup"),
  ("Oil for frying","as needed","as needed"),
  ("Baby okra, whole","250 g","500 g"),
  ("Onion","1","2"),
  ("Tomato, grated + paste","2 + 1 tbsp","4 + 2 tbsp"),
  ("Garlic","4 cloves","8 cloves"),
  ("Coriander powder","1 tsp","2 tsp"),
  ("Lemon juice","1 tbsp","2 tbsp"),
  ("Water","1 cup","2 cups"),
  ("White rice, cooked","1 cup","2 cups"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Marinate chicken 30 min. Coat in flour with salt and paprika. Fry in medium-hot oil 7-8 min each side until golden and cooked through (no pink at the bone). Drain on paper.",
  "Okra stew: fry onion golden, add garlic, coriander, tomato paste, tomato. Cook 5 min.",
  "Add okra and water, salt. Simmer 20 min uncovered until sauce thick. Finish with lemon.",
  "Serve chicken, okra and rice together.",
 ],
 "tl":[
  "Chicken: katamtamang init ng mantika. Kung sobrang init, sunog sa labas, hilaw sa loob.",
  "Okra buo, huwag haluin nang madalas.",
 ],
},
{
 "id":19,"name":"Musakhan Chicken with White Rice (Oven)","ar":"مسخن دجاج بالرز","emoji":"🧅","time":"1 h 15 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=cI6NslzSkNc","video_lang":"Tagalog","video_title":"Easy way to cook Chicken Musakhan - Els Kusinera",
 "img":"https://images.pexels.com/photos/19615781/pexels-photo-19615781.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Palestinian roasted chicken with lots of sumac and onion cooked soft in olive oil, served on flatbread with pine nuts, plus white rice on the side.",
 "ingredients":[
  ("Chicken pieces (thigh, leg)","400 g","800 g"),
  ("Onion, thinly sliced","2 large","4 large"),
  ("Sumac","2 tbsp","4 tbsp"),
  ("Olive oil","4 tbsp","8 tbsp"),
  ("7-spice + black pepper","1 tsp + 1/4 tsp","2 tsp + 1/2 tsp"),
  ("Lemon juice","1 tbsp","2 tbsp"),
  ("Taboon / Arabic bread","1","2"),
  ("Pine nuts or almonds, toasted","1 tbsp","2 tbsp"),
  ("White rice, cooked","1 cup","2 cups"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Rub chicken with half the sumac, 7-spice, pepper, lemon, 1 tbsp oil, salt. Bake 200 C 35-40 min until golden.",
  "Cook onion in the remaining olive oil on LOW 20-25 min until very soft and sweet (not brown). Add the rest of the sumac and salt. Cook 3 min.",
  "Put bread on a tray, spread the sumac onion over it, chicken on top, spoon some chicken juices. Oven 5 min to warm.",
  "Top with toasted nuts. Serve with white rice and yogurt.",
 ],
 "tl":[
  "Sibuyas: MAHINA ang apoy, 20-25 min, malambot at matamis, hindi brown.",
  "Maraming sumac: ito ang lasa ng musakhan.",
 ],
},
{
 "id":20,"name":"Spaghetti with Meatballs","ar":"سباغيتي بكرات اللحم","emoji":"🍝","time":"50 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=MAETFavPMXM","video_lang":"English","video_title":"Easy Spaghetti and Meatballs - Preppy Kitchen",
 "video2":"https://www.youtube.com/watch?v=YOG4UdcXMkU","video2_title":"Spaghetti & Meatballs Pinoy Style (Tagalog) - Mommy-Go-Round",
 "img":"https://images.pexels.com/photos/12214723/pexels-photo-12214723.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Italian-style, NOT sweet Filipino style: beef meatballs simmered in garlic tomato sauce over spaghetti with parmesan.",
 "ingredients":[
  ("Spaghetti","100 g","200 g"),
  ("Minced beef","200 g","400 g"),
  ("Breadcrumbs","2 tbsp","4 tbsp"),
  ("Egg","1 small","1"),
  ("Garlic, minced","3 cloves","5 cloves"),
  ("Onion, finely chopped","1/2","1"),
  ("Dried oregano + parsley","1/2 tsp each","1 tsp each"),
  ("Canned crushed tomatoes","1 cup (250 g)","2 cups (500 g)"),
  ("Tomato paste","1 tbsp","2 tbsp"),
  ("Olive oil","2 tbsp","3 tbsp"),
  ("Parmesan, grated","2 tbsp","4 tbsp"),
  ("Salt, pepper, pinch of sugar","to taste","to taste"),
 ],
 "steps":[
  "Mix minced beef, breadcrumbs, egg, half the garlic, oregano, salt, pepper. Roll into balls the size of a walnut. Do not over-mix.",
  "Brown meatballs in olive oil 2 min each side. Remove.",
  "Same pan: fry onion and remaining garlic 3 min. Add tomato paste 1 min, crushed tomatoes, pinch sugar, salt, pepper. Simmer 10 min.",
  "Return meatballs, cover, simmer 15 min.",
  "Boil spaghetti in salted water 1 min less than packet. Drain, toss in the sauce with a little pasta water. Serve with parmesan.",
 ],
 "tl":[
  "HINDI matamis: walang banana ketchup, walang sugar maliban sa isang kurot.",
  "Spaghetti 'al dente': may kaunting tigas pa, hindi malambot.",
 ],
},
{
 "id":21,"name":"Mashed Potato with Grilled Chicken","ar":"بطاطس مهروسة مع دجاج مشوي","emoji":"🥔","time":"40 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=EOa-jQXmVTg","video_lang":"English","video_title":"Grilled Chicken Breast with Creamy Mashed Potato - Priyanka Banerjee",
 "video2":"https://www.youtube.com/watch?v=Zl2DkxTpQ-4","video2_title":"Mashed Potato Recipe (Tagalog) - Juniors Tagalog Cooking Channel",
 "img":"https://images.pexels.com/photos/8697537/pexels-photo-8697537.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Smooth buttery mashed potato with a juicy grilled chicken breast and steamed vegetables. Light dinner option.",
 "ingredients":[
  ("Chicken breast","200 g (1 pc)","400 g (2 pcs)"),
  ("Olive oil, lemon, garlic, paprika, thyme, salt (marinade)","1 set","2 sets"),
  ("Potato, peeled, cubed","300 g (2 medium)","600 g (4 medium)"),
  ("Butter","2 tbsp","4 tbsp"),
  ("Warm milk (for Einas: oat milk or lactose-free)","1/4 cup","1/2 cup"),
  ("Broccoli / green beans / carrot","1 cup","2 cups"),
  ("Salt, white pepper","to taste","to taste"),
 ],
 "steps":[
  "Flatten chicken breast to even thickness (cover with plastic, press with a pan). Marinate 20 min.",
  "Boil potatoes in salted water 15-18 min until a knife goes in easily. Drain well, let steam dry 2 min.",
  "Mash with butter and warm milk until smooth. Season. Keep warm.",
  "Grill pan on high: chicken 5-6 min each side until cooked (cut: no pink). Rest 3 min, slice.",
  "Steam vegetables 5 min. Plate: mash, chicken, vegetables, a little olive oil or gravy.",
 ],
 "tl":[
  "Mashed potato kay Einas: oat milk o lactose-free milk lang, walang regular milk.",
  "Patagin (flatten) ang chicken breast para pantay ang luto at hindi matuyo.",
 ],
},
{
 "id":22,"name":"Chicken with Spinach and White Rice","ar":"دجاج بالسبانخ مع رز","emoji":"🥬","time":"45 min","difficulty":"Easy",
 "video":"https://www.youtube.com/watch?v=YebEQ7smBb8","video_lang":"English","video_title":"Spinach Chicken Curry (Palak Chicken) - Curries With Bumbi",
 "img":"https://images.pexels.com/photos/13513758/pexels-photo-13513758.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Chicken cooked in a mild spinach sauce (palak style, no cream for Einas). Healthy and filling with white rice.",
 "ingredients":[
  ("Chicken, boneless cubes","300 g","600 g"),
  ("Fresh spinach, washed (or 250 g frozen)","300 g","600 g"),
  ("Onion, chopped","1","2"),
  ("Tomato, chopped","1","2"),
  ("Ginger-garlic paste","1 tsp","2 tsp"),
  ("Cumin seeds","1/2 tsp","1 tsp"),
  ("Coriander powder + turmeric + garam masala","1 tsp + 1/4 tsp + 1/2 tsp","2 tsp + 1/2 tsp + 1 tsp"),
  ("Oil / ghee","2 tbsp","3 tbsp"),
  ("Lemon juice","1 tsp","2 tsp"),
  ("Salt","to taste","to taste"),
  ("White rice, cooked","1 cup","2 cups"),
 ],
 "steps":[
  "Blanch spinach in boiling water 1 min, drain, cool in cold water, squeeze and blend to a coarse puree.",
  "Fry cumin seeds in oil 20 seconds, add onion, cook golden. Add ginger-garlic 1 min, tomato and powdered spices, cook 5 min.",
  "Add chicken, coat, cook 8 min. Add 1/2 cup water, cover, 10 min.",
  "Add spinach puree, salt. Simmer 5-7 min only (keeps the green colour). Finish with lemon.",
  "Serve with white rice.",
 ],
 "tl":[
  "Spinach: 1 minuto lang sa kumukulong tubig, tapos malamig na tubig agad para manatiling berde.",
  "Walang cream, walang chili (para kay Einas).",
 ],
},
{
 "id":23,"name":"Madhbi Chicken with Rice","ar":"دجاج مظبي مع رز","emoji":"🔥","time":"1 h 15 min (plus marinating)","difficulty":"Medium",
 "video":"https://www.youtube.com/watch?v=3SNfPJp44rg","video_lang":"English","video_title":"Arabic Style Chicken Madhbi - Cook with Alma",
 "img":"https://images.pexels.com/photos/18698231/pexels-photo-18698231.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "intro":"Yemeni-style flattened chicken, marinated in madhbi spices and grilled (traditionally on hot stone; at home: very hot grill pan then oven). Served on spiced rice with sahawiq sauce.",
 "ingredients":[
  ("Half chicken, flattened (butterflied)","1/2 chicken (~600 g)","1 chicken (~1.2 kg)"),
  ("Yogurt","3 tbsp","6 tbsp"),
  ("Garlic, crushed","3 cloves","6 cloves"),
  ("Madhbi / hawaij spice (cumin, coriander, turmeric, cardamom, black pepper)","1.5 tbsp","3 tbsp"),
  ("Lemon juice","2 tbsp","4 tbsp"),
  ("Oil","2 tbsp","3 tbsp"),
  ("Basmati rice, washed, soaked","1 cup","2 cups"),
  ("Onion, chopped","1","2"),
  ("Whole spices: cardamom, cinnamon, cloves","1 set","1 set"),
  ("Turmeric for rice","1/4 tsp","1/2 tsp"),
  ("Chicken stock / water","1.5 cups","3 cups"),
  ("Sahawiq sauce: tomato, coriander, garlic, lemon (chili only for Mohamed)","1 set","1 set"),
  ("Salt","to taste","to taste"),
 ],
 "steps":[
  "Cut chicken along the backbone and press flat. Make deep cuts in thick parts. Marinate with yogurt, garlic, spices, lemon, oil, salt. Minimum 2 hours, overnight best.",
  "Heat a grill pan or heavy pan very hot. Sear chicken skin side down 6-8 min until charred, flip 5 min.",
  "Move to oven 190 C for 25-30 min until cooked through (juices clear).",
  "Rice: fry onion golden in ghee, add whole spices and turmeric, rice 1 min, stock, salt. Boil, cover LOW 18 min, rest 5 min.",
  "Sahawiq: blend tomato, coriander, garlic, lemon, salt (add green chili only in Mohamed's portion). Serve chicken on rice with sauce.",
 ],
 "tl":[
  "Napakainit na pan sa umpisa para sa 'char' (sunog-sunog na balat), tapos oven para maluto sa loob.",
  "Sahawiq para kay Einas: walang sili. Hiwalay na mangkok.",
 ],
},
]

SALADS = [
{"id":"S1","name":"Fattoush Salad","ar":"سلطة فتوش","emoji":"🥗","time":"20 min",
 "video":"https://www.youtube.com/watch?v=Lh2ujK9IFS0","video_lang":"English","video_title":"The best fattoush salad - Feel Good Foodie",
 "img":"https://images.pexels.com/photos/36879177/pexels-photo-36879177.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "ingredients":[("Romaine lettuce, chopped","2 cups","4 cups"),("Tomato, diced","1","2"),("Cucumber, diced","1/2","1"),("Radish, sliced","2","4"),("Spring onion / onion","1 tbsp","2 tbsp"),("Fresh mint + parsley","2 tbsp","4 tbsp"),("Arabic bread, toasted or fried until crisp","1/2","1"),("Dressing: lemon juice 1.5 tbsp, olive oil 2 tbsp, sumac 1 tsp, pomegranate molasses 1 tsp, garlic, salt","1 set","2 sets")],
 "steps":["Toast bread in oven 180 C until crisp, break into pieces.","Mix all vegetables and herbs in a bowl.","Whisk dressing. Add dressing and bread only at serving time."],
 "tl":["Tinapay at dressing: ilagay bago ihain lang, para hindi malata."]},
{"id":"S2","name":"Walnut Salad","ar":"سلطة الجوز","emoji":"🥗","time":"15 min",
 "video":"https://www.youtube.com/watch?v=v_z0g5IuD88","video_lang":"English","video_title":"10-Minute Apple Walnut Salad - Broke Bank Vegan",
 "img":"https://images.pexels.com/photos/32193925/pexels-photo-32193925.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "ingredients":[("Mixed green leaves","2 cups","4 cups"),("Apple, sliced thin","1/2","1"),("Walnuts, toasted","3 tbsp","6 tbsp"),("Pomegranate seeds or dried cranberries","2 tbsp","4 tbsp"),("Feta (lactose-free for Einas)","2 tbsp","4 tbsp"),("Dressing: balsamic vinegar 1 tbsp, olive oil 2 tbsp, honey 1 tsp, salt","1 set","2 sets")],
 "steps":["Toast walnuts in a dry pan 3 min.","Toss leaves, apple, pomegranate.","Add walnuts, feta, dressing just before serving."],
 "tl":["Apple: hiwain bago ihain lang (umiitim)."]},
{"id":"S3","name":"Corn Salad","ar":"سلطة الذرة","emoji":"🌽","time":"15 min",
 "video":"https://www.youtube.com/watch?v=TXT9LxDGGKE","video_lang":"English","video_title":"The Best Corn Salad - Inspired Taste",
 "img":"https://images.pexels.com/photos/4519056/pexels-photo-4519056.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "ingredients":[("Sweet corn kernels (boiled or canned, drained)","1 cup","2 cups"),("Cucumber, diced","1/2","1"),("Bell pepper (red), diced","1/2","1"),("Cherry tomatoes, halved","6","12"),("Red onion, finely chopped","1 tbsp","2 tbsp"),("Fresh coriander or parsley","2 tbsp","4 tbsp"),("Dressing: lime juice 1.5 tbsp, olive oil 1.5 tbsp, salt, pepper","1 set","2 sets")],
 "steps":["Mix all vegetables.","Add dressing, toss. Serve cold."],
 "tl":["Hindi creamy, walang mayonnaise. Lime at olive oil lang."]},
{"id":"S4","name":"Burghul (Bulgur) Salad / Tabbouleh","ar":"سلطة برغل / تبولة","emoji":"🌿","time":"25 min",
 "video":"https://www.youtube.com/watch?v=q2FVkPV2mds","video_lang":"English","video_title":"Tabouli Salad Recipe - The Mediterranean Dish",
 "img":"https://images.pexels.com/photos/15832880/pexels-photo-15832880.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "ingredients":[("Fine bulgur, soaked in hot water 15 min, squeezed","3 tbsp","6 tbsp"),("Parsley, very finely chopped","1.5 cups","3 cups"),("Fresh mint, chopped","2 tbsp","4 tbsp"),("Tomato, finely diced","1","2"),("Spring onion, chopped","1","2"),("Lemon juice","2 tbsp","4 tbsp"),("Olive oil","2 tbsp","4 tbsp"),("Salt","to taste","to taste")],
 "steps":["Soak bulgur, squeeze dry.","Chop parsley very fine with a sharp knife (do not blend).","Mix everything, add lemon, oil, salt. Rest 10 min."],
 "tl":["Parsley: pinong-pino sa kutsilyo, hindi sa blender (magiging lata)."]},
{"id":"S5","name":"Green Mix Salad","ar":"سلطة خضراء مشكلة","emoji":"🥬","time":"10 min",
 "video":"https://www.youtube.com/watch?v=shaMtIC4RbI","video_lang":"Tagalog","video_title":"Pinaka Madaling Vegetable Salad - Friend-Cheap Menu",
 "img":"https://images.pexels.com/photos/36425896/pexels-photo-36425896.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "ingredients":[("Mixed leaves (lettuce, rocket, baby spinach)","2 cups","4 cups"),("Cucumber, sliced","1/2","1"),("Cherry tomatoes","6","12"),("Avocado (optional)","1/2","1"),("Dressing: lemon 1 tbsp, olive oil 2 tbsp, salt, pepper","1 set","2 sets")],
 "steps":["Wash and dry leaves well.","Mix, add dressing at serving."],
 "tl":["Patuyuin ang dahon pagkatapos hugasan; basang dahon = lata."]},
{"id":"S6","name":"Greek Salad","ar":"سلطة يونانية","emoji":"🫒","time":"10 min",
 "video":"https://www.youtube.com/watch?v=fLiFdOR_ifI","video_lang":"English","video_title":"Greek Salad Recipe - Natasha's Kitchen",
 "img":"https://images.pexels.com/photos/34293330/pexels-photo-34293330.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "ingredients":[("Tomato, chunks","1 large","2 large"),("Cucumber, chunks","1/2","1"),("Red onion, thin slices","2 tbsp","4 tbsp"),("Kalamata olives","6","12"),("Feta block (lactose-free for Einas)","50 g","100 g"),("Dried oregano","1/2 tsp","1 tsp"),("Olive oil + red wine vinegar or lemon","2 tbsp + 1 tbsp","4 tbsp + 2 tbsp"),("Salt, pepper","to taste","to taste")],
 "steps":["Cut vegetables in big chunks.","Mix with olives, oil, vinegar, salt.","Put feta on top, sprinkle oregano."],
 "tl":["Malalaking hiwa; feta sa ibabaw, hindi hinahalo."]},
{"id":"S7","name":"Caesar Salad with Grilled Chicken","ar":"سلطة سيزر بالدجاج","emoji":"🥗","time":"25 min",
 "video":"https://www.youtube.com/watch?v=QIipQHe0css","video_lang":"English","video_title":"Perfect Chicken Caesar Salad - Inspired Taste",
 "video2":"https://www.youtube.com/watch?v=tNIg71OMCtY","video2_title":"Filipino-Style Caesar Salad - Yummy PH",
 "img":"https://images.pexels.com/photos/29935339/pexels-photo-29935339.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "ingredients":[("Romaine lettuce, chopped","2 cups","4 cups"),("Chicken breast, grilled, sliced","120 g","250 g"),("Croutons (toasted bread cubes)","1/2 cup","1 cup"),("Parmesan, shaved","2 tbsp","4 tbsp"),("Caesar dressing (bottle)","2 tbsp","4 tbsp")],
 "steps":["Season chicken with salt, pepper, garlic, oil. Grill 5-6 min each side. Rest, slice.","Toss lettuce with dressing.","Top with chicken, croutons, parmesan."],
 "tl":["Dressing sa hiwalay na lalagyan kapag lunch box."]},
{"id":"S8","name":"Halloumi Salad","ar":"سلطة حلوم","emoji":"🧀","time":"15 min",
 "video":"https://www.youtube.com/watch?v=thMEHZCmLCI","video_lang":"English","video_title":"Grilled Halloumi Salad - The Cooking Foodie",
 "img":"https://images.pexels.com/photos/8751410/pexels-photo-8751410.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "ingredients":[("Halloumi, sliced 1 cm","80 g","160 g"),("Mixed leaves / rocket","2 cups","4 cups"),("Cherry tomatoes","6","12"),("Cucumber","1/2","1"),("Pomegranate seeds (optional)","2 tbsp","4 tbsp"),("Dressing: lemon, olive oil, honey, mint","1 set","2 sets")],
 "steps":["Grill halloumi in a dry hot pan 2 min each side until golden. No oil needed.","Toss leaves, tomato, cucumber with dressing.","Put warm halloumi on top."],
 "tl":["Halloumi: tuyong pan, mainit, 2 min bawat side. Ihain agad habang mainit."]},
{"id":"S9","name":"Jarjeer (Rocket) Salad","ar":"سلطة جرجير","emoji":"🌱","time":"10 min",
 "video":"https://www.youtube.com/watch?v=MzWj-JF9AIo","video_lang":"Tagalog","video_title":"Arugula / Jarjeer Salad - Els Kusinera",
 "img":"https://images.pexels.com/photos/36212759/pexels-photo-36212759.jpeg?auto=compress&cs=tinysrgb&h=627&fit=crop&w=1200",
 "ingredients":[("Rocket (jarjeer) leaves","2 cups","4 cups"),("Onion, thin slices","2 tbsp","4 tbsp"),("Cherry tomatoes or tomato","6","12"),("Sumac","1/2 tsp","1 tsp"),("Lemon juice + olive oil","1 tbsp + 2 tbsp","2 tbsp + 4 tbsp"),("Salt","pinch","pinch")],
 "steps":["Wash and dry rocket.","Mix with onion, tomato.","Dress with lemon, oil, sumac, salt right before serving."],
 "tl":["Sumac ang nagbibigay ng maasim na lasa; huwag kalimutan."]},
]

FRUITS = [
 ("Banana + Apple + Watermelon","Saging + Mansanas + Pakwan","Peel and slice banana; slice apple with skin, drizzle lemon; watermelon in cubes, remove seeds."),
 ("Kiwi + Rockmelon + Orange","Kiwi + Melon + Orange","Peel and slice kiwi; rockmelon in cubes, no seeds; orange peeled and cut in segments, no white pith."),
 ("Pears + Mango + Banana","Peras + Mangga + Saging","Pear sliced with skin + lemon; mango peeled and cubed; banana sliced last."),
 ("Watermelon + Rockmelon + Kiwi","Pakwan + Melon + Kiwi","All in cubes, equal sizes, no seeds."),
 ("Apple + Kiwi + Mango","Mansanas + Kiwi + Mangga","Apple slices with lemon; kiwi peeled and sliced; mango cubed."),
]
