# -*- coding: utf-8 -*-
# HOME COOKBOOK, Breakfast recipes B1..B15. Servings: 2 adults. Spice level 0/5 everywhere.
# Each recipe follows the 17-section template used by build_book.py.
# Field notes:
#   meat: dict for the mandatory chicken / lamb specification table (None if no meat)
#   parts: list of parts; a simple dish has one part with title None
#   steps: dict(text, heat, time, done) so the builder can print pot / heat / time / doneness columns

SAY = "Sayidaty Kitchen (kitchen.sayidaty.net)"
MANAL = "Manal Alalem (manalonline.com)"
SHAM = "Shamlola (shamlola.com)"

BREAKFAST = [
# ---------------------------------------------------------------- B1
{
 "id": "B1", "name": "Pasolla", "arabic": "فاصوليا بيضاء بالصلصة",
 "cuisine": "Egyptian / Levantine", "category": "Breakfast",
 "times": {"prep": "10 min (plus overnight soak if using dried beans)", "cook": "40 min", "total": "50 min"},
 "difficulty": "Easy",
 "equipment": ["Medium pot with lid (2 to 3 L)", "Wooden spoon", "Chopping board and knife (vegetables)", "Measuring cups and spoons"],
 "meat": None,
 "spice_note": "Made with no chili of any kind. The original uses black pepper only; it was already non-spicy. Cumin and ground coriander give aroma, not heat.",
 "house_rule": "House rule: beans for breakfast are always served in a red tomato sauce, not dry. This recipe is the plain vegetarian version; the lamb cubes in some source recipes are left out for breakfast.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("White beans (cannellini / fasolia), canned, drained and rinsed", "400 g (1 can)", "or 150 g dried beans soaked overnight and boiled 50 min until soft"),
   ("Onion, finely chopped", "1 medium (120 g)", ""),
   ("Garlic, finely chopped", "2 cloves", ""),
   ("Tomato passata (smooth red tomato sauce)", "250 ml (1 cup)", "or 2 ripe tomatoes grated"),
   ("Tomato paste", "1 tbsp", ""),
   ("Vegetable oil or ghee", "2 tbsp", ""),
   ("Water or vegetable stock", "250 ml (1 cup)", ""),
   ("Salt", "1/2 tsp", "adjust at the end"),
   ("Black pepper, ground", "1/4 tsp", ""),
   ("Cumin, ground", "1/2 tsp", ""),
   ("Coriander, ground", "1/4 tsp", ""),
   ("Parsley, chopped (to finish)", "1 tbsp", "optional"),
  ],
  "prep_before": [
   "If using dried beans: soak 150 g in plenty of cold water overnight, drain, boil in fresh water 45 to 60 min until soft, drain.",
   "If using canned beans: open, pour into a sieve, rinse under cold water, let drain.",
   "Chop the onion and garlic. Measure the spices into a small bowl.",
  ],
  "steps": [
   {"text": "Heat the oil in the medium pot. Add the onion and cook, stirring, until soft and light golden.", "heat": "Medium", "time": "5 min", "done": "Onion is soft and golden, not brown"},
   {"text": "Add the garlic and stir for 1 minute until you smell it. Do not let it burn.", "heat": "Medium", "time": "1 min", "done": "Garlic smells sweet, still pale"},
   {"text": "Add the tomato passata and tomato paste. Add salt, black pepper, cumin and coriander. Stir well.", "heat": "Medium", "time": "1 min", "done": "Sauce is one even red color"},
   {"text": "Let the sauce bubble gently, uncovered, until it thickens and darkens slightly.", "heat": "Medium-low", "time": "10 min", "done": "Sauce coats the spoon; a little oil shows at the edges"},
   {"text": "Add the beans and the water or stock. Stir, bring back to a gentle bubble, then cover.", "heat": "Low", "time": "15 to 20 min", "done": "Beans are very soft and the sauce is thick, not watery"},
   {"text": "Taste. Add a pinch more salt if needed. Turn off the heat and stir in the parsley.", "heat": "Off", "time": "1 min", "done": "Ready to serve"},
  ],
 }],
 "mistakes": [
  "Sauce too thin: it was not reduced before the beans went in. Simmer uncovered a few more minutes.",
  "Beans still hard (dried beans): they were not soaked or boiled long enough. Canned beans avoid this problem.",
  "Burnt garlic gives a bitter taste. Add it after the onion is soft and stir only 1 minute.",
  "Too much tomato paste makes the dish sour. Stick to 1 tbsp.",
 ],
 "serving": ["Serve hot in a bowl with warm Arabic bread, sliced tomato and cucumber, and olives.", "A drizzle of olive oil on top is traditional."],
 "storage": ["Cool within 1 hour, then refrigerate in a covered container up to 3 days.", "Reheat in a pot over low heat with a splash of water until steaming hot (above 75 °C). Do not reheat more than once."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "طريقة عمل الفاصوليا البيضاء بالصلصة",
   "url": "https://kitchen.sayidaty.net/node/35150/طريقة-عمل-الفاصوليا-البيضاء-بالصلصة/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/e7/e7836f1211b96a2bd24b1698b6fbcc65_w360_h360.jpg",
   "status": "Verified: page opened and read. Adapted: scaled from 4 to 2 servings, lamb omitted for breakfast (house rule), canned-bean option added."},
},
# ---------------------------------------------------------------- B2
{
 "id": "B2", "name": "Fried Egg", "arabic": "بيض مقلي",
 "cuisine": "Everyday / Egyptian", "category": "Breakfast",
 "times": {"prep": "2 min", "cook": "5 min", "total": "7 min"},
 "difficulty": "Very easy",
 "equipment": ["Non-stick frying pan (24 cm) with lid", "Silicone or thin spatula", "Small bowl"],
 "meat": None,
 "spice_note": "Only a small pinch of black pepper. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Eggs", "4 (2 per person)", ""),
   ("Butter", "1 tbsp (15 g)", "or 1 tbsp vegetable oil"),
   ("Salt", "1/4 tsp", ""),
   ("Black pepper, ground", "1 pinch", ""),
   ("Cheddar cheese, grated (optional)", "2 tbsp", "the source adds cheese; leave out for plain eggs"),
  ],
  "prep_before": ["Take the eggs out of the fridge 10 minutes before cooking.", "Crack each egg into a small bowl first, so a broken yolk or shell piece can be removed."],
  "steps": [
   {"text": "Put the butter in the frying pan and let it melt and foam, swirling to coat the pan.", "heat": "Medium", "time": "1 min", "done": "Butter foams but does not brown"},
   {"text": "Slide the eggs in one at a time, keeping them apart. Sprinkle with salt and pepper.", "heat": "Medium", "time": "30 sec", "done": "Whites start to turn opaque at the edges"},
   {"text": "Cook until the white is set but the yolk is still soft. For a firmer egg, flip gently with the spatula and cook the second side.", "heat": "Medium-low", "time": "2 to 3 min (plus 1 min if flipped)", "done": "No clear, runny white remains. Yolk: soft (2 min) or firm (4 min)"},
   {"text": "If using cheese, sprinkle it on, cover the pan and cook until melted.", "heat": "Low", "time": "1 min", "done": "Cheese is melted"},
   {"text": "Slide onto warm plates and serve at once.", "heat": "Off", "time": "", "done": ""},
  ],
 }],
 "mistakes": ["Pan too hot: the bottom browns and goes crisp while the white on top is still raw. Use medium, not high.", "Adding eggs before the butter has melted makes them stick.", "Over-salting: salt lightly, the cheese is salty too."],
 "serving": ["Serve with warm Arabic bread or toast, sliced tomato and cucumber. Good next to Fried Halloumi (B9)."],
 "storage": ["Fried eggs are best eaten immediately. Do not keep for later."],
 "source": {"site": SHAM, "chef": "Shamlola (site recipe)", "recipe": "طريقة عمل بيض مقلي بالجبنة",
   "url": "https://shamlola.com/recipes/طريقة-عمل-بيض-مقلي-بالجبنة",
   "image": "https://shamlola.s3.amazonaws.com/Shamlola_Images/8/src/0235d9fa74945e1110257f7bcf99119a0df57be9.jpg",
   "status": "Verified: page opened and read. Adapted: 4 eggs for 2 adults, milk omitted, cheese made optional."},
},
# ---------------------------------------------------------------- B3
{
 "id": "B3", "name": "Boiled Egg", "arabic": "بيض مسلوق",
 "cuisine": "Everyday", "category": "Breakfast",
 "times": {"prep": "2 min", "cook": "6 to 10 min", "total": "15 min"},
 "difficulty": "Very easy",
 "equipment": ["Small pot (1.5 L)", "Slotted spoon", "Bowl of cold water with ice", "Timer"],
 "meat": None,
 "spice_note": "No spices needed; a little salt and black pepper at the table.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Eggs", "4 (2 per person)", "medium size, from the fridge"),
   ("Water", "1 L", "enough to cover the eggs by 2 cm"),
   ("Salt", "1/2 tsp", "in the water; helps if an egg cracks"),
   ("White vinegar", "1 tsp", "optional, same purpose"),
  ],
  "prep_before": ["Fill a bowl with cold water and a few ice cubes and keep it next to the stove.", "Check each egg for cracks; use cracked eggs for Fried Egg (B2) instead."],
  "steps": [
   {"text": "Put the water, salt and vinegar in the pot and bring to a full boil.", "heat": "High", "time": "5 min", "done": "Large bubbles, steady boil"},
   {"text": "Lower the eggs in gently with the slotted spoon. Start the timer now.", "heat": "Medium (gentle boil)", "time": "Soft: 6 min. Medium: 8 min. Hard: 10 min", "done": "Timer rings"},
   {"text": "Lift the eggs out and put them straight into the iced water. Leave 5 minutes.", "heat": "Off", "time": "5 min", "done": "Eggs are cool enough to hold"},
   {"text": "Tap on the counter, roll gently, and peel under a thin stream of water, starting at the wide end.", "heat": "", "time": "1 min per egg", "done": "Shell comes off cleanly"},
  ],
 }],
 "mistakes": ["Eggs cracking in the pot: they went into fast-boiling water from cold. Lower them gently and keep the boil medium.", "Grey ring around the yolk: over-cooked. Use the 10-minute maximum and cool at once.", "Hard to peel: eggs were not cooled in iced water, or are very fresh. Older eggs peel more easily."],
 "serving": ["Halve and sprinkle with salt and black pepper. Serve with bread, cucumber and olives, or use in Boiled Egg with Chicken Mix (B15)."],
 "storage": ["Hard-boiled eggs in the shell keep 5 days in the fridge. Peeled eggs: keep in a closed container up to 2 days.", "Do not freeze boiled eggs."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (chef tips page)", "recipe": "مدة سلق البيض",
   "url": "https://kitchen.sayidaty.net/node/12092/مدة-سلق-البيض/نصائح-الشيف",
   "image": "https://kitchen.sayidaty.net/uploads/small/81/8139feb2e19eed3067acec80271d2044_w750_h500.jpg",
   "status": "Verified: page opened and read (timing guide). Adapted into a step-by-step recipe for 2 adults."},
},
# ---------------------------------------------------------------- B4
{
 "id": "B4", "name": "Chicken Liver", "arabic": "كبدة دجاج بدبس الرمان",
 "cuisine": "Levantine", "category": "Breakfast",
 "times": {"prep": "10 min", "cook": "12 min", "total": "22 min"},
 "difficulty": "Easy",
 "equipment": ["Wide frying pan (28 cm)", "Separate chopping board and knife for raw meat", "Tongs or wooden spoon", "Kitchen paper"],
 "meat": {"animal": "Chicken", "type": "Offal (chicken liver), no bone", "cut": "Whole livers, trimmed of green or white membrane, halved if large", "skin": "N/A",
          "weight": "300 g", "prep": "Pat dry on kitchen paper (do not wash under running water); trim; season", "method": "Pan-fried in olive oil, finished with pomegranate molasses", "note": "Cut follows the original recipe (chicken liver)."},
 "spice_note": "The original (Manal Alalem) adds 2 chopped hot peppers. They are REMOVED. Only black pepper is used. The dish stays true to its nature: liver, onion-free, with sweet-sour pomegranate molasses.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Chicken livers, trimmed", "300 g", "see meat table"),
   ("Olive oil", "3 tbsp", ""),
   ("Salt", "1/2 tsp", ""),
   ("Black pepper, ground", "1/4 tsp", ""),
   ("Pomegranate molasses (dibs rumman)", "2 tbsp", ""),
   ("Parsley, chopped", "2 tbsp", "to finish"),
   ("Lemon wedges", "2", "for the table"),
  ],
  "prep_before": ["Use the raw-meat board. Trim the livers, cut large ones in half, and dry them on kitchen paper. Wet liver spits in hot oil.", "Wash hands, board and knife with hot soapy water immediately after."],
  "steps": [
   {"text": "Heat the olive oil in the wide pan until it shimmers.", "heat": "Medium-high", "time": "1 min", "done": "Oil moves easily, light haze"},
   {"text": "Add half the livers in one layer. Do not stir for the first minute, then turn. Cook until the juices they release have dried up. Remove to a plate and cook the second half the same way.", "heat": "Medium-high", "time": "4 min per batch", "done": "Livers are browned outside, no pink liquid in the pan"},
   {"text": "Return all the livers to the pan. Add salt, black pepper and the pomegranate molasses. Stir to coat.", "heat": "Low", "time": "2 min", "done": "Molasses bubbles and glazes the liver"},
   {"text": "Check doneness: cut the largest piece; it should be just faintly pink inside, not red, not grey and dry (internal 74 °C).", "heat": "Off", "time": "", "done": "Faint pink center, firm"},
   {"text": "Pour onto a plate, scatter the parsley and serve at once with lemon wedges.", "heat": "", "time": "", "done": ""},
  ],
 }],
 "mistakes": ["Crowding the pan: the liver boils in its own juice and turns grey. Cook in two batches.", "Over-cooking makes liver dry and grainy. Total time on the heat is about 6 minutes per batch.", "Adding the molasses too early burns it. Add it in the last 2 minutes on low heat."],
 "serving": ["Serve hot with warm Arabic bread, sliced onion rings (optional), tomato and lemon. Fried potato cubes (see B7, plain version) go well on the side."],
 "storage": ["Eat the same day if possible. Leftovers: cool, refrigerate covered, use within 1 day, reheat gently in a pan until steaming hot."],
 "source": {"site": MANAL, "chef": "Manal Alalem", "recipe": "كبدة الدجاج بدبس الرمان",
   "url": "https://www.manalonline.com/كبدة-الدجاج-بدبس-الرمان/",
   "image": "https://www.manalonline.com/images/crops/g16x9/كبدة-الدجاج-بدبس-الرمان-v2.jpg",
   "status": "Verified: page opened and read. Adapted: scaled from 1 kg to 300 g (2 adults), hot peppers removed."},
},
# ---------------------------------------------------------------- B5
{
 "id": "B5", "name": "Chickpeas", "arabic": "بليلة (حمص حب مسلوق)",
 "cuisine": "Levantine / Gulf", "category": "Breakfast",
 "times": {"prep": "5 min (plus overnight soak if dried)", "cook": "10 min (canned) or 60 min (dried)", "total": "15 min with canned"},
 "difficulty": "Very easy",
 "equipment": ["Small pot (1.5 L)", "Sieve", "Serving bowls"],
 "meat": None,
 "spice_note": "Only cumin and a little black pepper. No chili. (Some restaurants add chili flakes on top; do not.)",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Chickpeas, canned, drained and rinsed", "400 g (1 can)", "or 150 g dried, soaked overnight and boiled 60 to 90 min until very soft"),
   ("Water", "150 ml", ""),
   ("Garlic, crushed to a paste", "1 small clove", ""),
   ("Lemon juice, fresh", "2 tbsp", ""),
   ("Salt", "1/2 tsp", ""),
   ("Cumin, ground", "1/2 tsp", ""),
   ("Black pepper, ground", "1 pinch", "optional"),
   ("Olive oil", "1 tbsp", "to finish"),
   ("Parsley, chopped", "1 tbsp", "to finish"),
  ],
  "prep_before": ["Rinse canned chickpeas well in the sieve.", "Squeeze the lemon; crush the garlic with a pinch of salt."],
  "steps": [
   {"text": "Put the chickpeas and the water in the small pot. Bring to a gentle boil.", "heat": "Medium", "time": "4 min", "done": "Small bubbles, chickpeas hot through"},
   {"text": "Add the garlic, salt and half the cumin. Simmer so the chickpeas take the flavor.", "heat": "Low", "time": "5 min", "done": "Chickpeas are very soft; a little liquid remains"},
   {"text": "Turn off the heat. Add the lemon juice and stir.", "heat": "Off", "time": "", "done": ""},
   {"text": "Ladle into two bowls with a little of the liquid. Sprinkle the rest of the cumin, the black pepper, olive oil and parsley on top.", "heat": "", "time": "1 min", "done": "Served hot"},
  ],
 }],
 "mistakes": ["Dried chickpeas still hard: not soaked or boiled long enough. A pinch of baking soda in the boiling water helps them soften.", "Too dry: keep a little cooking liquid in the bowl; balila is eaten like a thick soup.", "Lemon added while boiling loses its fresh taste. Add it off the heat."],
 "serving": ["Serve warm in bowls with a spoon, warm bread, and pickles. A sprinkle of cumin on top is the classic finish."],
 "storage": ["Refrigerate covered up to 3 days. Reheat in a pot with a splash of water until steaming hot."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "بليلة",
   "url": "https://kitchen.sayidaty.net/node/1648/بليلة/المقبلات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/node_gallery/baleelah.jpg",
   "status": "Verified: page opened and read. Adapted: scaled from 1 kg boiled chickpeas (4 servings) to 1 can (2 adults); olive oil and parsley finish added."},
},
# ---------------------------------------------------------------- B6
{
 "id": "B6", "name": "Sandwich Pizza", "arabic": "ساندويش بيتزا (بيتزا التوست)",
 "cuisine": "Everyday / International", "category": "Breakfast",
 "times": {"prep": "10 min", "cook": "12 min", "total": "22 min"},
 "difficulty": "Easy",
 "equipment": ["Oven (or toaster oven)", "Baking tray lined with baking paper", "Small bowl and spoon", "Grater"],
 "meat": None,
 "spice_note": "Pizza sauce must be a plain tomato sauce; check the jar label for 'hot', 'spicy', 'arrabbiata' or chili and avoid those. Dried oregano only.",
 "house_rule": "No minced meat and no salami: the topping is cheese, vegetables and optional cooked chicken strips.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Toast bread (sandwich loaf) or 2 small French rolls", "4 slices", ""),
   ("Pizza sauce (plain tomato, not spicy)", "4 tbsp", "or tomato paste 2 tbsp mixed with 2 tbsp water and 1/4 tsp oregano"),
   ("Mozzarella cheese, grated", "100 g (1 cup)", ""),
   ("Tomato, thinly sliced", "1 small", ""),
   ("Black olives, sliced", "2 tbsp", ""),
   ("Green bell pepper (sweet), thin strips", "1/4 pepper", "sweet pepper only, never hot"),
   ("Cooked chicken breast, shredded (optional)", "60 g", "leftover grilled or boiled chicken"),
   ("Dried oregano", "1/2 tsp", ""),
   ("Olive oil", "1 tsp", "to brush"),
  ],
  "prep_before": ["Heat the oven to 200 °C.", "Grate the cheese, slice the tomato, olives and pepper."],
  "steps": [
   {"text": "Lay the bread on the tray. Brush the top lightly with olive oil and toast in the oven until just firm.", "heat": "Oven 200 °C", "time": "3 min", "done": "Bread surface is dry and pale gold"},
   {"text": "Spread 1 tbsp sauce on each slice, leaving a 1 cm edge.", "heat": "", "time": "1 min", "done": ""},
   {"text": "Top with chicken (if using), tomato, pepper and olives. Cover with the mozzarella and sprinkle oregano.", "heat": "", "time": "2 min", "done": ""},
   {"text": "Bake until the cheese is melted and bubbling and the edges are golden.", "heat": "Oven 200 °C", "time": "8 min", "done": "Cheese bubbles, bread edges are crisp"},
   {"text": "Cut each slice in half diagonally. Serve hot.", "heat": "", "time": "", "done": ""},
  ],
 }],
 "mistakes": ["Wet toppings (too much tomato or sauce) make the bread soggy. Toast the bread first and use thin tomato slices.", "Cheese not melting: oven not hot enough, or cheese put on cold from the fridge in a thick layer.", "Leaving it too long dries the bread; take it out as soon as the cheese bubbles."],
 "serving": ["Serve hot with cucumber sticks or a small Green Mix Salad (S5)."],
 "storage": ["Best eaten at once. Leftovers: refrigerate up to 1 day and reheat in the oven at 180 °C for 5 min (not the microwave, which makes the bread chewy)."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "بيتزا التوست السهلة",
   "url": "https://kitchen.sayidaty.net/node/6450/بيتزا-التوست-السهلة/البيتزا/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/12/122949290263cf012d2f581850238ded_w360_h360.jpg",
   "status": "Verified: page opened and read (also read: ساندويش البيتزا بالفيديو, node/36203, Lina Al-Hourani). Adapted: scaled to 2 adults, salami replaced with optional cooked chicken (house rule), hot ingredients excluded."},
},
# ---------------------------------------------------------------- B7
{
 "id": "B7", "name": "Potato", "arabic": "بطاطا حرّة (بدون شطة)",
 "cuisine": "Levantine (Lebanese / Syrian)", "category": "Breakfast",
 "times": {"prep": "10 min", "cook": "20 min", "total": "30 min"},
 "difficulty": "Easy",
 "equipment": ["Deep frying pan or wok", "Slotted spoon", "Kitchen paper on a plate", "Chopping board and knife (vegetables)"],
 "meat": None,
 "spice_note": "IMPORTANT: the traditional Levantine 'batata harra' is made with red chili paste (shatta). Here the chili is REMOVED and replaced with sweet paprika for color. The flavor base (garlic, fresh coriander, lemon) is kept, so the dish keeps its character but is completely non-spicy. The name in Arabic literally means 'hot potato'; ours is not hot.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Potatoes, peeled, 2 cm cubes", "2 large (500 g)", ""),
   ("Vegetable oil for shallow frying", "150 ml", ""),
   ("Garlic, finely chopped", "3 cloves", ""),
   ("Fresh coriander leaves, chopped", "4 tbsp (a small bunch)", ""),
   ("Sweet paprika (NOT hot paprika)", "1/2 tsp", "replaces the chili paste; check the label says sweet"),
   ("Lemon juice, fresh", "2 tbsp", ""),
   ("Salt", "1/2 tsp", ""),
   ("Olive oil", "1 tbsp", "for the garlic"),
  ],
  "prep_before": ["Peel and cube the potatoes. Rinse in cold water to remove starch and dry very well on a towel (wet potato spits in oil).", "Chop the garlic and coriander; squeeze the lemon."],
  "steps": [
   {"text": "Heat the frying oil in the deep pan until a potato cube dropped in sizzles at once.", "heat": "Medium-high", "time": "3 min", "done": "Oil about 170 °C; a cube sizzles immediately"},
   {"text": "Fry the potato cubes in one layer (two batches if needed), turning now and then, until golden and crisp outside and soft inside.", "heat": "Medium-high", "time": "8 to 10 min per batch", "done": "Golden all over; a cube is soft when pressed"},
   {"text": "Lift out with the slotted spoon onto kitchen paper. Pour the frying oil out of the pan (into a heat-proof container, never the sink).", "heat": "Off", "time": "1 min", "done": ""},
   {"text": "Return the pan to the heat with 1 tbsp olive oil. Add the garlic and stir until fragrant and barely golden.", "heat": "Low", "time": "1 min", "done": "Garlic smells sweet, pale gold"},
   {"text": "Add the potatoes back, then the coriander, paprika and salt. Toss to coat.", "heat": "Medium", "time": "2 min", "done": "Coriander wilted, potatoes evenly coated"},
   {"text": "Turn off the heat, add the lemon juice, toss once more and serve.", "heat": "Off", "time": "", "done": ""},
  ],
 }],
 "mistakes": ["Soggy potatoes: cubes were wet, the oil was not hot enough, or the pan was overcrowded.", "Burnt garlic: it needs only 1 minute on low heat; it turns bitter if brown.", "Lemon added on high heat loses its brightness; add it off the heat.", "Using hot paprika or chili by mistake. Read the label: 'sweet paprika' only."],
 "serving": ["Serve hot as a breakfast side with eggs (B2, B10), halloumi (B9), bread and yogurt."],
 "storage": ["Best fresh. Leftovers: refrigerate up to 2 days, reheat in a hot dry pan or oven at 200 °C for 8 min to re-crisp."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "بطاطا حرة",
   "url": "https://kitchen.sayidaty.net/node/10366/بطاطا-حرة/المقبلات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/f9/f9ae2d30e5001bfa3e7d25bf9739b66f_w360_h360.jpg",
   "status": "Verified: page opened and read (2 servings in the original). Adapted: chili paste (shatta) removed and replaced with sweet paprika; this changes the dish from spicy to non-spicy as required."},
},
# ---------------------------------------------------------------- B8
{
 "id": "B8", "name": "Feta Cheese Sandwich", "arabic": "ساندويش جبنة فيتا",
 "cuisine": "Levantine / Everyday", "category": "Breakfast",
 "times": {"prep": "8 min", "cook": "0 min (or 3 min if toasted)", "total": "10 min"},
 "difficulty": "Very easy",
 "equipment": ["Chopping board and knife (vegetables)", "Fork", "Toaster (optional)"],
 "meat": None,
 "spice_note": "No pepper needed beyond a pinch of black pepper. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Toast bread or Arabic bread", "4 slices or 2 loaves", ""),
   ("Feta cheese", "120 g", "white brined cheese"),
   ("Cucumber, thin slices", "1 small", ""),
   ("Tomato, thin slices", "1 small", ""),
   ("Fresh mint leaves", "8 leaves", "or 1/2 tsp dried mint"),
   ("Olive oil", "2 tsp", ""),
   ("Black pepper, ground", "1 pinch", ""),
   ("Black olives, pitted (optional)", "6", ""),
  ],
  "prep_before": ["If the feta is very salty, soak it in cold water 10 minutes and pat dry.", "Slice the cucumber and tomato thinly; lay tomato slices on kitchen paper so they do not wet the bread."],
  "steps": [
   {"text": "Toast the bread lightly if you like it warm and crisp.", "heat": "Toaster, medium", "time": "2 min", "done": "Pale golden"},
   {"text": "Crumble or slice the feta and spread it over 2 slices (or inside the Arabic bread). Press lightly with a fork.", "heat": "", "time": "2 min", "done": ""},
   {"text": "Lay on the cucumber, tomato, mint and olives. Drizzle olive oil and add a pinch of black pepper.", "heat": "", "time": "2 min", "done": ""},
   {"text": "Close with the second slice, press, cut in half diagonally and serve.", "heat": "", "time": "1 min", "done": ""},
  ],
 }],
 "mistakes": ["Wet tomato makes the bread soggy: blot the slices first and assemble just before eating.", "Very salty feta: soak it in water first; do not add salt to this sandwich."],
 "serving": ["Serve with black tea with mint. Good with Boiled Egg (B3) on the side."],
 "storage": ["Assemble fresh. Cut feta keeps in its brine in the fridge up to 1 week; sliced vegetables up to 1 day covered."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "سندويش جبنة وخيار بارد",
   "url": "https://kitchen.sayidaty.net/node/39486/سندويش-جبنة-وخيار-بارد/السندويشات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/67/67f6d7ae94c8a3692521efe9c8bebf1b_w360_h360.jpg",
   "status": "Verified: page opened and read (2 servings, cream cheese and cucumber). Adapted: feta cheese instead of cream cheese to match the dish name; tomato and olives added."},
},
# ---------------------------------------------------------------- B9
{
 "id": "B9", "name": "Fried Halloumi", "arabic": "جبنة حلوم مقلية",
 "cuisine": "Levantine / Cypriot", "category": "Breakfast",
 "times": {"prep": "5 min", "cook": "6 min", "total": "11 min"},
 "difficulty": "Very easy",
 "equipment": ["Non-stick frying pan (24 cm)", "Spatula or tongs", "Kitchen paper"],
 "meat": None,
 "spice_note": "No spices needed. Dried thyme (zaatar) or mint for aroma only. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Halloumi cheese, sliced 1 cm thick", "200 g (about 6 slices)", ""),
   ("Butter", "1 tbsp (15 g)", "or 1 tbsp olive oil"),
   ("Dried thyme or dried mint", "1/4 tsp", "to finish"),
   ("Lemon wedges", "2", ""),
   ("Tomato and cucumber slices", "for serving", ""),
  ],
  "prep_before": ["Slice the halloumi and pat the slices dry with kitchen paper; wet cheese will not brown."],
  "steps": [
   {"text": "Melt the butter in the non-stick pan.", "heat": "Medium", "time": "1 min", "done": "Butter foams"},
   {"text": "Lay the slices in without overlapping. Do not move them for 2 minutes, then turn.", "heat": "Medium", "time": "2 to 3 min per side", "done": "Deep golden crust on both sides, soft inside"},
   {"text": "Lift onto a plate, sprinkle thyme or mint and serve at once with lemon.", "heat": "Off", "time": "", "done": ""},
  ],
 }],
 "mistakes": ["Moving the slices too early tears the crust. Leave them still until golden.", "Halloumi goes rubbery when it cools; serve immediately.", "Adding salt: halloumi is already salty."],
 "serving": ["Serve hot with tomato, cucumber, olives, warm bread and a squeeze of lemon. Pairs with Fried Egg (B2) or Potato (B7)."],
 "storage": ["Eat at once. Unopened halloumi keeps for months in the fridge; opened, keep in its brine up to 1 week."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "الجبن الحلوم المقلي للفطور",
   "url": "https://kitchen.sayidaty.net/node/35978/الجبن-الحلوم-المقلي-للفطور/المقبلات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/37/374cc0ac7ae06ca83b5fdfd66b39403c_w360_h360.jpg",
   "status": "Verified: page opened and read. Adapted: scaled to 2 adults (200 g)."},
},
# ---------------------------------------------------------------- B10
{
 "id": "B10", "name": "Sunny-Side-Up Egg", "arabic": "بيض عيون بالطماطم",
 "cuisine": "Egyptian / Everyday", "category": "Breakfast",
 "times": {"prep": "3 min", "cook": "7 min", "total": "10 min"},
 "difficulty": "Very easy",
 "equipment": ["Non-stick frying pan (24 cm) with lid", "Spatula", "Small bowl"],
 "meat": None,
 "spice_note": "Salt and a pinch of black pepper only. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Eggs", "4", ""),
   ("Tomato, sliced 1 cm thick", "1 medium", ""),
   ("Ghee or butter", "1 tbsp", ""),
   ("Salt", "1/4 tsp", ""),
   ("Black pepper, ground", "1 pinch", ""),
   ("Parsley, chopped", "1 tbsp", "to finish"),
  ],
  "prep_before": ["Slice the tomato. Crack each egg into a small bowl before adding to the pan."],
  "steps": [
   {"text": "Melt the ghee in the pan and lay in the tomato slices. Cook, turning once, until soft.", "heat": "Medium", "time": "2 min per side", "done": "Tomato soft and lightly browned"},
   {"text": "Slide the eggs on top of the tomato (one bowl at a time), keeping yolks whole. Season with salt and pepper.", "heat": "Medium-low", "time": "30 sec", "done": ""},
   {"text": "Cover with the lid so the steam cooks the top of the white. Do not flip.", "heat": "Low", "time": "3 to 4 min", "done": "White fully set (no clear jelly), yolk still bright and soft"},
   {"text": "Lift carefully with the spatula onto plates, sprinkle parsley and serve.", "heat": "Off", "time": "", "done": ""},
  ],
 }],
 "mistakes": ["Clear, slimy white on top: the pan was not covered. The lid is the secret.", "Hard yolk: cooked too long; check at 3 minutes.", "Breaking the yolk when cracking directly into the pan; use the small bowl."],
 "serving": ["Serve with warm bread to dip into the yolk, plus cucumber and olives. 'Eyes' eggs are the classic Egyptian breakfast."],
 "storage": ["Eat immediately. Do not store."],
 "source": {"site": SHAM, "chef": "Shamlola (site recipe)", "recipe": "طريقة عمل بيض عيون بالطماطم",
   "url": "https://shamlola.com/recipes/طريقة-عمل-بيض-عيون-بالطماطم",
   "image": "https://shamlola.s3.amazonaws.com/Shamlola_Images/8/src/5b3cb3c28aa1e504bbe548a1aa28de8dbe6342f8.jpg",
   "status": "Verified: page opened and read. Used as written for 2 adults (4 eggs)."},
},
# ---------------------------------------------------------------- B11
{
 "id": "B11", "name": "Halloumi Sandwich", "arabic": "ساندويش حلوم مشوي",
 "cuisine": "Levantine", "category": "Breakfast",
 "times": {"prep": "10 min", "cook": "10 min", "total": "20 min"},
 "difficulty": "Easy",
 "equipment": ["Non-stick frying pan or griddle pan", "Spatula", "Chopping board and knife (vegetables)", "Kitchen paper"],
 "meat": None,
 "spice_note": "The breakfast-sandwich source offers hot sauce 'to taste'. It is REMOVED. Nothing hot is used.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Toast bread or 2 small baguette pieces", "4 slices", ""),
   ("Halloumi, sliced 1 cm", "200 g", ""),
   ("Tomato, sliced", "1 medium", ""),
   ("Eggplant, sliced 1 cm rounds", "1 small (150 g)", "optional, as in the source"),
   ("Rocket leaves (jarjeer)", "a handful", "or lettuce"),
   ("Olive oil", "2 tbsp", ""),
   ("Butter", "1 tbsp", ""),
   ("Salt", "1 pinch", "for the eggplant only"),
  ],
  "prep_before": ["Slice the halloumi, tomato and eggplant. Dry the halloumi with paper.", "Wash and dry the rocket."],
  "steps": [
   {"text": "Heat 2 tbsp olive oil in the pan. Fry the eggplant slices until golden on both sides; season with a pinch of salt. Then fry the tomato slices 1 minute per side. Drain both on kitchen paper.", "heat": "Medium-high", "time": "6 min", "done": "Eggplant golden and soft; tomato softened"},
   {"text": "Wipe the pan, melt the butter and fry the halloumi slices until golden on both sides.", "heat": "Medium", "time": "2 min per side", "done": "Golden crust"},
   {"text": "Toast the bread lightly in the same pan or in a toaster.", "heat": "Medium", "time": "1 min", "done": "Light gold"},
   {"text": "Build each sandwich: bread, halloumi, eggplant, tomato, rocket, bread. Press, cut in half and serve warm.", "heat": "", "time": "2 min", "done": ""},
  ],
 }],
 "mistakes": ["Eggplant soaking up too much oil: the pan must be hot before the slices go in.", "Assembling early: halloumi hardens as it cools. Serve within minutes."],
 "serving": ["Serve warm with cucumber sticks and tea."],
 "storage": ["Eat at once; the sandwich does not keep."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "ساندويش حلوم مشوي",
   "url": "https://kitchen.sayidaty.net/node/36062/ساندويش-حلوم-مشوي/السندويشات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/00/005998900a525fba93eeb4b12a3ee3cf_w360_h360.jpg",
   "status": "Verified: page opened and read (2 servings). Used as written; hot sauce from the alternative page (node/40284) excluded."},
},
# ---------------------------------------------------------------- B12
{
 "id": "B12", "name": "Egg Omelette", "arabic": "أومليت بالجبنة",
 "cuisine": "Everyday", "category": "Breakfast",
 "times": {"prep": "5 min", "cook": "6 min", "total": "11 min"},
 "difficulty": "Easy",
 "equipment": ["Non-stick frying pan (20 to 24 cm) with lid", "Bowl and fork or whisk", "Silicone spatula"],
 "meat": None,
 "spice_note": "Salt and a pinch of black pepper only. Sweet bell pepper may be added; never hot pepper.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Eggs", "4", ""),
   ("Milk", "2 tbsp", ""),
   ("Salt", "1/4 tsp", ""),
   ("Black pepper, ground", "1 pinch", ""),
   ("Cheese slices (Gouda, Edam or cheddar)", "2 slices (40 g)", "or 3 tbsp grated"),
   ("Butter", "1 tbsp", ""),
   ("Optional filling: chopped tomato, parsley, sweet pepper", "3 tbsp total", ""),
  ],
  "prep_before": ["Beat the eggs with the milk, salt and pepper until no streaks of white remain.", "Have the cheese and any filling ready next to the stove; the omelette cooks fast."],
  "steps": [
   {"text": "Melt the butter in the pan and swirl to coat.", "heat": "Medium", "time": "1 min", "done": "Butter foams, not brown"},
   {"text": "Pour in the eggs. As the edges set, push them gently toward the center with the spatula and tilt the pan so raw egg runs underneath.", "heat": "Medium-low", "time": "2 min", "done": "Mostly set, top still slightly wet"},
   {"text": "Lay the cheese (and filling) over one half. Cover with the lid.", "heat": "Low", "time": "2 min", "done": "Cheese melted, top no longer wet"},
   {"text": "Fold the empty half over the cheese, slide onto a plate and cut in two.", "heat": "Off", "time": "", "done": "Pale yellow outside, no browning needed"},
  ],
 }],
 "mistakes": ["High heat browns and toughens the omelette. Keep it medium-low.", "Over-beating with lots of milk makes it watery; 2 tbsp milk is enough.", "Folding before the center is set makes it leak."],
 "serving": ["Serve with toast or Arabic bread, sliced tomato and cucumber."],
 "storage": ["Eat at once."],
 "source": {"site": SHAM, "chef": "Shamlola (site recipe)", "recipe": "طريقة عمل أومليت بالجبنة",
   "url": "https://shamlola.com/recipes/طريقة-عمل-أومليت-بالجبنة",
   "image": "https://shamlola.s3.amazonaws.com/Shamlola_Images/8/src/a3bc0fad0657f08091001d1aeb2160c5cd183207.jpg",
   "status": "Verified: page opened and read. Adapted: doubled to 4 eggs for 2 adults; optional vegetable filling from the site's vegetable omelette page."},
},
# ---------------------------------------------------------------- B13
{
 "id": "B13", "name": "Shakshuka Egg", "arabic": "شكشوكة بيض",
 "cuisine": "Egyptian / Levantine", "category": "Breakfast",
 "times": {"prep": "10 min", "cook": "15 min", "total": "25 min"},
 "difficulty": "Easy",
 "equipment": ["Frying pan (24 to 26 cm) with lid", "Wooden spoon", "Chopping board and knife (vegetables)"],
 "meat": None,
 "spice_note": "Many shakshuka recipes add chili or hot pepper. This one uses sweet green bell pepper and sweet paprika only. Cumin for aroma. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Eggs", "4", ""),
   ("Onion, finely chopped", "1 small (80 g)", ""),
   ("Green bell pepper (sweet), small dice", "1/2 pepper", ""),
   ("Tomatoes, ripe, small dice", "3 medium (350 g)", "or 200 ml passata plus 1 fresh tomato"),
   ("Tomato paste", "1 tsp", ""),
   ("Vegetable oil or olive oil", "2 tbsp", ""),
   ("Sugar", "1/4 tsp", "balances the tomato acidity, as in the source"),
   ("Salt", "1/2 tsp", ""),
   ("Black pepper, ground", "1 pinch", ""),
   ("Cumin, ground", "1/4 tsp", ""),
   ("Sweet paprika", "1/4 tsp", "optional, for color"),
   ("Parsley, chopped", "1 tbsp", "to finish"),
  ],
  "prep_before": ["Chop the onion, pepper and tomatoes.", "Crack each egg into a small cup before adding to the pan."],
  "steps": [
   {"text": "Heat the oil in the pan. Cook the onion until soft and translucent.", "heat": "Medium", "time": "4 min", "done": "Soft, glossy, not brown"},
   {"text": "Add the green pepper and cook 2 minutes, then the tomatoes, tomato paste, sugar, salt, pepper, cumin and paprika. Stir.", "heat": "Medium", "time": "3 min", "done": "Tomatoes start to break down"},
   {"text": "Simmer uncovered until the mixture is thick and saucy, not watery.", "heat": "Medium-low", "time": "5 min", "done": "A spoon dragged through leaves a trail for a second"},
   {"text": "Make 4 hollows with the spoon and slide one egg into each. Cover with the lid.", "heat": "Low", "time": "4 to 5 min", "done": "Whites set, yolks still soft"},
   {"text": "Sprinkle parsley and bring the pan to the table.", "heat": "Off", "time": "", "done": ""},
  ],
 }],
 "mistakes": ["Watery sauce: tomatoes not reduced enough before the eggs. Wait until thick.", "Over-cooked eggs: check at 4 minutes; they continue cooking in the hot pan.", "Hot pepper used by mistake: only sweet bell pepper goes in."],
 "serving": ["Serve straight from the pan with warm Arabic bread for scooping. Cucumber and olives on the side."],
 "storage": ["The tomato base (without eggs) keeps 3 days in the fridge; reheat and add fresh eggs. Cooked eggs do not keep well."],
 "source": {"site": SHAM, "chef": "Shamlola (site recipe)", "recipe": "طريقة عمل شكشوكة البيض للسحور",
   "url": "https://shamlola.com/recipes/طريقة-عمل-شكشوكة-البيض-للسحور",
   "image": "https://shamlola.s3.amazonaws.com/Shamlola_Images/8/src/50157714dc52a5f1b341e8191d3b7a8ca819929d.jpg",
   "status": "Verified: page opened and read. Adapted: more tomato for a saucier base, cumin and sweet paprika added, oil reduced; 4 eggs for 2 adults."},
},
# ---------------------------------------------------------------- B14
{
 "id": "B14", "name": "Chicken Mix", "arabic": "سلطة دجاج بالمايونيز (للساندويش)",
 "cuisine": "International / Everyday", "category": "Breakfast",
 "times": {"prep": "10 min", "cook": "15 min (poaching the chicken)", "total": "30 min (plus 20 min chilling)"},
 "difficulty": "Easy",
 "equipment": ["Small pot (1.5 L) with lid", "Separate chopping board and knife for raw chicken", "Two forks (for shredding)", "Mixing bowl", "Meat thermometer (recommended)"],
 "meat": {"animal": "Chicken", "type": "Boneless", "cut": "Breast fillet", "skin": "Skinless", "weight": "250 g (1 large breast)",
          "prep": "Do not wash. Pat dry, trim fat. Poach whole in seasoned water, cool, shred", "method": "Poached (gently simmered), then shredded and mixed cold",
          "note": "Cut follows the original recipe (boiled chicken breast)."},
 "spice_note": "No chili. Mustard is a mild yellow mustard (not hot English mustard). Black pepper only.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Chicken breast, skinless, boneless", "250 g", "see meat table"),
   ("Water", "500 ml", "to poach"),
   ("Bay leaf, cardamom pod, salt", "1 leaf, 1 pod, 1/2 tsp", "for the poaching water"),
   ("Mayonnaise", "4 tbsp", ""),
   ("Mild yellow mustard", "1/2 tsp", ""),
   ("Lemon juice", "1 tbsp", ""),
   ("Olive oil", "1 tsp", ""),
   ("Pickled cucumber, very finely diced", "1 small", ""),
   ("Celery or green onion, finely chopped (optional)", "1 tbsp", ""),
   ("Salt", "1/4 tsp", ""),
   ("Black pepper, ground", "1 pinch", ""),
  ],
  "prep_before": ["Dry the chicken on paper (never wash raw chicken). Use the raw-meat board; wash hands and tools after.", "Dice the pickle, squeeze the lemon."],
  "steps": [
   {"text": "Put the water, bay leaf, cardamom and salt in the small pot and bring to a boil. Add the chicken breast.", "heat": "High then Low", "time": "2 min", "done": "Water returns to a gentle simmer"},
   {"text": "Cover and simmer very gently (small bubbles only) until cooked through.", "heat": "Low", "time": "12 to 15 min", "done": "Internal 74 °C; cut the thickest part: white all through, no pink"},
   {"text": "Lift out and let cool 10 minutes, then shred finely with two forks (or chop into 1 cm pieces). Discard the water or keep for soup.", "heat": "Off", "time": "12 min", "done": "Shreds are fine and even"},
   {"text": "In the bowl mix mayonnaise, mustard, lemon juice, olive oil, salt and pepper. Add the chicken, pickle and celery. Fold together.", "heat": "", "time": "3 min", "done": "Every piece is coated, mixture holds together"},
   {"text": "Cover and chill at least 20 minutes before using.", "heat": "Fridge", "time": "20 min", "done": "Cold and firm"},
  ],
 }],
 "mistakes": ["Boiling hard makes the chicken stringy; keep the water barely bubbling.", "Mixing warm chicken into mayonnaise makes the mix oily and unsafe; cool first.", "Too much mayonnaise hides the chicken; add it gradually."],
 "serving": ["Spread in toast or Arabic bread with lettuce for breakfast sandwiches, or serve a scoop on lettuce leaves. Base for Boiled Egg with Chicken Mix (B15)."],
 "storage": ["Keep refrigerated in a sealed container and use within 2 days. Never leave mayonnaise mixtures out for more than 1 hour.", "Do not freeze."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "سلطة الدجاج بالمايونيز",
   "url": "https://kitchen.sayidaty.net/node/13306/سلطة-الدجاج-بالمايونيز/السلطات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/03/036b3e3b10adf0e4e0d00c5f774e35f1_w360_h360.png",
   "status": "Verified: page opened and read (3 servings). Adapted: scaled to 2 adults, poaching method written out in full, mild mustard specified."},
},
# ---------------------------------------------------------------- B15
{
 "id": "B15", "name": "Boiled Egg with Chicken Mix", "arabic": "بيض مسلوق مع سلطة الدجاج بالمايونيز",
 "cuisine": "International / Everyday", "category": "Breakfast",
 "times": {"prep": "10 min", "cook": "25 min", "total": "40 min (plus chilling)"},
 "difficulty": "Easy",
 "equipment": ["Small pot for eggs", "Small pot for chicken", "Separate raw-chicken board and knife", "Mixing bowl", "Serving plates"],
 "meat": {"animal": "Chicken", "type": "Boneless", "cut": "Breast fillet", "skin": "Skinless", "weight": "250 g",
          "prep": "Do not wash; pat dry; poach; shred", "method": "Poached and shredded (Part 1)", "note": "Same as Chicken Mix (B14)."},
 "spice_note": "No chili anywhere. Black pepper at the table only.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Chicken Mix", "ingredients": [
    ("Chicken Mix (recipe B14), full quantity", "1 batch", "chicken breast 250 g, mayonnaise 4 tbsp, mustard, lemon, pickle, salt, pepper"),
   ], "prep_before": ["Follow recipe B14 completely, including chilling."],
   "steps": [{"text": "Make the Chicken Mix exactly as in recipe B14 and keep it in the fridge.", "heat": "See B14", "time": "30 min + chilling", "done": "Cold, coated, firm"}]},
  {"title": "Part 2: Boiled Eggs", "ingredients": [
    ("Eggs", "4", ""), ("Water", "1 L", ""), ("Salt", "1/2 tsp", ""),
   ], "prep_before": ["Prepare the iced water bowl."],
   "steps": [{"text": "Boil the eggs as in recipe B3 for 9 minutes (medium-firm), cool in iced water and peel.", "heat": "Medium boil", "time": "9 min + 5 min cooling", "done": "Yolk set but still slightly creamy in the center"}]},
  {"title": "Part 3: Assembly", "ingredients": [
    ("Lettuce leaves", "4", ""), ("Toast bread or Arabic bread", "4 slices", ""), ("Black pepper", "1 pinch", ""), ("Parsley, chopped", "1 tsp", ""),
   ], "prep_before": ["Wash and dry the lettuce."],
   "steps": [
    {"text": "Halve the eggs lengthwise. Lay lettuce on each plate, add a mound of Chicken Mix, and arrange 4 egg halves around it.", "heat": "", "time": "3 min", "done": ""},
    {"text": "Sprinkle black pepper and parsley on the eggs. Serve with the bread on the side (or fill the bread with the mix and egg slices as a sandwich).", "heat": "", "time": "1 min", "done": ""},
   ]},
 ],
 "timeline": [
  "0:00  Start poaching the chicken (B14 step 1).",
  "0:05  While the chicken simmers, boil the water for the eggs.",
  "0:10  Eggs in, timer 9 minutes.",
  "0:15  Chicken done; lift out to cool. Eggs out into iced water (0:19).",
  "0:25  Shred the chicken, mix with the dressing, chill. Peel the eggs.",
  "0:45  Plate and serve (or keep both parts covered in the fridge until breakfast).",
 ],
 "presentation": ["Mix in the center, egg halves around it yolk-side up, bread and lettuce on the side. A few olives or cherry tomatoes add color."],
 "mistakes": ["Warm egg or warm chicken on the mayonnaise mix: both must be cold.", "Under-boiled eggs (6 min) are too runny to hold on the plate; use 9 minutes here."],
 "serving": ["A filling breakfast for 2. Also packs well in a lunch box if kept cold."],
 "storage": ["Chicken Mix: 2 days refrigerated. Peeled eggs: 2 days refrigerated. Assemble just before serving."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipes)", "recipe": "سلطة الدجاج بالمايونيز + مدة سلق البيض",
   "url": "https://kitchen.sayidaty.net/node/13306/سلطة-الدجاج-بالمايونيز/السلطات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/03/036b3e3b10adf0e4e0d00c5f774e35f1_w360_h360.png",
   "status": "Verified: both pages opened and read. This combined dish is a household combination of the two verified recipes (not a single published recipe)."},
},
]
