# -*- coding: utf-8 -*-
# HOME COOKBOOK, Mains M17..M23. Servings: 2 adults. Spice level 0/5.
from mains1 import RAW_CHICKEN_PREP, RAW_LAMB_PREP, SAY, MANAL, SHAM
from mains2 import white_rice_part, WHITE_RICE_SRC

MAINS3 = [
# ---------------------------------------------------------------- M17
{
 "id": "M17", "name": "Okra with Lamb and White Rice", "arabic": "بامية باللحم مع رز أبيض",
 "cuisine": "Egyptian / Levantine", "category": "Main",
 "times": {"prep": "20 min", "cook": "1 h 45 min", "total": "2 h 05 min"},
 "difficulty": "Easy",
 "equipment": ["Pot with lid (3 L)", "Frying pan (okra)", "Medium pot for rice", "Separate raw-meat board and knife"],
 "meat": {"animal": "Lamb", "type": "Boneless (original: cubed lamb)", "cut": "Shoulder, 3 cm cubes", "skin": "N/A; trim fat",
          "weight": "450 g", "prep": RAW_LAMB_PREP, "method": "Browned with onion, simmered in tomato sauce, okra added near the end",
          "note": "Cut follows the original (cubed lamb); shoulder suggested."},
 "spice_note": "No chili in the Shamlola original. Ground coriander, cumin and a little cinnamon; black pepper 1/4 tsp.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Okra with lamb",
   "ingredients": [
    ("Lamb cubes", "450 g", "see meat table"),
    ("Okra (bamia), small, fresh or frozen", "400 g", "trim stems without cutting into the pod"),
    ("Olive oil or ghee", "3 tbsp", ""),
    ("Onion, chopped", "1 large", ""),
    ("Garlic, crushed", "4 cloves", ""),
    ("Tomato passata", "400 ml", "or 4 grated tomatoes"),
    ("Tomato paste", "1 tbsp", ""),
    ("Hot water", "400 ml", ""),
    ("Coriander, ground", "1 tsp", ""),
    ("Cumin, ground", "1/2 tsp", ""),
    ("Cinnamon, ground", "1/4 tsp", ""),
    ("Salt", "1 tsp", ""),
    ("Black pepper, ground", "1/4 tsp", ""),
    ("Lemon juice", "1 tbsp", "at the end"),
    ("Fresh coriander, chopped", "2 tbsp", ""),
   ],
   "prep_before": ["Trim the okra; if fresh, wash and dry completely (wet okra goes slimy).", "Dry and cube the lamb."],
   "steps": [
    {"text": "Heat 2 tbsp oil; cook the onion until golden, add garlic 1 minute.", "heat": "Medium", "time": "7 min", "done": "Golden"},
    {"text": "Add the lamb, salt, pepper, coriander, cumin and cinnamon; brown.", "heat": "Medium-high", "time": "8 min", "done": "Browned all over"},
    {"text": "Add passata, tomato paste and hot water. Boil, cover, simmer until the lamb is tender.", "heat": "Low", "time": "60 to 70 min", "done": "Fork-tender"},
    {"text": "Meanwhile fry the okra in 1 tbsp oil in the frying pan, turning, until bright green and lightly browned at the edges (this keeps it firm).", "heat": "Medium-high", "time": "5 min", "done": "Bright green, slightly blistered"},
    {"text": "Add the okra to the lamb. Simmer uncovered until the okra is tender and the sauce thick.", "heat": "Low", "time": "20 min", "done": "Okra soft but whole; sauce coats the spoon"},
    {"text": "Off the heat add lemon juice and fresh coriander.", "heat": "Off", "time": "", "done": ""},
   ]},
  white_rice_part(2),
 ],
 "timeline": ["0:00  Onion, lamb, sauce; simmer 65 min. Soak rice.", "1:00  Fry okra. Start the rice at 1:05.", "1:15  Okra into the stew, 20 min.", "1:35  Serve."],
 "presentation": ["Rice on the plate, stew spooned beside it, lemon wedge, coriander."],
 "mistakes": ["Stirring the okra a lot breaks it and makes it slimy. Fold gently, once or twice.", "Cutting into the okra pod when trimming releases the slime; trim only the cap.", "Adding okra too early: it dissolves. Last 20 minutes only."],
 "serving": ["Serve hot for 2 with white rice and bread."],
 "storage": ["Keeps 3 days refrigerated; freezes 1 month. Reheat until steaming."],
 "source": {"site": SHAM, "chef": "Shamlola (site recipe)", "recipe": "طريقة عمل طاجن البامية باللحم الضأني",
   "url": "https://shamlola.com/recipes/طريقة-عمل-طاجن-البامية-باللحم-الضأني",
   "image": "https://shamlola.s3.amazonaws.com/Shamlola_Images/8/src/7e480891667cbdbd673b675cac55f7ea2abf5b84.jpg",
   "status": "Verified: page opened and read (also read the lamb-shank version). Adapted: cooked on the stove instead of the oven for simplicity, spices from the shank version, scaled to 2 adults. " + WHITE_RICE_SRC},
},
# ---------------------------------------------------------------- M18
{
 "id": "M18", "name": "Fried Chicken with Okra and White Rice", "arabic": "دجاج مقلي مع بامية ورز أبيض",
 "cuisine": "Egyptian / Everyday", "category": "Main",
 "times": {"prep": "25 min (plus 3 h marinating)", "cook": "50 min", "total": "1 h 15 min plus marinating"},
 "difficulty": "Medium",
 "equipment": ["Deep frying pan or deep pot for frying", "Thermometer for oil and meat", "Pot with lid (2.5 L) for okra", "Medium pot for rice", "Separate raw-chicken board and knife", "Wire rack and kitchen paper"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Drumsticks (2) and thighs (2)", "skin": "Skin-on",
          "weight": "650 g", "prep": RAW_CHICKEN_PREP + " Marinate 3 hours in the fridge.", "method": "Marinated, coated, deep-fried",
          "note": "The Shamlola marinade is written for 1 kg of mixed chicken pieces; bone-in drumsticks and thighs are our suggestion (they fry evenly)."},
 "spice_note": "No chili. The Shamlola marinade uses sweet paprika (1/4 tsp) and black pepper only. Soy sauce gives color and salt.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Fried chicken",
   "ingredients": [
    ("Chicken drumsticks and thighs", "650 g", "see meat table"),
    ("MARINADE: lemon juice", "3 tbsp", ""),
    ("MARINADE: soy sauce", "3 tbsp", ""),
    ("MARINADE: tomato passata", "3 tbsp", ""),
    ("MARINADE: garlic, crushed", "1 tsp", ""),
    ("MARINADE: salt", "1/2 tsp", ""),
    ("MARINADE: black pepper", "1/4 tsp", ""),
    ("MARINADE: sweet paprika", "1/4 tsp", ""),
    ("COATING: flour", "60 g (1/2 cup)", ""),
    ("COATING: cornstarch", "60 g (1/2 cup)", ""),
    ("COATING: breadcrumbs", "100 g (1 cup)", ""),
    ("Vegetable oil for deep frying", "1 L", ""),
   ],
   "prep_before": ["Mix the marinade; coat the chicken; refrigerate 3 hours.", "Mix flour, cornstarch and breadcrumbs on a plate."],
   "steps": [
    {"text": "Heat the oil to 170 °C (a cube of bread browns in 40 seconds).", "heat": "Medium-high", "time": "8 min", "done": "170 °C"},
    {"text": "Lift the pieces from the marinade, let excess drip, roll in the coating, pressing it on.", "heat": "", "time": "3 min", "done": "Fully coated"},
    {"text": "Fry 2 pieces at a time, turning every 3 minutes, keeping the oil between 160 and 170 °C.", "heat": "Medium", "time": "14 to 16 min per batch", "done": "Deep golden; internal 75 °C at the bone; juices clear"},
    {"text": "Drain on the rack over paper. Keep warm in a low oven (90 °C) while frying the second batch.", "heat": "Oven 90 °C", "time": "", "done": ""},
   ]},
  {"title": "Part 2: Okra in tomato sauce (no meat)",
   "ingredients": [
    ("Okra, small", "350 g", "trimmed, dried"),
    ("Olive oil", "2 tbsp", ""),
    ("Onion, chopped", "1", ""),
    ("Garlic, crushed", "3 cloves", ""),
    ("Tomato passata", "300 ml", ""),
    ("Hot water", "150 ml", ""),
    ("Coriander, ground", "1 tsp", ""),
    ("Salt", "3/4 tsp", ""),
    ("Black pepper", "1/4 tsp", ""),
    ("Lemon juice", "1 tbsp", ""),
   ],
   "prep_before": ["Trim and dry the okra."],
   "steps": [
    {"text": "Fry the okra in the oil until bright green and lightly blistered; remove.", "heat": "Medium-high", "time": "5 min", "done": "Bright, slightly browned"},
    {"text": "In the same pot cook onion and garlic until golden, add passata, water, coriander, salt and pepper; simmer 5 minutes.", "heat": "Medium", "time": "10 min", "done": "Sauce slightly thick"},
    {"text": "Return the okra, cover, simmer until tender. Finish with lemon.", "heat": "Low", "time": "15 min", "done": "Okra tender, sauce thick"},
   ]},
  white_rice_part(3),
 ],
 "timeline": ["-3:00 Marinate the chicken.", "0:00  Okra sauce started. Soak rice.", "0:20  Start the rice. Heat the frying oil.", "0:30  Fry chicken batch 1; 0:46 batch 2.", "1:05  Serve."],
 "presentation": ["Rice, okra sauce beside it, fried chicken on a separate plate so it stays crisp. Lemon wedges."],
 "mistakes": ["Oil too hot: coating burns before the inside cooks. Use the thermometer.", "Crowding the pan drops the oil temperature and makes greasy chicken.", "Check the thickest piece at the bone: 75 °C, no pink."],
 "serving": ["Serve hot for 2."],
 "storage": ["Fried chicken is best fresh; refrigerate up to 2 days and re-crisp in the oven at 200 °C for 12 min. Okra sauce keeps 3 days. Never reuse frying oil more than twice; cool and filter it."],
 "source": {"site": SHAM, "chef": "Shamlola (site recipes)", "recipe": "طريقة عمل تتبيلة الدجاج المقلي المقرمش + طريقة عمل الأرز بالبامية",
   "url": "https://shamlola.com/recipes/طريقة-عمل-تتبيلة-الدجاج-المقلي-المقرم",
   "image": "https://shamlola.s3.amazonaws.com/Shamlola_Images/8/src/5a3bd921de73104631273d553080afb90199d048.jpg",
   "status": "Verified: both pages opened and read. Adapted: marinade scaled from 1 kg to 650 g; okra cooked as a tomato stew (Shamlola's okra-rice page simmers okra in stock) to match the household dish. " + WHITE_RICE_SRC},
},
# ---------------------------------------------------------------- M19
{
 "id": "M19", "name": "Musakhan Chicken with White Rice in Oven", "arabic": "مسخن دجاج مع رز أبيض بالفرن",
 "cuisine": "Palestinian", "category": "Main",
 "times": {"prep": "25 min", "cook": "1 h 20 min", "total": "1 h 45 min"},
 "difficulty": "Medium",
 "equipment": ["Pot (3 L) for boiling chicken", "Wide pan with lid for the onions", "Oven tray", "Medium pot for rice", "Separate raw-chicken board and knife", "Meat thermometer"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Leg quarters, 2", "skin": "Skin-on",
          "weight": "700 g", "prep": RAW_CHICKEN_PREP, "method": "Boiled with aromatics, then baked on the sumac onions until golden",
          "note": "Chef Imtiaz Al-Jitawi's original boils a whole cut chicken; leg quarters are our suggestion for 2 adults."},
 "spice_note": "No chili. Sumac is sour, not hot; it is the heart of this dish. Allspice-style 'mixed spice' (non-hot) and black pepper 1/2 tsp.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Boil the chicken",
   "ingredients": [
    ("Chicken leg quarters", "2 (700 g)", "see meat table"),
    ("Water", "1.2 L", ""),
    ("Onion, halved", "1", ""),
    ("Bay leaf", "1", ""), ("Cardamom pods", "3", ""), ("Whole cloves", "2", ""),
    ("Salt", "1 1/2 tsp", ""),
   ],
   "prep_before": ["Dry the chicken."],
   "steps": [
    {"text": "Boil the chicken with the aromatics, skim, and simmer.", "heat": "Low", "time": "35 min", "done": "Internal 74 °C"},
    {"text": "Lift out; keep 100 ml of the stock for the onions (the rest can cook the rice instead of water).", "heat": "Off", "time": "2 min", "done": ""},
   ]},
  {"title": "Part 2: Sumac onions and baking",
   "ingredients": [
    ("Onions, sliced thin", "4 large (600 g)", "the onions are the dish; do not reduce"),
    ("Olive oil", "100 ml", "generous, as in the original"),
    ("Sumac", "4 tbsp", "plus 1 tsp for the chicken"),
    ("Salt", "3/4 tsp", ""),
    ("Black pepper, ground", "1/2 tsp", ""),
    ("Mixed spice (non-hot)", "1/2 tsp", ""),
    ("Chicken stock (Part 1)", "100 ml", ""),
    ("Taboon or Arabic bread", "2 large loaves", ""),
    ("Pine nuts or slivered almonds, fried golden", "3 tbsp", ""),
   ],
   "prep_before": ["Slice the onions; fry the nuts."],
   "steps": [
    {"text": "Put the onions and olive oil in the wide pan. Cook gently, covered, stirring now and then, until completely soft and sweet (not browned).", "heat": "Low", "time": "25 min", "done": "Translucent, collapsed, sweet"},
    {"text": "Add sumac, salt, pepper, mixed spice and the stock. Cook 5 minutes more.", "heat": "Low", "time": "5 min", "done": "Deep purple-red, glossy"},
    {"text": "Heat the oven to 200 °C. Lay the bread on the tray, spread two-thirds of the onions over it, set the chicken on top, spoon the rest of the onions over the chicken and sprinkle 1 tsp sumac.", "heat": "", "time": "5 min", "done": ""},
    {"text": "Bake until the chicken skin is golden and the bread edges are crisp.", "heat": "Oven 200 °C", "time": "20 min", "done": "Golden chicken, crisp bread edges"},
    {"text": "Scatter the fried nuts.", "heat": "", "time": "", "done": ""},
   ]},
  white_rice_part(3),
 ],
 "timeline": ["0:00  Chicken into the pot. Slice onions.", "0:10  Onions on low, 30 min. Soak rice.", "0:35  Chicken out. Oven on.", "0:45  Assemble and bake 20 min. Start the rice.", "1:10  Serve."],
 "presentation": ["Bring the tray to the table: bread, onions, chicken, nuts. White rice in a bowl beside it, yogurt and Green Mix Salad (S5)."],
 "mistakes": ["Browning the onions: musakhan onions are soft and sweet, never fried brown. Low heat, lid on.", "Too little sumac or oil: the dish tastes flat. Use the quantities.", "Dry chicken: it was already cooked; the oven step is only 20 minutes for color."],
 "serving": ["Serve hot for 2."],
 "storage": ["Onion mixture keeps 3 days refrigerated. Assembled musakhan is best fresh; reheat at 180 °C for 10 min."],
 "source": {"site": SAY, "chef": "Chef Imtiaz Al-Jitawi (Sayidaty Kitchen)", "recipe": "مسخن دجاج",
   "url": "https://kitchen.sayidaty.net/node/8560/مسخن-دجاج/وصفات-دجاج/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/4a/4a0b8321fe15fd2274ed88c7d185dc81_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings; also read Sahar Al-Sharif's step-by-step node/12237 and Lama Shihab's video version node/14648). Adapted: scaled from 2 kg onions to 600 g for 2 adults. Samira Basharat (chef 4243) has no musakhan on her Sayidaty listing page; the Sayidaty chef version above was used. " + WHITE_RICE_SRC},
},
# ---------------------------------------------------------------- M20
{
 "id": "M20", "name": "Spaghetti with Meatballs", "arabic": "سباغيتي بكرات اللحم",
 "cuisine": "Italian-American", "category": "Main",
 "times": {"prep": "25 min", "cook": "40 min", "total": "1 h 05 min"},
 "difficulty": "Easy",
 "equipment": ["Large pot (4 L) for pasta", "Wide pan with lid for sauce", "Mixing bowl", "Separate raw-meat board", "Meat thermometer"],
 "meat": {"animal": "Lamb or beef (minced)", "type": "Minced", "cut": "Lean minced beef or lamb (15 percent fat)", "skin": "N/A",
          "weight": "250 g (makes about 10 meatballs)", "prep": "Keep minced meat cold; mix with clean hands; wash hands and bowl after.", "method": "Shaped, pan-fried, then simmered in the tomato sauce",
          "note": "Cut follows the original (minced meat)."},
 "spice_note": "No chili. Dried oregano, garlic, black pepper 1/4 tsp. Use a plain tomato passata, not 'arrabbiata'.",
 "house_rule": "FOR EINAS ONLY. Mohamed does not eat minced meat in pasta. When cooking for both: make the sauce without meatballs for Mohamed and top his spaghetti with sliced grilled chicken breast (see S7 chicken method) or serve his plain with sauce and parmesan. Cook the meatballs in a separate small pan for Einas.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Meatballs",
   "ingredients": [
    ("Minced beef or lamb", "250 g", "see meat table"),
    ("Breadcrumbs", "4 tbsp", ""),
    ("Milk", "2 tbsp", ""),
    ("Egg", "1 small", ""),
    ("Garlic, crushed", "1 clove", ""),
    ("Dried oregano", "1/2 tsp", ""),
    ("Parsley, chopped", "1 tbsp", ""),
    ("Salt", "1/2 tsp", ""),
    ("Black pepper", "1/4 tsp", ""),
    ("Vegetable oil", "2 tbsp", ""),
   ],
   "prep_before": ["Soak the breadcrumbs in the milk 5 minutes. Mix everything (except oil) with your hands just until combined; do not over-mix. Roll into 10 balls, 4 cm."],
   "steps": [
    {"text": "Heat the oil in the wide pan; brown the meatballs on all sides (they finish cooking in the sauce). Remove to a plate.", "heat": "Medium-high", "time": "6 min", "done": "Browned outside"},
   ]},
  {"title": "Part 2: Tomato sauce and spaghetti",
   "ingredients": [
    ("Spaghetti", "200 g", ""),
    ("Salt for pasta water", "1 tbsp", ""),
    ("Onion, finely chopped", "1 small", ""),
    ("Garlic, chopped", "2 cloves", ""),
    ("Olive oil", "1 tbsp", ""),
    ("Tomato passata (plain)", "400 ml", ""),
    ("Sugar", "1/2 tsp", ""),
    ("Dried oregano", "1/2 tsp", ""),
    ("Salt", "1/2 tsp", ""),
    ("Black pepper", "1 pinch", ""),
    ("Parmesan, grated", "3 tbsp", ""),
    ("Parsley or basil", "1 tbsp", ""),
   ],
   "prep_before": ["Boil the pasta water."],
   "steps": [
    {"text": "In the meatball pan cook onion and garlic in olive oil until soft. Add passata, sugar, oregano, salt and pepper. Simmer 5 minutes.", "heat": "Medium-low", "time": "10 min", "done": "Sauce slightly thick"},
    {"text": "Return the meatballs, cover, simmer.", "heat": "Low", "time": "20 min", "done": "Meatballs 75 °C inside, no pink; sauce thick"},
    {"text": "Cook the spaghetti in the salted boiling water as the packet says (usually 9 to 11 min). Keep 100 ml pasta water; drain.", "heat": "High", "time": "10 min", "done": "Tender with a slight bite"},
    {"text": "Toss the spaghetti with half the sauce and a splash of pasta water. Serve with meatballs and remaining sauce on top, parmesan and herbs.", "heat": "", "time": "2 min", "done": ""},
   ]},
 ],
 "timeline": ["0:00  Shape meatballs. Boil water.", "0:10  Brown meatballs; make sauce.", "0:25  Meatballs simmer 20 min; spaghetti in at 0:33.", "0:45  Serve."],
 "presentation": ["Spaghetti twirled on the plate, meatballs and sauce on top, parmesan and parsley. Green Mix Salad (S5) beside. Mohamed's plate: sauce and chicken strips, no meatballs."],
 "mistakes": ["Over-mixed meat makes hard meatballs; mix lightly.", "Rinsing the pasta washes off the starch that holds the sauce; do not rinse.", "Serving meatballs to Mohamed by mistake: keep his portion separate."],
 "serving": ["Serve hot for 2 (one portion with meatballs, one as noted)."],
 "storage": ["Sauce with meatballs keeps 3 days refrigerated; freezes 1 month. Cook pasta fresh each time."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "سباغيتي بكرات اللحم",
   "url": "https://kitchen.sayidaty.net/node/35902/سباغيتي-بكرات-اللحم/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/91/9193bc47d274df863a4cfa7088fee335_w360_h360.jpg",
   "status": "Verified: page opened and read (3 servings). Adapted: scaled to 2 adults; sauce ingredients listed explicitly (the source names them only in the steps)."},
},
# ---------------------------------------------------------------- M21
{
 "id": "M21", "name": "Mashed Potato with Grilled Chicken", "arabic": "بطاطس مهروسة مع صدور دجاج مشوية",
 "cuisine": "International / Everyday", "category": "Main",
 "times": {"prep": "15 min (plus 1 to 4 h marinating)", "cook": "40 min", "total": "55 min plus marinating"},
 "difficulty": "Easy",
 "equipment": ["Pot (2.5 L) for potatoes", "Potato masher", "Griddle pan or oven tray", "Separate raw-chicken board and knife", "Meat thermometer"],
 "meat": {"animal": "Chicken", "type": "Boneless", "cut": "Breast fillets, flattened to 1.5 cm", "skin": "Skinless",
          "weight": "400 g (2 fillets)", "prep": RAW_CHICKEN_PREP + " Marinate 1 to 4 hours.", "method": "Grilled on a griddle pan (or oven 180 °C, 25 min)",
          "note": "Cut follows the original (chicken breast)."},
 "spice_note": "No chili. Garlic, lemon, yogurt, onion powder, black pepper 1/4 tsp; nutmeg in the mash.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Grilled chicken breast",
   "ingredients": [
    ("Chicken breast fillets", "400 g", "see meat table"),
    ("Plain yogurt", "4 tbsp", ""),
    ("Lemon juice", "2 tbsp", ""),
    ("Garlic, crushed", "2 cloves", ""),
    ("Olive oil", "2 tbsp", ""),
    ("Onion powder", "1/2 tsp", ""),
    ("Salt", "3/4 tsp", ""),
    ("Black pepper", "1/4 tsp", ""),
    ("Dried parsley or thyme", "1/2 tsp", ""),
   ],
   "prep_before": ["Whisk the marinade; coat the flattened fillets; refrigerate 1 to 4 hours."],
   "steps": [
    {"text": "Heat the griddle until hot. Scrape excess marinade off the chicken (yogurt burns). Grill without moving, then turn.", "heat": "Medium-high", "time": "5 to 6 min per side", "done": "Internal 74 °C; golden grill marks; juices clear"},
    {"text": "Rest 5 minutes; slice thickly.", "heat": "Off", "time": "5 min", "done": ""},
   ]},
  {"title": "Part 2: Mashed potato",
   "ingredients": [
    ("Potatoes (floury type), peeled, 3 cm chunks", "600 g (4 medium)", ""),
    ("Salt for the water", "1 tsp", ""),
    ("Butter", "40 g (3 tbsp)", ""),
    ("Milk, warm", "100 ml", "more for a softer mash"),
    ("Salt", "1/4 tsp", ""),
    ("Black pepper", "1 pinch", ""),
    ("Nutmeg, grated", "1 pinch", "optional"),
   ],
   "prep_before": ["Peel and cut the potatoes evenly; warm the milk."],
   "steps": [
    {"text": "Cover the potatoes with cold salted water, bring to a boil, cook until very soft.", "heat": "Medium", "time": "20 min", "done": "A knife slides through with no resistance"},
    {"text": "Drain well, return to the hot pot 1 minute to dry, then mash until smooth.", "heat": "Low", "time": "3 min", "done": "No lumps"},
    {"text": "Beat in the butter, then the warm milk a little at a time. Season with salt, pepper and nutmeg.", "heat": "Off", "time": "2 min", "done": "Creamy, holds a soft peak"},
   ]},
 ],
 "timeline": ["-2:00 Marinate the chicken.", "0:00  Potatoes on.", "0:15  Grill the chicken.", "0:25  Mash the potatoes; rest and slice the chicken.", "0:35  Serve."],
 "presentation": ["A mound of mash, sliced chicken leaning on it, a spoon of the pan juices, and Corn Salad (S3) or Green Mix (S5) beside."],
 "mistakes": ["Cold milk makes gluey mash; warm it.", "Mashing in a blender turns potatoes to glue; use a masher.", "Thick uneven chicken: flatten to 1.5 cm so it cooks through without drying."],
 "serving": ["Serve hot for 2."],
 "storage": ["Mash keeps 2 days refrigerated; reheat with a splash of milk. Chicken 2 days; reheat until steaming hot."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipes)", "recipe": "البطاطس المهروسة بالزبدة والحليب + تتبيلة صدور دجاج مشوية بالفرن",
   "url": "https://kitchen.sayidaty.net/node/37035/البطاطس-المهروسة-بالزبدة-والحليب/المقبلات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/ae/ae7d3fae88106c5128f783c8e0e800d0_w360_h360.jpg",
   "status": "Verified: both pages opened and read (mash node/37035; chicken marinade node/35369). Adapted: scaled to 2 adults; griddle method instead of oven."},
},
# ---------------------------------------------------------------- M22
{
 "id": "M22", "name": "Chicken Spinach with White Rice", "arabic": "دجاج بالسبانخ مع رز أبيض",
 "cuisine": "Levantine / Egyptian", "category": "Main",
 "times": {"prep": "20 min", "cook": "40 min", "total": "1 h"},
 "difficulty": "Easy",
 "equipment": ["Wide pan with lid", "Medium pot for rice", "Separate raw-chicken board and knife", "Meat thermometer"],
 "meat": {"animal": "Chicken", "type": "Boneless", "cut": "Breast fillet, 2.5 cm cubes (or boneless thigh)", "skin": "Skinless",
          "weight": "400 g", "prep": RAW_CHICKEN_PREP, "method": "Seared, then simmered with spinach in a light tomato-garlic sauce",
          "note": "The Shamlola original uses breast fillets (stuffed). Cubed breast in a spinach stew is the household style of this dish; cut is our suggestion."},
 "spice_note": "No chili. Garlic, ground coriander, black pepper 1/4 tsp, lemon.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Chicken with spinach",
   "ingredients": [
    ("Chicken breast, cubed", "400 g", "see meat table"),
    ("Spinach, fresh, washed and chopped", "400 g", "or 300 g frozen, thawed and squeezed"),
    ("Olive oil", "3 tbsp", ""),
    ("Onion, chopped", "1", ""),
    ("Garlic, crushed", "4 cloves", ""),
    ("Tomato passata", "150 ml", ""),
    ("Hot water or chicken stock", "200 ml", ""),
    ("Coriander, ground", "1 tsp", ""),
    ("Salt", "1 tsp", ""),
    ("Black pepper", "1/4 tsp", ""),
    ("Lemon juice", "2 tbsp", ""),
    ("Pine nuts, toasted (optional)", "1 tbsp", ""),
   ],
   "prep_before": ["Wash the spinach in 3 changes of water (it hides sand); chop. Cube and dry the chicken."],
   "steps": [
    {"text": "Heat 2 tbsp oil; sear the chicken cubes with 1/2 tsp salt and the pepper until golden. Remove.", "heat": "Medium-high", "time": "5 min", "done": "Golden outside"},
    {"text": "Add 1 tbsp oil; cook onion until soft, garlic and ground coriander 1 minute.", "heat": "Medium", "time": "6 min", "done": "Fragrant"},
    {"text": "Add passata and water; simmer 3 minutes. Add the spinach in handfuls, stirring until wilted.", "heat": "Medium", "time": "5 min", "done": "Spinach wilted and dark green"},
    {"text": "Return the chicken with the remaining salt. Cover and simmer.", "heat": "Low", "time": "15 min", "done": "Chicken 74 °C, white through; sauce thick"},
    {"text": "Off the heat add lemon juice; top with pine nuts.", "heat": "Off", "time": "", "done": ""},
   ]},
  white_rice_part(2),
 ],
 "timeline": ["0:00  Wash spinach; cube chicken. Soak rice.", "0:15  Start the rice.", "0:20  Sear chicken; onion; spinach; simmer.", "0:45  Serve."],
 "presentation": ["Rice on the plate, spinach-chicken beside it, lemon wedge, pine nuts."],
 "mistakes": ["Sandy spinach: wash it three times.", "Watery sauce: squeeze frozen spinach well; simmer uncovered at the end.", "Over-cooked chicken cubes go dry: 15 minutes in the sauce is enough."],
 "serving": ["Serve hot for 2 with rice and lemon."],
 "storage": ["Keeps 2 days refrigerated; reheat until steaming. Freezes 1 month."],
 "source": {"site": SHAM, "chef": "Shamlola (site recipe)", "recipe": "طريقة عمل دجاج بالسبانخ في الفرن",
   "url": "https://shamlola.com/recipes/طريقة-عمل-دجاج-بالسبانخ-في-الفرن",
   "image": "https://shamlola.s3.amazonaws.com/Shamlola_Images/8/src/13f4f7c5f15a772b28903b8d2c84aae783ec64ae.jpg",
   "status": "Verified: page opened and read (also read طاجن الدجاج بالسبانخ). Adapted: turned from stuffed baked breasts into a stove-top chicken and spinach stew for serving with rice; scaled to 2 adults. " + WHITE_RICE_SRC},
},
# ---------------------------------------------------------------- M23
{
 "id": "M23", "name": "Mahdbi Chicken with Rice", "arabic": "دجاج مظبي مع الرز",
 "cuisine": "Gulf / Yemeni", "category": "Main",
 "times": {"prep": "20 min (plus 2 h marinating)", "cook": "1 h 10 min", "total": "1 h 30 min plus marinating"},
 "difficulty": "Medium",
 "equipment": ["Oven with grill, or griddle pan", "Heavy pot with lid (3 L) for rice", "Small heat-proof bowl and 1 piece of natural charcoal (optional smoking step)", "Separate raw-chicken board and knife", "Meat thermometer", "Foil"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Thighs, 4 pieces (or half a chicken flattened)", "skin": "Skin-on",
          "weight": "700 g", "prep": RAW_CHICKEN_PREP + " Marinate 2 hours or overnight.", "method": "Marinated, grilled (oven grill or griddle), optionally smoked with charcoal",
          "note": "Cut follows the Sayidaty charcoal version (chicken thighs)."},
 "spice_note": "No chili. The marinade is yogurt, lemon, garlic, dried coriander, turmeric, cumin, sweet paprika, cinnamon and black pepper 1/4 tsp. Traditional madhbi is often served with a hot sahawiq sauce; it is NOT included.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Madhbi chicken",
   "ingredients": [
    ("Chicken thighs, bone-in", "700 g", "see meat table"),
    ("Plain yogurt", "4 tbsp", ""),
    ("Olive oil", "2 tbsp", ""),
    ("Garlic, crushed", "3 cloves", ""),
    ("Lemon juice", "2 tbsp", ""),
    ("Coriander, ground", "1 tsp", ""),
    ("Cumin, ground", "1/2 tsp", ""),
    ("Turmeric", "1/2 tsp", ""),
    ("Sweet paprika", "1 tsp", ""),
    ("Cinnamon, ground", "1/4 tsp", ""),
    ("Salt", "1 tsp", ""),
    ("Black pepper", "1/4 tsp", ""),
    ("Charcoal piece and 1 tsp oil (optional smoke)", "1", ""),
   ],
   "prep_before": ["Mix the marinade; coat the chicken; refrigerate 2 hours or overnight."],
   "steps": [
    {"text": "Heat the oven grill (or a griddle). Put the chicken skin-up on a foil-lined tray on the middle shelf.", "heat": "Oven grill, 200 °C", "time": "", "done": ""},
    {"text": "Grill, turning once, until charred at the edges and cooked through.", "heat": "Grill 200 °C", "time": "35 to 40 min", "done": "Internal 75 °C at the bone; juices clear; skin golden with dark edges"},
    {"text": "Optional smoke: put the chicken in a pot, set a small heat-proof bowl in the middle, light the charcoal piece with tongs until glowing, place it in the bowl, drop 1 tsp oil on it and cover the pot immediately for 5 minutes. (Do this with the kitchen window open; keep hair and towels away from the flame.)", "heat": "Off", "time": "5 min", "done": "Smoky aroma"},
   ]},
  {"title": "Part 2: Madhbi rice",
   "ingredients": [
    ("Basmati rice", "300 g (1 1/2 cups)", "washed, soaked 30 min, drained"),
    ("Vegetable oil", "1 tbsp", ""), ("Ghee", "1 tbsp", ""),
    ("Bay leaf", "1", ""), ("Cardamom pods", "3", ""), ("Whole cloves", "3", ""), ("Dried lime (loomi), pierced", "1", ""),
    ("Hot water or chicken stock", "450 ml", ""),
    ("Salt", "3/4 tsp", ""),
    ("Saffron threads soaked in 2 tbsp hot water", "1 pinch", ""),
   ],
   "prep_before": ["Soak the rice and the saffron."],
   "steps": [
    {"text": "Heat oil and ghee in the pot; sizzle bay, cardamom, cloves and loomi 30 seconds.", "heat": "Medium", "time": "1 min", "done": "Fragrant"},
    {"text": "Add the rice; stir gently to coat. Add stock and salt; boil until craters appear.", "heat": "High", "time": "6 min", "done": "Liquid level with rice"},
    {"text": "Drizzle the saffron water, cover tightly, steam on the lowest heat.", "heat": "Very low", "time": "20 min", "done": "Tender"},
    {"text": "Rest 10 minutes; fluff.", "heat": "Off", "time": "10 min", "done": ""},
   ]},
 ],
 "timeline": ["-2:00 Marinate. Soak rice 30 min before cooking.", "0:00  Chicken under the grill (40 min).", "0:10  Start the rice.", "0:40  Rice rests; chicken done; optional smoke 5 min.", "0:50  Serve."],
 "presentation": ["Saffron-streaked rice on a platter, chicken on top, lemon wedges, Jer-Jer Salad (S9) and mild daqqus (M6 Part 3). No hot sauce."],
 "mistakes": ["Grilling too close to the element burns the yogurt marinade before the inside cooks; use the middle shelf.", "Skipping the resting of the rice gives wet grains.", "Charcoal step without ventilation: open the window."],
 "serving": ["Serve hot for 2."],
 "storage": ["Chicken 2 days refrigerated, reheat in the oven to 75 °C inside. Rice 2 days, reheat with a splash of water until steaming."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "المظبي على الفحم بالطريقة الأصلية",
   "url": "https://kitchen.sayidaty.net/node/32135/المظبي-على-الفحم-بالطريقة-الأصلية/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/d8/d83be496acc69f92bf8b4b367205cb58_w360_h360.jpg",
   "status": "Verified: page opened and read (marinade list given in the steps; also read node/38000 for the rice and charcoal-smoke method). Adapted: oven grill instead of an outdoor charcoal grill; scaled to 2 adults."},
},
]
