# -*- coding: utf-8 -*-
# HOME COOKBOOK, Mains M1..M8. Servings: 2 adults. Spice level 0/5.
SAY = "Sayidaty Kitchen (kitchen.sayidaty.net)"
MANAL = "Manal Alalem (manalonline.com)"
SHAM = "Shamlola (shamlola.com)"

RAW_CHICKEN_PREP = "Use the separate raw-meat board and knife. Do NOT wash the chicken under the tap (it spreads bacteria); pat it dry with kitchen paper instead. Wash hands, board and knife with hot soapy water right after."
RAW_LAMB_PREP = "Use the separate raw-meat board and knife. Pat the lamb dry; trim thick fat. Wash hands, board and knife with hot soapy water right after."

MAINS1 = [
# ---------------------------------------------------------------- M1
{
 "id": "M1", "name": "Chicken Biryani", "arabic": "برياني الدجاج",
 "cuisine": "Gulf / Indian-Gulf", "category": "Main",
 "times": {"prep": "30 min (plus 30 min soaking rice)", "cook": "1 h 20 min", "total": "2 h"},
 "difficulty": "Medium",
 "equipment": ["Large heavy pot with tight lid (4 L)", "Wide deep frying pan", "Sieve and bowl for soaking rice", "Separate raw-chicken board and knife", "Meat thermometer (recommended)", "Small cup (saffron)"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Thighs and drumsticks (4 pieces: 2 thighs, 2 drumsticks)", "skin": "Skin removed (as the original cuts a whole chicken into 8; skin-off reduces fat in the pot)",
          "weight": "600 g", "prep": RAW_CHICKEN_PREP, "method": "Braised in the spiced yogurt-tomato sauce, then steamed on top of the rice",
          "note": "The original uses a whole chicken cut into 8 pieces. For 2 adults we use 4 pieces of bone-in thigh and drumstick, which stay juicy during the long cooking."},
 "spice_note": "Manal Alalem's original uses 1/2 tsp crushed chili and 2 chopped green hot peppers. BOTH ARE REMOVED. Cardamom, cumin, turmeric, cinnamon, bay and saffron give the full biryani aroma. Black pepper is reduced to 1/4 tsp. The dish keeps its character; it is fragrant, not hot.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Chicken in spiced sauce",
   "ingredients": [
    ("Chicken thighs and drumsticks, skin removed", "600 g", "see meat table"),
    ("Ghee or butter", "2 tbsp", ""),
    ("Cardamom, ground", "1/2 tsp", ""),
    ("Black pepper, ground", "1/4 tsp", ""),
    ("Turmeric", "1/2 tsp", ""),
    ("Cumin, ground", "1/2 tsp", ""),
    ("Salt", "1 tsp", ""),
    ("Onions, finely chopped", "2 medium (240 g)", ""),
    ("Garlic, crushed", "3 cloves", ""),
    ("Fresh ginger, finely grated", "1 tsp", ""),
    ("Tomatoes, peeled and chopped", "2 medium", "or 200 ml passata"),
    ("Plain yogurt", "4 tbsp", ""),
    ("Bay leaf", "1", ""),
    ("Cinnamon stick", "1 small piece (3 cm)", ""),
    ("Fresh mint, chopped", "2 tbsp", ""),
    ("Fresh coriander, chopped", "3 tbsp", ""),
    ("Water", "150 ml", ""),
   ],
   "prep_before": ["Dry and season the chicken (see meat table).", "Chop onions, garlic, ginger, tomatoes and herbs; measure the spices into one small bowl."],
   "steps": [
    {"text": "Melt the ghee in the wide pan. Add cardamom, black pepper, turmeric, cumin and salt and stir for 20 seconds until fragrant.", "heat": "Medium", "time": "1 min", "done": "Spices smell toasted, not burnt"},
    {"text": "Add the onions, garlic and ginger. Cook, stirring often, until deep golden.", "heat": "Medium", "time": "10 min", "done": "Onions soft and golden brown"},
    {"text": "Add the chicken pieces and turn them in the onion mixture until they lose their pink color on the outside.", "heat": "Medium-high", "time": "5 min", "done": "No raw-looking surfaces"},
    {"text": "Add tomatoes, yogurt, bay leaf, cinnamon, mint and coriander. Stir, cover, and cook 10 minutes. Then add the water, cover again and simmer until the chicken is tender and the sauce is thick.", "heat": "Low", "time": "35 to 40 min", "done": "Internal 74 °C; meat pulls from the bone easily; sauce thick, oil visible at the edges"},
   ]},
  {"title": "Part 2: Saffron rice",
   "ingredients": [
    ("Basmati rice", "300 g (1 1/2 cups)", "washed until the water runs clear, soaked 30 min, drained"),
    ("Rose water", "2 tbsp", ""),
    ("Saffron threads", "1/4 tsp", ""),
    ("Ghee", "2 tbsp", ""),
    ("Blanched almonds", "2 tbsp", ""),
    ("Raisins", "2 tbsp", ""),
    ("Onion, finely chopped", "1 small", ""),
    ("Whole cardamom pods", "3", ""),
    ("Whole cloves", "3", ""),
    ("Cinnamon stick", "1 small piece", ""),
    ("Salt", "1 tsp", ""),
    ("Hot water", "500 ml (2 cups)", ""),
   ],
   "prep_before": ["Soak the saffron in the rose water in the small cup (15 min).", "Wash and soak the rice."],
   "steps": [
    {"text": "Melt the ghee in the large pot. Fry the almonds until pale gold, lift out with a slotted spoon. Fry the raisins just until they puff (30 seconds), lift out. Keep both for garnish.", "heat": "Medium", "time": "3 min", "done": "Almonds light gold; raisins plump"},
    {"text": "In the same ghee cook the onion with the cardamom pods, cloves and cinnamon until the onion is golden.", "heat": "Medium", "time": "5 min", "done": "Golden, aromatic"},
    {"text": "Add the drained rice and stir gently 1 minute to coat. Add the hot water and salt. Boil uncovered until the water is level with the rice and holes appear on the surface.", "heat": "High", "time": "6 to 8 min", "done": "Water absorbed to the rice line, small craters on top"},
    {"text": "Lay the chicken pieces on the rice and spoon the sauce over. Drizzle the saffron rose water. Cover with a clean towel then the lid (the towel traps steam).", "heat": "Very low", "time": "30 min", "done": "Rice grains long, separate and fully soft; no bite in the center"},
    {"text": "Turn off the heat and rest, covered, 10 minutes.", "heat": "Off", "time": "10 min", "done": ""},
   ]},
 ],
 "timeline": [
  "0:00  Wash and soak the rice; soak saffron in rose water.",
  "0:05  Start Part 1: spices, onions, chicken, sauce.",
  "0:25  Chicken simmering (40 min). Fry almonds and raisins, cook the rice onion (Part 2 steps 1 and 2).",
  "0:55  Rice in, boil until holes appear.",
  "1:05  Chicken on rice, saffron, cover, very low 30 min.",
  "1:35  Rest 10 min. Serve at 1:45.",
 ],
 "presentation": ["Lift the chicken off, fluff the rice with a fork mixing the yellow saffron streaks through the white. Pile on a wide platter, chicken on top, almonds and raisins scattered over. Serve with Jer-Jer Salad (S9) and a bowl of yogurt."],
 "mistakes": ["Rice mushy: it boiled too long before covering, or too much water. Stop when the water reaches the rice line.", "Rice hard on top: lid not tight; use the towel trick and the lowest flame.", "Chicken dry: it was cooked on high. The sauce stage must be a gentle simmer.", "Burnt spices in step 1: 20 seconds is enough."],
 "serving": ["Serve hot on a platter for 2 with yogurt, Jer-Jer Salad (S9) or Green Mix (S5)."],
 "storage": ["Cool within 1 hour, refrigerate up to 2 days. Reheat covered with 2 tbsp water in a pot on low, or microwave until steaming (75 °C). Reheat only once."],
 "source": {"site": MANAL, "chef": "Manal Alalem", "recipe": "برياني الدجاج",
   "url": "https://www.manalonline.com/برياني-الدجاج/",
   "image": "https://www.manalonline.com/images/crops/g16x9/برياني-الدجاج-v2.jpg",
   "status": "Verified: page opened and read (Arabic YouTube video embedded). Adapted: scaled from 1 kg chicken / 3 cups rice to 600 g / 1.5 cups (2 adults); crushed chili and green hot peppers removed."},
},
# ---------------------------------------------------------------- M2
{
 "id": "M2", "name": "Lamb Biryani", "arabic": "برياني اللحم",
 "cuisine": "Gulf / Indian-Gulf", "category": "Main",
 "times": {"prep": "30 min (plus 30 min soaking rice)", "cook": "1 h 45 min", "total": "2 h 30 min"},
 "difficulty": "Medium",
 "equipment": ["Large pot (4 L) for boiling the lamb", "Heavy pot with tight lid for the rice", "Wide frying pan", "Sieve", "Separate raw-meat board and knife"],
 "meat": {"animal": "Lamb", "type": "Boneless (original: 'lamb or beef, cut up')", "cut": "Shoulder or leg, 3 cm cubes", "skin": "N/A; trim heavy fat",
          "weight": "500 g", "prep": RAW_LAMB_PREP, "method": "Boiled in aromatic stock until tender, then fried with onion and yogurt, then layered with rice",
          "note": "The original says 'lamb or beef, cut'. Shoulder is our suggestion because it stays moist; leg also works."},
 "spice_note": "Manal Alalem's original has no chili; black pepper is reduced to 1/4 tsp. Whole cardamom, cloves, cinnamon, bay and 'mixed spice' (bahar mushakkal, a non-hot blend) carry the flavor.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Boil the lamb",
   "ingredients": [
    ("Lamb cubes", "500 g", "see meat table"),
    ("Water", "1.5 L", ""),
    ("Onion, quartered", "1 medium", ""),
    ("Cardamom pods", "4", ""),
    ("Bay leaves", "2", ""),
    ("Cinnamon stick", "1 piece", ""),
    ("Whole cloves", "4", ""),
    ("Salt", "1 tbsp", ""),
    ("Black pepper, whole", "4 peppercorns", ""),
   ],
   "prep_before": ["Trim and cube the lamb."],
   "steps": [
    {"text": "Put the lamb in the large pot, cover with the water and bring to a boil. Skim off the grey foam with a spoon.", "heat": "High", "time": "10 min", "done": "No more foam rising"},
    {"text": "Add onion, cardamom, bay, cinnamon, cloves, salt and peppercorns. Lower the heat, cover partly, and simmer until the lamb is tender.", "heat": "Low", "time": "60 to 75 min", "done": "A fork slides in with no resistance"},
    {"text": "Lift out the meat. Strain the stock and keep 600 ml (3 cups) for the rice.", "heat": "Off", "time": "3 min", "done": ""},
   ]},
  {"title": "Part 2: Lamb masala and rice",
   "ingredients": [
    ("Basmati rice", "300 g (1 1/2 cups)", "washed, soaked 30 min in warm salted water, drained"),
    ("Saffron threads", "1/4 tsp", "soaked in 2 tbsp rose water"),
    ("Ghee or corn oil", "3 tbsp", ""),
    ("Onions, chopped", "2 medium", ""),
    ("Garlic, crushed", "2 cloves", ""),
    ("Fresh ginger, grated", "1 tsp", ""),
    ("Mixed spice (bahar mushakkal, non-hot)", "1 tbsp", "check the label: no chili"),
    ("Plain yogurt", "125 ml (1/2 cup)", ""),
    ("Fresh mint, chopped", "3 tbsp", ""),
    ("Fresh coriander, chopped", "3 tbsp", ""),
    ("Lamb stock (from Part 1)", "600 ml", ""),
    ("Hard-boiled eggs, halved (garnish)", "2", "see B3"),
   ],
   "prep_before": ["Wash and soak the rice. Soak the saffron. Boil the eggs."],
   "steps": [
    {"text": "Heat the ghee in the wide pan. Cook the onions, garlic and ginger until dark golden.", "heat": "Medium", "time": "10 min", "done": "Deep golden, sweet smell"},
    {"text": "Add the boiled lamb and the mixed spice. Stir until the meat browns lightly.", "heat": "Medium-high", "time": "5 min", "done": "Meat edges golden"},
    {"text": "Add mint, yogurt and the saffron rose water. Cook until the sauce is thick and clings to the meat.", "heat": "Medium", "time": "5 min", "done": "Thick sauce, little liquid left"},
    {"text": "Bring the 600 ml stock to a boil in the rice pot. Add the drained rice and cook until the stock is absorbed and the rice is almost tender.", "heat": "High then Medium", "time": "8 to 10 min", "done": "Grain soft outside with a slight bite inside"},
    {"text": "Spoon half the rice into the lamb pan and fold gently. Spread the rest of the rice on top without stirring. Cover tightly and steam.", "heat": "Very low", "time": "15 min", "done": "Rice fully tender, steam fragrant"},
   ]},
 ],
 "timeline": [
  "0:00  Lamb into water; soak rice; soak saffron; boil eggs.",
  "0:15  Lamb simmering (about 70 min). Chop onions and herbs.",
  "1:20  Lamb tender; strain stock. Start the onion masala.",
  "1:40  Lamb in masala; rice into boiling stock.",
  "1:55  Layer, cover, steam 15 min.",
  "2:10  Rest 5 min, serve with eggs and coriander.",
 ],
 "presentation": ["Mound on a platter so the white and spiced layers show. Halved boiled eggs on top, fresh coriander leaves scattered. Serve with yogurt and Jer-Jer Salad (S9)."],
 "mistakes": ["Tough lamb: not simmered long enough; test with a fork before moving on.", "Rice overcooked in the stock: stop at 'almost tender', it finishes while steaming.", "Stirring the top rice layer makes it gummy; leave it."],
 "serving": ["Serve hot for 2 with yogurt and salad."],
 "storage": ["Refrigerate up to 2 days. Reheat covered with a splash of water until steaming hot. Reheat once only."],
 "source": {"site": MANAL, "chef": "Manal Alalem", "recipe": "برياني اللحم",
   "url": "https://www.manalonline.com/برياني-اللحم/",
   "image": "https://www.manalonline.com/images/crops/g16x9/برياني-اللحم-v2.jpg",
   "status": "Verified: page opened and read. Adapted: scaled from 1 kg lamb / 3 cups rice to 500 g / 1.5 cups (2 adults); black pepper reduced."},
},
# ---------------------------------------------------------------- M3
{
 "id": "M3", "name": "Chicken Maqluba", "arabic": "مقلوبة الدجاج",
 "cuisine": "Levantine (Palestinian / Jordanian)", "category": "Main",
 "times": {"prep": "30 min", "cook": "1 h 30 min", "total": "2 h"},
 "difficulty": "Medium",
 "equipment": ["Medium pot (3 L) for boiling chicken", "Heavy pot with lid (3 L, straight sides) for the maqluba", "Deep frying pan for the eggplant", "Large flat serving plate (wider than the pot)", "Separate raw-chicken board and knife", "Kitchen paper"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Thighs (2) and drumsticks (2)", "skin": "Skin-on for boiling (removed before layering if preferred)",
          "weight": "600 g", "prep": RAW_CHICKEN_PREP, "method": "Boiled in aromatic stock, then layered under the rice and steamed",
          "note": "The original uses 1 kg boiled chicken, unspecified cut. Thigh and drumstick are our suggestion; they do not dry out."},
 "spice_note": "No chili in Manal Alalem's original; black pepper reduced to 1/4 tsp. Mixed spice, turmeric, cinnamon and cardamom give the typical flavor.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Boil the chicken and make the stock",
   "ingredients": [
    ("Chicken thighs and drumsticks", "600 g", "see meat table"),
    ("Water", "1.2 L", ""),
    ("Onion, quartered", "1", ""),
    ("Cardamom pods", "3", ""),
    ("Bay leaf", "1", ""),
    ("Cinnamon stick", "1 small piece", ""),
    ("Salt", "1 tsp", ""),
    ("Turmeric", "1/4 tsp", ""),
   ],
   "prep_before": ["Dry and trim the chicken (raw-meat board)."],
   "steps": [
    {"text": "Put chicken, water, onion and spices in the medium pot. Bring to a boil and skim the foam.", "heat": "High", "time": "10 min", "done": "Clear stock, no foam"},
    {"text": "Simmer, partly covered, until the chicken is cooked.", "heat": "Low", "time": "35 min", "done": "Internal 74 °C; juices clear"},
    {"text": "Lift the chicken out. Strain the stock and measure 500 ml (2 cups) for the rice; keep it hot.", "heat": "Off", "time": "3 min", "done": ""},
   ]},
  {"title": "Part 2: Fry the eggplant",
   "ingredients": [
    ("Eggplant, 1 cm thick rounds", "1 large (350 g)", ""),
    ("Salt", "1 tsp", "for sweating the eggplant"),
    ("Corn oil for frying", "200 ml", ""),
   ],
   "prep_before": ["Slice the eggplant, sprinkle with salt, leave 15 minutes, then wipe the slices dry with kitchen paper (do not rinse, as the source says)."],
   "steps": [
    {"text": "Heat the oil in the deep pan. Fry the eggplant slices in batches until golden on both sides. Drain on kitchen paper.", "heat": "Medium-high", "time": "3 min per side", "done": "Golden brown, soft"},
   ]},
  {"title": "Part 3: Layer and cook the maqluba",
   "ingredients": [
    ("Short-grain (Egyptian) rice", "300 g (1 1/2 cups)", "washed, soaked in warm water 15 min, drained"),
    ("Hot chicken stock (Part 1)", "500 ml", ""),
    ("Salt", "1 tsp", ""),
    ("Mixed spice (non-hot)", "1/2 tsp", ""),
    ("Turmeric", "1/4 tsp", ""),
    ("Cinnamon, ground", "1/4 tsp", ""),
    ("Cardamom, ground", "1 pinch", ""),
    ("Black pepper, ground", "1/4 tsp", ""),
    ("Corn oil", "1 tbsp", ""),
    ("Pine nuts or slivered almonds, fried golden", "2 tbsp", "garnish"),
   ],
   "prep_before": ["Stir salt and all the spices into the hot stock.", "Have the pot, chicken, eggplant and rice next to each other."],
   "steps": [
    {"text": "Spread 3 tbsp of rice over the bottom of the heavy pot. Lay the eggplant slices over it in one neat layer (this will be the top when flipped).", "heat": "", "time": "2 min", "done": ""},
    {"text": "Arrange the chicken pieces on the eggplant. Cover with the rest of the rice and press lightly flat.", "heat": "", "time": "2 min", "done": ""},
    {"text": "Pour the seasoned stock slowly down the side of the pot so the layers are not disturbed. Add 1 tbsp oil.", "heat": "", "time": "1 min", "done": "Stock just covers the rice"},
    {"text": "Bring to a boil, then cover tightly and cook on the lowest heat until the liquid is absorbed and the rice is tender.", "heat": "High 3 min, then Very low", "time": "30 min", "done": "No liquid when you tilt the pot; rice soft"},
    {"text": "Rest off the heat, covered, 10 minutes. Place the serving plate upside down over the pot, hold both firmly with towels, and flip in one confident movement. Wait 2 minutes, then lift the pot straight up.", "heat": "Off", "time": "12 min", "done": "The maqluba stands as a cake with eggplant on top"},
   ]},
 ],
 "timeline": [
  "0:00  Chicken into the pot to boil. Salt the eggplant. Soak the rice.",
  "0:20  Fry the eggplant while the chicken simmers.",
  "0:45  Chicken done; strain and season the stock.",
  "0:50  Layer the pot, add stock, boil, then very low 30 min.",
  "1:25  Rest 10 min, flip, garnish, serve at 1:40.",
 ],
 "presentation": ["Scatter fried pine nuts over the top. Serve with a bowl of plain yogurt or yogurt-cucumber, and Green Mix Salad (S5) or Fattoush (S1)."],
 "mistakes": ["Layers collapse when flipped: not enough resting time, or too much liquid. Rest 10 minutes and tilt-check for liquid first.", "Eggplant soaks up oil: the oil was not hot enough; sweating with salt also helps.", "Rice burnt at the bottom: heat was too high; use the lowest flame (a heat diffuser helps)."],
 "serving": ["Serve hot for 2 with yogurt and salad."],
 "storage": ["Refrigerate up to 2 days. Reheat portions covered with a splash of water until steaming. Reheat once only."],
 "source": {"site": MANAL, "chef": "Manal Alalem", "recipe": "مقلوبة الدجاج الباذنجان",
   "url": "https://www.manalonline.com/مقلوبة-الدجاج-الباذنجان/",
   "image": "https://www.manalonline.com/images/crops/g16x9/مقلوبة-الدجاج-الباذنجان-v2.jpg",
   "status": "Verified: page opened and read. Adapted: scaled from 1 kg chicken / 2.5 cups rice to 600 g / 1.5 cups; chicken-boiling method written out from the carrot maqluba page. Note: Samira Basharat (Sayidaty chef 4243) also has an eggplant maqluba (node/845); the Manal page was chosen because it includes the full chicken method."},
},
# ---------------------------------------------------------------- M4
{
 "id": "M4", "name": "Lamb Maqluba", "arabic": "مقلوبة اللحم",
 "cuisine": "Levantine (Palestinian / Jordanian)", "category": "Main",
 "times": {"prep": "30 min", "cook": "2 h", "total": "2 h 30 min"},
 "difficulty": "Medium",
 "equipment": ["Heavy pot with lid (3 L)", "Deep frying pan", "Large flat serving plate", "Separate raw-meat board and knife", "Kitchen paper"],
 "meat": {"animal": "Lamb", "type": "Bone-in (as in the original: 'lamb with bone')", "cut": "Shoulder or neck pieces on the bone, 4 to 5 cm", "skin": "N/A; trim heavy fat",
          "weight": "600 g", "prep": RAW_LAMB_PREP, "method": "Browned with spices, simmered until tender in its own stock, then layered under vegetables and rice",
          "note": "Cut follows the original (bone-in lamb); shoulder is the suggested part."},
 "spice_note": "No chili in this Manal Alalem version (her second lamb maqluba adds green hot peppers; that version is not used). Cardamom, cinnamon and sweet mixed spice (bahar helou) give the flavor. Black pepper 1/4 tsp.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Cook the lamb",
   "ingredients": [
    ("Lamb on the bone", "600 g", "see meat table"),
    ("Corn oil", "2 tbsp", ""),
    ("Cardamom, ground", "1/2 tsp", ""),
    ("Black pepper, ground", "1/4 tsp", ""),
    ("Salt", "1 1/2 tsp", ""),
    ("Sweet mixed spice (bahar helou)", "1/2 tsp", ""),
    ("Cinnamon, ground", "1 tsp", ""),
    ("Water", "1 L", ""),
   ],
   "prep_before": ["Dry the lamb; measure the spices."],
   "steps": [
    {"text": "Heat the oil in the heavy pot. Add the lamb and all the spices and turn the pieces until browned on all sides.", "heat": "Medium-high", "time": "12 to 15 min", "done": "Deep brown crust, spices fragrant"},
    {"text": "Add the water, bring to a boil, skim, then cover and simmer until tender.", "heat": "Low", "time": "60 to 75 min", "done": "Meat soft, pulling from the bone"},
    {"text": "Lift the lamb out. Strain and keep 500 ml (2 cups) of the stock, hot. Wipe the pot.", "heat": "Off", "time": "3 min", "done": ""},
   ]},
  {"title": "Part 2: Fry the vegetables",
   "ingredients": [
    ("Cauliflower, large florets", "1/2 small head (250 g)", ""),
    ("Eggplant, thick slices (1.5 cm)", "1 medium (300 g)", "salted 15 min and wiped dry"),
    ("Corn oil for frying", "200 ml", ""),
   ],
   "prep_before": ["Cut the vegetables; salt and dry the eggplant."],
   "steps": [
    {"text": "Fry the cauliflower florets until golden; drain on paper. Then fry the eggplant slices until golden on both sides; drain.", "heat": "Medium-high", "time": "6 min each", "done": "Golden brown, tender"},
   ]},
  {"title": "Part 3: Layer and cook",
   "ingredients": [
    ("Basmati rice", "300 g (1 1/2 cups)", "washed, soaked 30 min, drained"),
    ("Corn oil", "2 tbsp", ""),
    ("Onion, chopped", "1 medium", ""),
    ("Tomatoes, thick slices", "2 medium", ""),
    ("Hot lamb stock (Part 1)", "500 ml", ""),
    ("Fried nuts (almonds or pine nuts)", "2 tbsp", "garnish"),
   ],
   "prep_before": ["Have everything ready beside the pot."],
   "steps": [
    {"text": "Heat 2 tbsp oil in the clean heavy pot and cook the onion until dark golden.", "heat": "Medium", "time": "8 min", "done": "Dark golden"},
    {"text": "Layer in this order: tomato slices, eggplant, cauliflower, lamb pieces, then all the rice. Press gently.", "heat": "", "time": "3 min", "done": ""},
    {"text": "Pour the hot stock down the side. Boil until holes appear on the rice surface.", "heat": "High", "time": "5 min", "done": "Craters on the surface, liquid level below the rice"},
    {"text": "Cover tightly and cook on the lowest heat until the rice is tender.", "heat": "Very low", "time": "40 min", "done": "Rice soft, no liquid"},
    {"text": "Rest 10 minutes, then flip onto the serving plate as for Chicken Maqluba (M3).", "heat": "Off", "time": "12 min", "done": "Holds its shape"},
   ]},
 ],
 "timeline": [
  "0:00  Brown the lamb with spices; add water; simmer (75 min). Soak the rice.",
  "0:30  Salt the eggplant; fry cauliflower and eggplant.",
  "1:30  Lamb tender; strain stock. Fry onion in the pot.",
  "1:40  Layer, add stock, boil, then very low 40 min.",
  "2:25  Rest, flip, garnish. Serve at 2:40.",
 ],
 "presentation": ["Scatter fried nuts on top; serve with yogurt and Green Mix Salad (S5)."],
 "mistakes": ["Lamb still tough when layered: it will not soften later. Test with a fork in Part 1.", "Too much stock makes the bottom (future top) soggy: use exactly 500 ml for 300 g basmati.", "Flipping too soon: let it rest 10 minutes."],
 "serving": ["Serve hot for 2 with yogurt and salad."],
 "storage": ["Refrigerate up to 2 days; reheat covered until steaming hot, once only."],
 "source": {"site": MANAL, "chef": "Manal Alalem", "recipe": "مقلوبة اللحم بالزهرة والباذنجان",
   "url": "https://www.manalonline.com/مقلوبة-اللحم-بالزهرة-والباذنجان/",
   "image": "https://www.manalonline.com/images/crops/g16x9/مقلوبة-اللحم-بالزهرة-والباذنجان-v2.webp",
   "status": "Verified: page opened and read. Adapted: scaled from 1 kg lamb / 2 cups rice to 600 g / 1.5 cups (2 adults)."},
},
# ---------------------------------------------------------------- M5
{
 "id": "M5", "name": "Yellow Rice with Nando's Peri-Peri Chicken", "arabic": "أرز أصفر مع دجاج بيري بيري (بدون حار)",
 "cuisine": "Gulf-style yellow rice with Portuguese-African style chicken", "category": "Main",
 "times": {"prep": "20 min (plus 2 h marinating)", "cook": "1 h", "total": "3 h 20 min including marinating"},
 "difficulty": "Medium",
 "equipment": ["Oven and roasting tray with rack (or lined tray)", "Medium pot with lid (2.5 L) for rice", "Blender or jar (marinade)", "Separate raw-chicken board and knife", "Meat thermometer (strongly recommended)", "Brush"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Leg quarters (thigh + drumstick), 2 pieces", "skin": "Skin-on (keeps the meat moist under the glaze)",
          "weight": "700 g (2 quarters)", "prep": RAW_CHICKEN_PREP + " Score the skin twice so the marinade enters.", "method": "Marinated, oven-roasted, basted with the marinade",
          "note": "The Sayidaty source uses 'chicken pieces' for oven roasting; leg quarters are our suggestion for Nando's-style chicken."},
 "spice_note": "IMPORTANT: real Nando's peri-peri sauce is made from African bird's-eye chili and is very hot. This recipe is a NON-SPICY PERI-PERI: it keeps the lemon, garlic, sweet paprika, oregano and vinegar of the style, with ZERO chili. Do not use bottled Nando's sauce (all flavors contain chili, including 'Lemon & Herb' which has a little). Taste is tangy and smoky, not hot. This changes the dish from spicy to mild by design.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Non-spicy peri-peri chicken",
   "ingredients": [
    ("Chicken leg quarters", "2 (700 g)", "see meat table"),
    ("Red bell pepper (sweet), roasted or raw, chopped", "1/2", "gives the red color instead of chili"),
    ("Garlic", "3 cloves", ""),
    ("Lemon juice", "3 tbsp", ""),
    ("Lemon zest", "1 tsp", ""),
    ("White vinegar", "1 tbsp", ""),
    ("Olive oil", "3 tbsp", ""),
    ("Sweet paprika", "2 tsp", "NOT hot paprika"),
    ("Smoked paprika (sweet)", "1/2 tsp", "optional, check label: sweet"),
    ("Dried oregano", "1 tsp", ""),
    ("Salt", "1 tsp", ""),
    ("Black pepper, ground", "1/4 tsp", ""),
    ("Sugar", "1/2 tsp", ""),
   ],
   "prep_before": ["Blend all marinade ingredients (everything except the chicken) until smooth. Keep 3 tbsp aside in a clean bowl for basting at the table.", "Coat the chicken in the rest, cover, refrigerate 2 hours (up to 12 hours)."],
   "steps": [
    {"text": "Heat the oven to 200 °C. Put the chicken skin-side up on the rack over the tray. Spoon over the marinade from the bowl.", "heat": "Oven 200 °C", "time": "2 min", "done": ""},
    {"text": "Roast. After 25 minutes brush with the pan juices.", "heat": "Oven 200 °C", "time": "40 to 45 min", "done": "Internal 75 °C at the thickest part of the thigh (not touching bone); juices run clear; skin deep red-gold"},
    {"text": "Rest 5 minutes. Brush with the reserved clean marinade before serving.", "heat": "Off", "time": "5 min", "done": ""},
   ]},
  {"title": "Part 2: Yellow rice",
   "ingredients": [
    ("Basmati rice", "300 g (1 1/2 cups)", "washed, soaked 20 min, drained"),
    ("Vegetable oil", "2 tbsp", ""),
    ("Bay leaves", "2", ""),
    ("Cinnamon stick", "1 small piece", ""),
    ("Turmeric", "1 tsp", "gives the yellow color"),
    ("Dried lime (loomi), ground", "1/4 tsp", "optional"),
    ("Salt", "1 tsp", ""),
    ("Hot water", "450 ml", ""),
   ],
   "prep_before": ["Wash and soak the rice."],
   "steps": [
    {"text": "Heat the oil in the pot. Add bay, cinnamon and turmeric; stir 20 seconds.", "heat": "Medium", "time": "1 min", "done": "Fragrant, oil yellow"},
    {"text": "Add the drained rice, salt and loomi. Stir gently to coat.", "heat": "Medium", "time": "3 min", "done": "Every grain yellow"},
    {"text": "Add the hot water, bring to a boil, cover and cook on the lowest heat.", "heat": "Very low", "time": "18 min", "done": "Water absorbed, rice tender"},
    {"text": "Rest 5 minutes off the heat, fluff with a fork.", "heat": "Off", "time": "5 min", "done": ""},
   ]},
 ],
 "timeline": [
  "-2:00 Make the marinade, coat the chicken, refrigerate.",
  "0:00  Oven on; chicken in.",
  "0:10  Wash and soak the rice.",
  "0:30  Start the rice (it takes 25 min with resting).",
  "0:45  Chicken done; rest. Fluff rice.",
  "0:55  Serve.",
 ],
 "presentation": ["Yellow rice on the platter, chicken quarters on top, reserved sauce drizzled over, lemon wedges and Corn Salad (S3) or Green Mix (S5) on the side."],
 "mistakes": ["Using bottled Nando's or any 'peri-peri' seasoning: these contain chili. Make the marinade from this list only.", "Basting with the raw marinade at the end: it touched raw chicken. Only the reserved clean portion goes on cooked meat.", "Under-cooked thigh near the bone: check 75 °C with the thermometer.", "Rice stirred while steaming goes sticky; leave the lid on."],
 "serving": ["Serve hot for 2 with lemon wedges and a salad."],
 "storage": ["Refrigerate chicken and rice separately up to 2 days. Reheat chicken in the oven at 180 °C for 15 min (75 °C inside), rice covered with a splash of water."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "الأرز الأصفر مع الدجاج المشوي بالفرن",
   "url": "https://kitchen.sayidaty.net/node/37189/الأرز-الأصفر-مع-الدجاج-المشوي-بالفرن/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/db/db71694f378489a7a21dd3dd6f10cb03_w360_h360.jpg",
   "status": "Verified: page opened and read (method only; the page lists no ingredient quantities). Yellow rice quantities from node/36347 (طريقة عمل الأرز البسمتي الأصفر). The Nando's-style marinade is a non-spicy household adaptation (no Arabic source exists for a chili-free peri-peri)."},
},
# ---------------------------------------------------------------- M6
{
 "id": "M6", "name": "Lamb Kabsa", "arabic": "كبسة اللحم",
 "cuisine": "Gulf (Saudi)", "category": "Main",
 "times": {"prep": "25 min (plus 30 min soaking rice)", "cook": "1 h 50 min", "total": "2 h 45 min"},
 "difficulty": "Medium",
 "equipment": ["Large heavy pot with lid (4 L)", "Frying pan (for browning the lamb)", "Sieve", "Separate raw-meat board and knife", "Grater"],
 "meat": {"animal": "Lamb", "type": "Bone-in", "cut": "Shanks (2 small) or shoulder pieces on the bone", "skin": "N/A; trim heavy fat",
          "weight": "700 g (2 small shanks)", "prep": RAW_LAMB_PREP, "method": "Blanched, then simmered in the spiced tomato stock, browned, and served on rice cooked in the same stock",
          "note": "Cut follows the original (lamb shank, 'mozat')."},
 "spice_note": "Sayidaty's original adds 1/2 tsp hot chili powder and 3 chopped green hot peppers. ALL REMOVED. Whole and ground spices (cardamom, cloves, cinnamon, cumin, coriander, ginger, turmeric, loomi) are kept, so the kabsa flavor is complete; black pepper is reduced to 1/2 tsp.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Lamb in spiced stock",
   "ingredients": [
    ("Lamb shanks", "700 g", "see meat table"),
    ("Ghee", "2 tbsp", ""),
    ("Onions, chopped", "2 medium", ""),
    ("Garlic, chopped", "3 cloves", ""),
    ("Fresh ginger, grated", "1 tbsp", ""),
    ("Tomatoes, chopped", "2 medium", ""),
    ("Tomato paste", "2 tbsp", ""),
    ("Dried limes (loomi), pierced", "2", ""),
    ("Cardamom pods", "4", ""),
    ("Whole cloves", "3", ""),
    ("Cinnamon stick", "1", ""),
    ("Bay leaf", "1", ""),
    ("Cumin, ground", "1 tsp", ""),
    ("Coriander, ground", "1 tsp", ""),
    ("Cinnamon, ground", "1/2 tsp", ""),
    ("Ginger, ground", "1/2 tsp", ""),
    ("Turmeric", "1/2 tsp", ""),
    ("Black pepper, ground", "1/2 tsp", ""),
    ("Salt", "1 1/2 tsp", ""),
    ("Water", "1.2 L", ""),
   ],
   "prep_before": ["Blanch the lamb: cover with cold water, boil 10 minutes, drain and rinse the pot (removes scum).", "Chop vegetables; measure the spices."],
   "steps": [
    {"text": "Heat the ghee in the large pot; cook the onions until soft and golden.", "heat": "Medium", "time": "7 min", "done": "Golden"},
    {"text": "Add garlic, ginger, tomatoes and tomato paste. Cook, stirring.", "heat": "Medium", "time": "5 min", "done": "Tomato darkens and thickens"},
    {"text": "Add all the whole and ground spices and the loomi; stir 2 minutes.", "heat": "Medium", "time": "2 min", "done": "Aromatic"},
    {"text": "Add the blanched lamb, turn to coat, add the water and salt, bring to a boil, then cover and simmer.", "heat": "Low", "time": "90 min", "done": "Meat very tender, falling from the bone"},
    {"text": "Lift out the lamb. Strain the stock; measure 550 ml for the rice (top up with water if short).", "heat": "Off", "time": "3 min", "done": ""},
    {"text": "Brown the lamb pieces in a hot dry frying pan (or under the grill) for color.", "heat": "High", "time": "4 min", "done": "Golden-brown surface"},
   ]},
  {"title": "Part 2: Kabsa rice",
   "ingredients": [
    ("Basmati rice", "300 g (1 1/2 cups)", "washed, soaked 30 min, drained"),
    ("Lamb stock (Part 1)", "550 ml", ""),
    ("Carrot, grated", "1", ""),
    ("Raisins", "2 tbsp", ""),
    ("Fresh coriander, chopped", "2 tbsp", ""),
    ("Toasted almonds and pine nuts", "3 tbsp", "garnish"),
   ],
   "prep_before": ["Grate the carrot; toast the nuts in a dry pan."],
   "steps": [
    {"text": "Bring the stock to a boil in the rinsed large pot. Add the rice, carrot and raisins. Boil until the liquid is level with the rice.", "heat": "High", "time": "6 min", "done": "Craters on the surface"},
    {"text": "Cover tightly and steam on the lowest heat.", "heat": "Very low", "time": "20 min", "done": "Rice tender and separate"},
    {"text": "Rest 10 minutes, fluff with a fork, fold in the coriander.", "heat": "Off", "time": "10 min", "done": ""},
   ]},
  {"title": "Part 3: Daqqus (mild tomato sauce)",
   "ingredients": [
    ("Tomatoes, grated", "2", ""),
    ("Garlic, crushed", "1 clove", ""),
    ("Tomato paste", "1 tsp", ""),
    ("Olive oil", "1 tbsp", ""),
    ("Lemon juice", "1 tbsp", ""),
    ("Salt", "1/4 tsp", ""),
    ("Cumin, ground", "1 pinch", ""),
   ],
   "prep_before": ["Grate the tomatoes."],
   "steps": [
    {"text": "Fry the garlic in the oil 30 seconds, add tomatoes, paste, salt and cumin, simmer until slightly thick. Off the heat add lemon juice. (Traditional daqqus has chili; this one has none.)", "heat": "Medium-low", "time": "8 min", "done": "Thick, spoonable sauce"},
   ]},
 ],
 "timeline": [
  "0:00  Blanch the lamb (10 min). Soak the rice.",
  "0:15  Onion, tomato, spices; lamb in; simmer 90 min.",
  "1:30  Make the daqqus; toast nuts; grate carrot.",
  "1:50  Lamb out, strain stock, brown lamb. Rice into stock.",
  "2:20  Rice rests. Serve at 2:30.",
 ],
 "presentation": ["Rice on a wide platter, lamb on top, nuts and raisins scattered, daqqus in a small bowl, Jer-Jer Salad (S9) on the side."],
 "mistakes": ["Skipping the blanching makes a cloudy, scummy stock.", "Lamb not tender at 90 minutes (older meat): give it 20 more minutes before removing.", "Rice stock measured wrong: 550 ml for 300 g soaked basmati; too much makes it soft."],
 "serving": ["Serve hot for 2 with daqqus, salad and yogurt."],
 "storage": ["Refrigerate up to 2 days; reheat covered with a splash of water until steaming, once only. Daqqus keeps 3 days."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "الكبسة السعودية باللحم الضاني",
   "url": "https://kitchen.sayidaty.net/node/39312/الكبسة-السعودية-باللحم-الضاني/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/4b/4bcfff8d4f09537d99728834786d0a2b_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings). Adapted: scaled to 2 adults; hot chili powder and green hot peppers removed; daqqus from node/11172 made without chili."},
},
# ---------------------------------------------------------------- M7
{
 "id": "M7", "name": "Chicken Kabsa", "arabic": "كبسة الدجاج",
 "cuisine": "Gulf (Saudi)", "category": "Main",
 "times": {"prep": "25 min (plus 30 min soaking rice)", "cook": "1 h 15 min", "total": "2 h 10 min"},
 "difficulty": "Medium",
 "equipment": ["Large heavy pot with lid (4 L)", "Oven tray or frying pan (browning)", "Sieve", "Separate raw-chicken board and knife", "Meat thermometer"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Half chicken cut into 4 pieces (thigh, drumstick, 2 breast-on-bone halves)", "skin": "Skin-on (for browning at the end)",
          "weight": "700 g", "prep": RAW_CHICKEN_PREP, "method": "Simmered in the spiced tomato stock, then browned in the oven; rice cooked in the stock",
          "note": "Cut follows the original (a whole chicken cut in quarters); for 2 adults we use half."},
 "spice_note": "No chili. The original kabsa spice mix is cardamom, cloves, cinnamon, loomi, cumin, coriander and turmeric with black pepper. We keep all of it with 1/2 tsp black pepper.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Chicken in kabsa stock",
   "ingredients": [
    ("Chicken, bone-in pieces", "700 g", "see meat table"),
    ("Ghee or butter", "2 tbsp", ""),
    ("Onion, chopped", "1 large", ""),
    ("Garlic, crushed", "3 cloves", ""),
    ("Tomatoes, grated", "2", "or 150 ml passata"),
    ("Tomato paste", "1 tbsp", ""),
    ("Carrot, grated", "1", ""),
    ("Dried lime (loomi), pierced", "1", ""),
    ("Cardamom pods", "4", ""),
    ("Whole cloves", "3", ""),
    ("Cinnamon stick", "1", ""),
    ("Bay leaf", "1", ""),
    ("Kabsa spice, ground (non-hot blend: cumin, coriander, turmeric, cardamom, cinnamon, black pepper)", "1 tbsp", "check label: no chili"),
    ("Salt", "1 1/2 tsp", ""),
    ("Hot water", "900 ml", ""),
   ],
   "prep_before": ["Dry the chicken; chop and grate the vegetables."],
   "steps": [
    {"text": "Melt the ghee in the pot; cook the onion and garlic until golden.", "heat": "Medium", "time": "6 min", "done": "Golden"},
    {"text": "Add the chicken pieces and turn them until the outside is no longer pink.", "heat": "Medium-high", "time": "6 min", "done": "Surface sealed, lightly colored"},
    {"text": "Add tomatoes, paste, carrot, loomi, whole spices, kabsa spice and salt. Stir 2 minutes, then add the hot water. Bring to a boil, cover, simmer.", "heat": "Low", "time": "30 min", "done": "Internal 74 °C; meat tender"},
    {"text": "Lift out the chicken. Strain the stock and measure 550 ml for the rice. Put the chicken on an oven tray.", "heat": "Off", "time": "3 min", "done": ""},
    {"text": "Brown the chicken under the oven grill (or in the oven at 220 °C) until the skin is golden.", "heat": "Grill, high", "time": "8 to 10 min", "done": "Golden skin, crisp edges"},
   ]},
  {"title": "Part 2: Kabsa rice",
   "ingredients": [
    ("Basmati rice", "300 g (1 1/2 cups)", "washed, soaked 30 min, drained"),
    ("Chicken kabsa stock (Part 1)", "550 ml", ""),
    ("Saffron (optional)", "1 pinch", "soaked in 1 tbsp hot water"),
    ("Raisins", "2 tbsp", ""),
    ("Toasted almonds", "3 tbsp", "garnish"),
   ],
   "prep_before": ["Toast the almonds."],
   "steps": [
    {"text": "Boil the stock in the rinsed pot, add the rice and raisins, boil until craters appear.", "heat": "High", "time": "6 min", "done": "Liquid level with the rice"},
    {"text": "Drizzle the saffron water, cover tightly, steam on the lowest heat.", "heat": "Very low", "time": "20 min", "done": "Tender, separate grains"},
    {"text": "Rest 10 minutes, fluff.", "heat": "Off", "time": "10 min", "done": ""},
   ]},
 ],
 "timeline": [
  "0:00  Soak rice. Onion, chicken, stock in; simmer 30 min.",
  "0:40  Chicken out; stock strained; rice in.",
  "0:45  Chicken under the grill (10 min).",
  "1:05  Rice rests. Serve at 1:15 with daqqus (see M6 Part 3) and salad.",
 ],
 "presentation": ["Rice on the platter, browned chicken on top, almonds and raisins over, lemon wedges, Jer-Jer Salad (S9), mild daqqus (M6 Part 3)."],
 "mistakes": ["Over-boiling the chicken makes it stringy; 30 minutes gentle simmer is enough.", "Skipping the final browning: the chicken looks pale and boiled. The grill step gives the kabsa look.", "Kabsa spice blends from the shop often contain chili; read the label."],
 "serving": ["Serve hot for 2."],
 "storage": ["Refrigerate up to 2 days; reheat until steaming hot, once only."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "الكبسة السعودية التقليدية بالدجاج",
   "url": "https://kitchen.sayidaty.net/node/32649/الكبسة-السعودية-التقليدية-بالدجاج/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/84/84cf7d80ec41ae7fc4d712e7f17de5f6_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings; also read chef Abdullah Al-Madani's version node/2370). Adapted: scaled to 2 adults, rice cooked separately in the strained stock for even results."},
},
# ---------------------------------------------------------------- M8
{
 "id": "M8", "name": "Chicken Bukhari", "arabic": "رز بخاري بالدجاج",
 "cuisine": "Gulf (Saudi, Hijazi)", "category": "Main",
 "times": {"prep": "20 min (plus 20 min soaking rice)", "cook": "1 h 10 min", "total": "1 h 50 min"},
 "difficulty": "Easy to medium",
 "equipment": ["Heavy pot with lid (3 L)", "Oven tray", "Separate raw-chicken board and knife", "Meat thermometer", "Grater"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Thighs, 4 pieces", "skin": "Skin-on",
          "weight": "650 g", "prep": RAW_CHICKEN_PREP, "method": "Seared, simmered in the tomato-spice stock, then browned in the oven",
          "note": "Cut follows the Saudi-style source (chicken thighs, node/22744)."},
 "spice_note": "No chili in the source. Cardamom, cinnamon, whole black pepper (removed before serving) and ginger. Black pepper, ground, 1/4 tsp.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Chicken in tomato stock",
   "ingredients": [
    ("Chicken thighs, bone-in", "650 g", "see meat table"),
    ("Vegetable oil", "2 tbsp", ""),
    ("Onion, small dice", "1 large", ""),
    ("Tomatoes, small dice", "2", ""),
    ("Tomato paste", "1 1/2 tbsp", ""),
    ("Fresh ginger, grated", "1 tsp", ""),
    ("Cardamom pods", "4", ""),
    ("Cinnamon stick", "1", ""),
    ("Black peppercorns, whole", "6", ""),
    ("Salt", "1 tsp", ""),
    ("Hot water", "700 ml", ""),
   ],
   "prep_before": ["Dry and trim the chicken."],
   "steps": [
    {"text": "Heat the oil in the pot and sear the thighs skin-side down, then turn, until lightly golden. Remove to a plate.", "heat": "Medium-high", "time": "6 min", "done": "Golden skin"},
    {"text": "In the same pot cook the onion until soft, add the tomatoes and cook until they collapse.", "heat": "Medium", "time": "7 min", "done": "Soft, jammy"},
    {"text": "Add tomato paste, ginger, cardamom, cinnamon, peppercorns and salt. Stir 1 minute. Return the chicken, add the hot water, cover, simmer.", "heat": "Low", "time": "30 min", "done": "Internal 74 °C"},
    {"text": "Lift the chicken onto the oven tray. Keep the stock in the pot (you need 500 ml; remove extra or top up).", "heat": "Off", "time": "2 min", "done": ""},
   ]},
  {"title": "Part 2: Bukhari rice",
   "ingredients": [
    ("Basmati rice", "300 g (1 1/2 cups)", "washed, soaked 20 min, drained"),
    ("Carrot, cut into thin matchsticks", "2", ""),
    ("Raisins", "3 tbsp", ""),
    ("Ghee", "1 tbsp", ""),
    ("Vegetable oil", "1 tbsp", "for frying carrot and raisins"),
    ("Toasted almonds", "3 tbsp", "garnish"),
   ],
   "prep_before": ["Cut the carrots; toast the almonds."],
   "steps": [
    {"text": "In a small pan fry the carrot sticks in 1 tbsp oil until soft and lightly caramelized; add the raisins for the last 30 seconds. Set aside.", "heat": "Medium", "time": "5 min", "done": "Carrots soft, edges golden"},
    {"text": "Bring the 500 ml stock to a boil, add the drained rice, boil until craters appear.", "heat": "High", "time": "6 min", "done": "Liquid level with rice"},
    {"text": "Spread the carrot and raisins on top, add the ghee, cover tightly and steam.", "heat": "Very low", "time": "20 min", "done": "Rice tender"},
    {"text": "Meanwhile brown the chicken in the oven.", "heat": "Oven 220 °C", "time": "12 min", "done": "Golden, crisp skin"},
    {"text": "Rest the rice 5 minutes; fluff so the carrots mix through.", "heat": "Off", "time": "5 min", "done": ""},
   ]},
 ],
 "timeline": [
  "0:00  Soak rice. Sear chicken; onion, tomato, spices; simmer 30 min.",
  "0:20  Fry carrots and raisins; toast almonds.",
  "0:45  Chicken out to the tray; rice into stock.",
  "0:50  Chicken in the oven; rice steaming.",
  "1:10  Fluff rice, plate. Serve at 1:15.",
 ],
 "presentation": ["Orange-flecked rice on a platter, chicken on top, almonds over. Serve with mild daqqus (M6 Part 3) or yogurt and Jer-Jer Salad (S9)."],
 "mistakes": ["Too much stock: the rice goes mushy. Measure 500 ml.", "Carrot cut too thick stays hard; cut thin matchsticks.", "Whole peppercorns left in: warn the eater or fish them out before serving."],
 "serving": ["Serve hot for 2."],
 "storage": ["Refrigerate up to 2 days; reheat until steaming hot, once only."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "أرز بخاري بالدجاج على الطريقة السعودية",
   "url": "https://kitchen.sayidaty.net/node/22744/أرز-بخاري-بالدجاج-على-الطريقة-السعودية/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/43/4350e0363f527a824911febe58194c49_w360_h360.jpg",
   "status": "Verified: page opened and read (6 servings; also read node/6849 breast version). Adapted: scaled to 2 adults; exact stock quantity added."},
},
]
