# -*- coding: utf-8 -*-
# HOME COOKBOOK, Mains M9..M16. Servings: 2 adults. Spice level 0/5.
from mains1 import RAW_CHICKEN_PREP, RAW_LAMB_PREP, SAY, MANAL, SHAM

# Shared white-rice part (Sayidaty method), reused by several composite mains.
def white_rice_part(num):
    return {"title": f"Part {num}: White rice (fluffy)",
     "ingredients": [
      ("Basmati rice", "300 g (1 1/2 cups)", "washed, soaked 15 min, drained"),
      ("Vegetable oil or ghee", "1 tbsp", ""),
      ("Salt", "3/4 tsp", ""),
      ("Hot water", "450 ml", ""),
     ],
     "prep_before": ["Wash the rice in several changes of water until clear; soak 15 minutes; drain."],
     "steps": [
      {"text": "Heat the oil in a medium pot, add the drained rice and salt, stir gently.", "heat": "Medium", "time": "2 min", "done": "Grains coated and glossy"},
      {"text": "Add the hot water, bring to a boil, cover tightly, lowest heat.", "heat": "Very low", "time": "18 min", "done": "Water absorbed, rice tender"},
      {"text": "Rest 5 minutes off the heat; fluff with a fork.", "heat": "Off", "time": "5 min", "done": "Separate grains"},
     ]}

WHITE_RICE_SRC = "White rice method: Sayidaty Kitchen, رز أبيض مفلفل, https://kitchen.sayidaty.net/node/10821/رز-أبيض-مفلفل/وصفات-طبخ/وصفات (verified)."

MAINS2 = [
# ---------------------------------------------------------------- M9
{
 "id": "M9", "name": "Lamb Bukhari", "arabic": "رز بخاري باللحم",
 "cuisine": "Gulf (Saudi, Hijazi)", "category": "Main",
 "times": {"prep": "25 min (plus 30 min soaking rice)", "cook": "2 h", "total": "2 h 55 min"},
 "difficulty": "Medium",
 "equipment": ["Large pot with lid (4 L)", "Frying pan", "Sieve", "Separate raw-meat board and knife", "Grater"],
 "meat": {"animal": "Lamb", "type": "Bone-in (as in the original)", "cut": "Shoulder or neck on the bone, 5 cm pieces", "skin": "N/A; trim heavy fat",
          "weight": "700 g", "prep": RAW_LAMB_PREP, "method": "Seared, simmered 90 min with whole spices, then set on the rice to finish",
          "note": "Cut follows the original (bone-in lamb); shoulder suggested."},
 "spice_note": "No chili in chef Israa Barjawi's original. Whole cardamom, bay, loomi, cloves, plus ground seven-spice (non-hot blend), turmeric, cardamom; black pepper reduced to 1/2 tsp.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Lamb",
   "ingredients": [
    ("Lamb on the bone", "700 g", "see meat table"),
    ("Vegetable oil", "2 tbsp", ""),
    ("Onion, chopped", "1 medium", ""),
    ("Cardamom pods", "4", ""),
    ("Bay leaves", "2", ""),
    ("Whole cloves", "3", ""),
    ("Dried lime (loomi), pierced", "1", ""),
    ("Black peppercorns", "6", ""),
    ("Salt", "1 1/2 tsp", ""),
    ("Hot water", "1.2 L", ""),
   ],
   "prep_before": ["Dry and trim the lamb."],
   "steps": [
    {"text": "Heat the oil in the large pot and brown the lamb pieces on all sides.", "heat": "Medium-high", "time": "10 min", "done": "Deep golden crust"},
    {"text": "Add the whole spices and onion; stir 1 minute. Add the hot water and salt. Boil, skim, cover and simmer.", "heat": "Low", "time": "90 min", "done": "Meat tender, falls from the bone"},
    {"text": "Lift out the lamb; strain and keep 600 ml stock.", "heat": "Off", "time": "3 min", "done": ""},
   ]},
  {"title": "Part 2: Rice",
   "ingredients": [
    ("Basmati rice", "300 g (1 1/2 cups)", "washed, soaked 30 min, drained"),
    ("Vegetable oil or ghee", "2 tbsp", ""),
    ("Onion, chopped", "1 medium", ""),
    ("Garlic, crushed", "2 cloves", ""),
    ("Fresh ginger, grated", "1 tsp", ""),
    ("Carrots, grated coarsely", "2", ""),
    ("Tomato paste", "1 tbsp", ""),
    ("Seven-spice (baharat, non-hot)", "1 tsp", "check label: no chili"),
    ("Turmeric", "1/2 tsp", ""),
    ("Cardamom, ground", "1/2 tsp", ""),
    ("Black pepper, ground", "1/2 tsp", ""),
    ("Lamb stock (Part 1)", "600 ml", ""),
    ("Raisins", "3 tbsp", ""),
    ("Toasted nuts (almonds, pine nuts)", "3 tbsp", "garnish"),
   ],
   "prep_before": ["Grate the carrots; soak the rice."],
   "steps": [
    {"text": "Heat the oil in the rinsed pot. Cook onion, garlic and ginger until golden.", "heat": "Medium", "time": "6 min", "done": "Golden"},
    {"text": "Add the carrots and tomato paste; cook until the carrot softens.", "heat": "Medium", "time": "4 min", "done": "Carrot soft, mixture orange"},
    {"text": "Add the rice and ground spices; stir gently to coat.", "heat": "Medium", "time": "2 min", "done": "Grains colored"},
    {"text": "Add the stock, lay the lamb pieces on top, scatter the raisins. Boil until craters appear, then cover and steam.", "heat": "High 5 min, then Very low", "time": "25 min", "done": "Rice tender, no liquid"},
    {"text": "Rest 10 minutes.", "heat": "Off", "time": "10 min", "done": ""},
   ]},
 ],
 "timeline": [
  "0:00  Brown lamb, add water, simmer 90 min. Soak rice.",
  "1:20  Grate carrots, toast nuts.",
  "1:45  Lamb out, stock strained. Onion, carrot, rice, stock, lamb on top.",
  "2:20  Rest. Serve at 2:30.",
 ],
 "presentation": ["Rice on the platter, lamb on top, nuts and raisins over. Serve with mild daqqus (M6 Part 3) and Jer-Jer Salad (S9)."],
 "mistakes": ["Lamb not tender: simmer longer before adding to the rice; the rice stage is too short to soften it.", "Carrot grated too fine disappears; use the coarse side."],
 "serving": ["Serve hot for 2."],
 "storage": ["Refrigerate up to 2 days; reheat until steaming hot, once only."],
 "source": {"site": SAY, "chef": "Chef Israa Barjawi (Sayidaty Kitchen video recipe)", "recipe": "أرز بخاري باللحم لغداء عيد الأضحى بالفيديو",
   "url": "https://kitchen.sayidaty.net/node/19304/أرز-بخاري-باللحم-لغداء-عيد-الأضحى-بالفيديو/وصفات-طبخ/وصفات-الفيديو",
   "image": "https://kitchen.sayidaty.net/uploads/small/a2/a2619020f67f84540b8544da78b8e374_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings; Arabic video on the page). Adapted: scaled from 2 kg lamb / 4 cups rice to 700 g / 1.5 cups."},
},
# ---------------------------------------------------------------- M10
{
 "id": "M10", "name": "Chicken Curry with Boiled Egg", "arabic": "دجاج بالكاري مع بيض مسلوق",
 "cuisine": "Gulf / Indian-influenced", "category": "Main",
 "times": {"prep": "20 min", "cook": "1 h", "total": "1 h 20 min"},
 "difficulty": "Easy to medium",
 "equipment": ["Wide deep pan or pot with lid (3 L)", "Small pot (eggs)", "Separate raw-chicken board and knife", "Meat thermometer"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Thighs (2) and drumsticks (2)", "skin": "Skin removed",
          "weight": "600 g", "prep": RAW_CHICKEN_PREP + " Rub each piece with the spice mix just before it goes in the pan.", "method": "Browned in onions, simmered in coconut milk",
          "note": "The original uses a whole chicken cut into 8. Four bone-in pieces for 2 adults."},
 "spice_note": "Manal Alalem's original uses 1 tsp crushed chili and 2 green hot peppers. BOTH REMOVED. Curry powder must be a MILD blend (check the label: no chili / 'mild'). Sweet paprika for color. Black pepper 1/4 tsp. Result: a creamy, aromatic, non-hot curry.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Chicken curry",
   "ingredients": [
    ("Chicken pieces, bone-in, skinless", "600 g", "see meat table"),
    ("Mild curry powder (no chili)", "2 tsp", ""),
    ("Cumin, ground", "1/2 tsp", ""),
    ("Turmeric", "1/2 tsp", ""),
    ("Sweet paprika", "1/2 tsp", ""),
    ("Coriander, ground", "1/2 tsp", ""),
    ("Salt", "3/4 tsp", ""),
    ("Black pepper, ground", "1/4 tsp", ""),
    ("Corn oil", "2 tbsp", ""),
    ("Onions, sliced", "2 medium", ""),
    ("Garlic, sliced", "2 cloves", ""),
    ("Fresh ginger, finely chopped", "1 tsp", ""),
    ("Coconut milk", "200 ml", ""),
    ("Water", "150 ml", ""),
    ("Cooking cream", "3 tbsp", ""),
    ("Fresh coriander, chopped", "3 tbsp", ""),
    ("Cashews, fried or toasted", "2 tbsp", "garnish"),
   ],
   "prep_before": ["Mix all the dry spices and salt in a bowl.", "Slice the onions, garlic and ginger."],
   "steps": [
    {"text": "Heat the oil in the wide pan; cook the onions until dark golden.", "heat": "Medium", "time": "10 min", "done": "Deep golden"},
    {"text": "Add garlic and ginger; stir until fragrant.", "heat": "Medium", "time": "1 min", "done": "Ginger smell rises"},
    {"text": "Rub each chicken piece with the spice mix and lay it in the pan. Add any leftover spice. Turn the pieces until the surface changes color.", "heat": "Medium-high", "time": "5 min", "done": "No pink surface, spices toasted"},
    {"text": "Add coconut milk and water. Cover and simmer until the chicken is cooked and tender.", "heat": "Low", "time": "40 min", "done": "Internal 74 °C; sauce thick and orange"},
    {"text": "Stir in the cream, let it bubble 1 minute, add the coriander.", "heat": "Low", "time": "2 min", "done": ""},
   ]},
  {"title": "Part 2: Boiled eggs",
   "ingredients": [("Eggs", "2", ""), ("Water and 1/2 tsp salt", "1 L", "")],
   "prep_before": ["Iced water bowl ready."],
   "steps": [{"text": "Boil the eggs 10 minutes (recipe B3), cool, peel and halve.", "heat": "Medium boil", "time": "10 min + 5 min", "done": "Fully set yolk"}]},
  white_rice_part(3),
 ],
 "timeline": [
  "0:00  Onions on. Soak rice.",
  "0:15  Chicken in with spices; coconut milk; simmer 40 min.",
  "0:20  Boil the eggs.",
  "0:35  Start the white rice.",
  "0:58  Cream and coriander into the curry. Rest the rice.",
  "1:05  Serve.",
 ],
 "presentation": ["Rice on one side of the plate, curry beside it, egg halves set into the sauce yolk-up, cashews and coriander on top. Cucumber-yogurt on the side."],
 "mistakes": ["Curry powder with chili: many 'madras' or 'hot' blends contain it. Use a mild blend.", "Boiling the coconut milk hard makes it split; keep a gentle simmer.", "Dry chicken: cooked uncovered or too hot."],
 "serving": ["Serve hot for 2 with white rice and yogurt."],
 "storage": ["Curry keeps 2 days refrigerated; reheat gently until steaming. Add fresh eggs when serving leftovers."],
 "source": {"site": MANAL, "chef": "Manal Alalem", "recipe": "الدجاج بالكاري",
   "url": "https://www.manalonline.com/الدجاج-بالكاري/",
   "image": "https://www.manalonline.com/images/crops/g16x9/الدجاج-بالكاري-v2.jpg",
   "status": "Verified: page opened and read. Adapted: scaled from 1 kg to 600 g chicken; crushed chili and green hot peppers removed; mild curry powder specified; boiled egg added per the dish name. " + WHITE_RICE_SRC},
},
# ---------------------------------------------------------------- M11
{
 "id": "M11", "name": "Chicken with Vegetables in Oven", "arabic": "دجاج وخضروات بالفرن",
 "cuisine": "Gulf / Everyday", "category": "Main",
 "times": {"prep": "25 min", "cook": "1 h 15 min", "total": "1 h 40 min"},
 "difficulty": "Easy",
 "equipment": ["Oven", "Oven roasting bag (as in the original) or deep roasting tray with foil", "Separate raw-chicken board and knife", "Meat thermometer", "Small bowl for spices"],
 "meat": {"animal": "Chicken", "type": "Bone-in, whole", "cut": "Whole small chicken, left whole", "skin": "Skin-on",
          "weight": "1 kg (small bird; 2 adults with leftovers for Chicken Mix B14)", "prep": RAW_CHICKEN_PREP + " Remove giblets; rub the spice mix inside and outside.", "method": "Roasted in an oven bag with vegetables",
          "note": "Cut follows the original (whole chicken). For a smaller meal use 2 leg quarters (700 g) and reduce roasting to 55 minutes."},
 "spice_note": "Manal Alalem's original includes 1 chopped green hot pepper in the stuffing. REMOVED. The rub (turmeric, sweet paprika, garlic powder, onion powder, cumin, coriander, ginger, mild curry, cardamom) is kept. Black pepper 1/2 tsp. Mild curry powder only.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Whole chicken", "1 kg", "see meat table"),
   ("RUB: turmeric", "1/2 tsp", ""),
   ("RUB: sweet paprika", "1 tsp", ""),
   ("RUB: garlic powder", "1/2 tsp", ""),
   ("RUB: onion powder", "1/2 tsp", ""),
   ("RUB: cumin, ground", "1/2 tsp", ""),
   ("RUB: coriander, ground", "1/2 tsp", ""),
   ("RUB: ginger, ground", "1/4 tsp", ""),
   ("RUB: mild curry powder", "1/2 tsp", ""),
   ("RUB: cardamom, ground", "1/4 tsp", ""),
   ("RUB: salt", "1 1/2 tsp", ""),
   ("RUB: black pepper", "1/2 tsp", ""),
   ("Olive oil", "2 tbsp", ""),
   ("STUFFING: onion, roughly chopped", "1/2", ""),
   ("STUFFING: garlic cloves, crushed", "2", ""),
   ("Carrots, quartered lengthwise", "2", ""),
   ("Potatoes, quartered", "2 medium", ""),
   ("Mushrooms, whole", "6", ""),
   ("Green beans, trimmed", "100 g", ""),
   ("Tomato, quartered", "1", ""),
   ("Cauliflower florets", "1 cup", ""),
  ],
  "prep_before": ["Mix all rub ingredients in the small bowl. Dry the chicken, rub half the mix inside and out with the olive oil. Mix the stuffing onion and garlic with a pinch of rub and push into the cavity.", "Cut the vegetables; toss with the remaining rub and 1 tbsp oil."],
  "steps": [
   {"text": "Heat the oven to 180 °C. Put the vegetables in the oven bag (or tray), set the chicken on top breast-up, close the bag as the packet says (or cover the tray tightly with foil).", "heat": "Oven 180 °C", "time": "5 min", "done": ""},
   {"text": "Roast.", "heat": "Oven 180 °C", "time": "60 min", "done": "Internal 75 °C in the thickest thigh (not touching bone); juices run clear"},
   {"text": "Cut the bag open (or remove the foil) carefully, steam is hot. Roast uncovered to brown.", "heat": "Oven 200 °C", "time": "15 min", "done": "Golden skin"},
   {"text": "Rest the chicken 10 minutes before carving.", "heat": "Off", "time": "10 min", "done": ""},
  ],
 }],
 "mistakes": ["Opening the bag without care: hot steam burns. Cut away from your face.", "Vegetables cut large stay hard; keep potatoes in quarters no bigger than 4 cm.", "Carving at once lets the juices run out; rest 10 minutes."],
 "serving": ["Carve at the table; serve the vegetables and juices alongside, with Arabic bread and yogurt-cucumber salad or Green Mix (S5)."],
 "storage": ["Refrigerate up to 2 days. Strip leftover meat from the bones the same evening; use for Chicken Mix (B14). Reheat until steaming hot."],
 "source": {"site": MANAL, "chef": "Manal Alalem", "recipe": "دجاج وخضروات بالفرن",
   "url": "https://www.manalonline.com/دجاج-وخضروات-بالفرن/",
   "image": "https://www.manalonline.com/images/crops/g16x9/دجاج-وخضروات-بالفرن-v2.jpg",
   "status": "Verified: page opened and read (Arabic YouTube video embedded). Adapted: green hot pepper removed; spice amounts scaled for a 1 kg bird; mild curry specified."},
},
# ---------------------------------------------------------------- M12
{
 "id": "M12", "name": "Chicken Salona", "arabic": "صالونة دجاج",
 "cuisine": "Gulf (Emirati / Saudi)", "category": "Main",
 "times": {"prep": "20 min", "cook": "55 min", "total": "1 h 15 min"},
 "difficulty": "Easy",
 "equipment": ["Pot with lid (3 L)", "Separate raw-chicken board and knife", "Meat thermometer", "Medium pot for rice"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Thighs, 4 pieces (or 2 thighs + 2 drumsticks)", "skin": "Skin removed (so the stew is not greasy)",
          "weight": "600 g", "prep": RAW_CHICKEN_PREP, "method": "Browned, then stewed with vegetables in tomato stock",
          "note": "Cut follows the original (chicken thighs, 2-serving recipe node/25452)."},
 "spice_note": "No chili. The Saudi version (node/6754) adds green hot pepper; that is not used. Ground coriander, ginger, cardamom, loomi and turmeric; black pepper 1/4 tsp.",
 "house_rule": "House rule: no minced meat in salona. This recipe uses chicken pieces only.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Salona",
   "ingredients": [
    ("Chicken thighs, skinless", "600 g", "see meat table"),
    ("Olive oil or vegetable oil", "2 tbsp", ""),
    ("Onions, chopped", "2 medium", ""),
    ("Garlic, chopped", "2 cloves", ""),
    ("Potatoes, 3 cm chunks", "2 medium", ""),
    ("Carrot, thick slices", "1", ""),
    ("Zucchini (courgette), thick slices", "1", ""),
    ("Tomatoes, chopped", "2", ""),
    ("Tomato paste", "1 1/2 tbsp", ""),
    ("Dried limes (loomi), pierced", "2", ""),
    ("Cardamom pods", "2", ""),
    ("Coriander, ground", "1/2 tsp", ""),
    ("Ginger, ground", "1/4 tsp", ""),
    ("Turmeric", "1/4 tsp", ""),
    ("Cumin, ground", "1/4 tsp", ""),
    ("Salt", "1 tsp", ""),
    ("Black pepper, ground", "1/4 tsp", ""),
    ("Hot water", "600 ml", ""),
    ("Fresh coriander, chopped", "2 tbsp", "to finish"),
   ],
   "prep_before": ["Dry the chicken. Chop all vegetables; measure spices."],
   "steps": [
    {"text": "Heat the oil in the pot; cook the onions until golden, add garlic 1 minute.", "heat": "Medium", "time": "7 min", "done": "Golden"},
    {"text": "Add the chicken and turn until the surface is sealed and lightly colored.", "heat": "Medium-high", "time": "5 min", "done": "No pink surface"},
    {"text": "Add tomatoes, tomato paste, loomi, cardamom and all ground spices; stir 2 minutes.", "heat": "Medium", "time": "2 min", "done": "Paste darkens, aromatic"},
    {"text": "Add hot water and salt; bring to a boil, cover, simmer.", "heat": "Low", "time": "20 min", "done": "Chicken half cooked"},
    {"text": "Add potatoes and carrot; cover and cook 15 minutes. Add zucchini; cook until all vegetables are tender and the sauce has thickened.", "heat": "Low", "time": "15 + 10 min", "done": "Internal 74 °C in chicken; potato soft; sauce coats a spoon"},
    {"text": "Taste for salt; scatter the fresh coriander.", "heat": "Off", "time": "1 min", "done": ""},
   ]},
  white_rice_part(2),
 ],
 "timeline": ["0:00  Onions, chicken, spices, water; simmer. Soak rice.", "0:25  Potatoes and carrot in.", "0:35  Start white rice. Zucchini in at 0:40.", "0:58  Rice rests; salona finished. Serve at 1:05."],
 "presentation": ["Serve the salona in a deep dish with the white rice beside it, Arabic bread, and lemon wedges."],
 "mistakes": ["Adding all vegetables at once: zucchini turns to mush. Stagger them.", "Watery sauce: simmer uncovered the last 5 minutes.", "Loomi not pierced gives little flavor; pierce it with a knife tip."],
 "serving": ["Serve hot for 2 with white rice or bread."],
 "storage": ["Keeps 3 days refrigerated; reheat until steaming, once only. Freezes well up to 1 month (without the rice)."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "صالونة الدجاج",
   "url": "https://kitchen.sayidaty.net/node/25452/صالونة-الدجاج/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/11/115bb037d0e2aa4cf389d87ce4df5555_w360_h360.jpg",
   "status": "Verified: page opened and read (2 servings). Adapted: quantities made exact, staged vegetable timing added; hot pepper from the Saudi variant excluded. " + WHITE_RICE_SRC},
},
# ---------------------------------------------------------------- M13
{
 "id": "M13", "name": "Lamb Salona", "arabic": "صالونة لحم",
 "cuisine": "Gulf", "category": "Main",
 "times": {"prep": "20 min", "cook": "1 h 45 min", "total": "2 h 05 min"},
 "difficulty": "Easy",
 "equipment": ["Pot with lid (3 L)", "Separate raw-meat board and knife", "Medium pot for rice"],
 "meat": {"animal": "Lamb", "type": "Boneless (original: lamb or veal cubes)", "cut": "Shoulder or leg, 3 cm cubes", "skin": "N/A; trim fat",
          "weight": "500 g", "prep": RAW_LAMB_PREP, "method": "Browned, simmered until tender, then stewed with vegetables",
          "note": "Cut follows the original (cubed lamb); shoulder suggested."},
 "spice_note": "No chili in the source. Turmeric, cardamom, cinnamon stick; black pepper 1/2 tsp. The sweet green bell pepper in the original is kept (it is not hot).",
 "house_rule": "House rule: no minced meat in salona. Cubes only.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Salona",
   "ingredients": [
    ("Lamb cubes", "500 g", "see meat table"),
    ("Ghee", "2 tbsp", ""),
    ("Onions, chopped", "1 large", ""),
    ("Garlic, crushed", "2 cloves", ""),
    ("Tomatoes, chopped", "3", ""),
    ("Tomato paste", "1 tbsp", ""),
    ("Green bell pepper (sweet), strips", "1/2", ""),
    ("Carrot, thick slices", "1", ""),
    ("Potatoes, large chunks", "2 medium", ""),
    ("Zucchini, thick slices (optional)", "1", ""),
    ("Dried lime (loomi), pierced", "1", ""),
    ("Cinnamon stick", "1 small", ""),
    ("Cardamom, ground", "1/4 tsp", ""),
    ("Turmeric", "1/2 tsp", ""),
    ("Salt", "1 tsp", ""),
    ("Black pepper, ground", "1/2 tsp", ""),
    ("Hot water", "900 ml", ""),
    ("Parsley or coriander, chopped", "2 tbsp", "to finish"),
   ],
   "prep_before": ["Dry and cube the lamb; chop the vegetables."],
   "steps": [
    {"text": "Heat the ghee; cook the onion until golden, add garlic 1 minute.", "heat": "Medium", "time": "7 min", "done": "Golden"},
    {"text": "Add the lamb and brown on all sides.", "heat": "Medium-high", "time": "8 min", "done": "Browned"},
    {"text": "Add tomatoes, tomato paste, loomi, cinnamon, cardamom, turmeric, salt and pepper; stir 2 minutes. Add the hot water, boil, cover and simmer until the lamb is tender.", "heat": "Low", "time": "60 to 75 min", "done": "Fork slides into the meat easily"},
    {"text": "Add potatoes, carrot and bell pepper; cook 15 minutes. Add zucchini; cook until everything is tender and the sauce is thick.", "heat": "Low", "time": "15 + 10 min", "done": "Vegetables soft, sauce coats the spoon"},
    {"text": "Taste for salt; add the herbs.", "heat": "Off", "time": "1 min", "done": ""},
   ]},
  white_rice_part(2),
 ],
 "timeline": ["0:00  Onion, lamb, spices, water; simmer 70 min. Soak rice.", "1:15  Vegetables in.", "1:20  Start the rice.", "1:45  Serve."],
 "presentation": ["Deep bowl of salona, white rice beside, bread and lemon."],
 "mistakes": ["Vegetables added with the raw lamb overcook into mush. Wait until the lamb is tender.", "Sauce too thin: simmer uncovered at the end."],
 "serving": ["Serve hot for 2."],
 "storage": ["Keeps 3 days refrigerated; freezes 1 month without rice. Reheat until steaming."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "صالونة اللحم الخليجية",
   "url": "https://kitchen.sayidaty.net/node/38473/صالونة-اللحم-الخليجية/وصفات-طبخ/وصفات-رمضانية",
   "image": "https://kitchen.sayidaty.net/uploads/small/02/0288cf965e347f8572b2ad8a419658d5_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings). Adapted: scaled to 2 adults, lamb browned instead of pre-boiled, staged vegetables. " + WHITE_RICE_SRC},
},
# ---------------------------------------------------------------- M14
{
 "id": "M14", "name": "Mashi Malfouf", "arabic": "محشي ملفوف",
 "cuisine": "Levantine", "category": "Main",
 "times": {"prep": "50 min", "cook": "1 h", "total": "1 h 50 min"},
 "difficulty": "Medium (rolling takes practice)",
 "equipment": ["Large pot (5 L) for blanching the cabbage", "Pot with lid (3 L) for cooking the rolls", "Heat-proof plate that fits inside the pot", "Separate raw-meat board and knife", "Mixing bowl"],
 "meat": {"animal": "Lamb", "type": "Minced (as in the original)", "cut": "Lean minced lamb (shoulder or leg, 15 percent fat)", "skin": "N/A",
          "weight": "200 g", "prep": RAW_LAMB_PREP + " Minced meat spoils fast: keep it cold until mixing.", "method": "Mixed raw into the rice filling, cooked inside the rolls",
          "note": "Minced meat is traditional for malfouf and is allowed here (the house rule excludes minced meat from pasta, salona and samosa only). For a meat-free version, replace the lamb with 100 g extra rice and 1 chopped tomato."},
 "spice_note": "No chili. Mixed spice (non-hot), cumin, black pepper 1/4 tsp. Lots of garlic and lemon, which are sour, not hot.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("White cabbage", "1 small head (about 1 kg)", "you need about 14 leaves"),
   ("Short-grain (Egyptian) rice", "150 g (3/4 cup)", "washed and drained"),
   ("Minced lamb", "200 g", "see meat table"),
   ("Onion, finely chopped", "1 small", ""),
   ("Tomato, grated", "1", ""),
   ("Parsley, chopped", "2 tbsp", ""),
   ("Dill, chopped", "2 tbsp", ""),
   ("Fresh coriander, chopped", "2 tbsp", ""),
   ("Vegetable oil", "1 tbsp", ""),
   ("Salt", "1 tsp", ""),
   ("Black pepper, ground", "1/4 tsp", ""),
   ("Mixed spice (non-hot)", "1/2 tsp", ""),
   ("Cumin, ground", "1/4 tsp", ""),
   ("COOKING: garlic cloves, peeled, whole", "6", ""),
   ("COOKING: lemon juice", "4 tbsp", ""),
   ("COOKING: dried mint", "1 tsp", ""),
   ("COOKING: tomato paste", "1 tbsp", ""),
   ("COOKING: hot water", "about 600 ml", "to cover"),
   ("COOKING: salt", "1/2 tsp", ""),
  ],
  "prep_before": ["Core the cabbage. Boil it whole in the large pot of salted water; as the outer leaves soften (3 to 5 min) peel them off with tongs onto a tray. Continue until you have 14 leaves. Cut out the thick central rib of each leaf (keep the ribs).", "Mix the filling: rice, minced lamb, onion, tomato, herbs, oil, salt, pepper, mixed spice, cumin. Mix with your hands (wash before and after)."],
  "steps": [
   {"text": "Line the bottom of the cooking pot with the cabbage ribs and any torn leaves (this stops the rolls from burning).", "heat": "", "time": "2 min", "done": ""},
   {"text": "Lay a leaf flat, put 1 heaped tbsp filling along the wide end in a line, fold the sides in, and roll firmly but not tight (the rice swells). Repeat.", "heat": "", "time": "20 min", "done": "14 rolls, finger-thick"},
   {"text": "Pack the rolls seam-down in the pot in tight layers, tucking the garlic cloves between them.", "heat": "", "time": "5 min", "done": ""},
   {"text": "Stir tomato paste, lemon juice, dried mint and salt into the hot water and pour over until the rolls are just covered. Put the heat-proof plate on top to hold them down.", "heat": "", "time": "2 min", "done": "Liquid just covers the rolls"},
   {"text": "Bring to a boil, then cover and simmer until the rice inside is fully cooked.", "heat": "Low", "time": "50 to 60 min", "done": "Cut a roll: rice soft, meat grey all through (no pink), liquid mostly absorbed"},
   {"text": "Rest 10 minutes off the heat before lifting the plate and unpacking the rolls.", "heat": "Off", "time": "10 min", "done": ""},
  ],
 }],
 "mistakes": ["Rolling too tight: the rice bursts the leaves. Leave a little room.", "Leaves boiled too long tear; take each leaf as soon as it bends easily.", "Not lining the pot: the bottom rolls scorch.", "Too much water makes the rolls fall apart; just cover them."],
 "serving": ["Pile the rolls on a platter with the soft garlic cloves, squeeze extra lemon over, and serve with yogurt and a cucumber-tomato salad. Enough for 2 with some left over."],
 "storage": ["Keeps 3 days refrigerated; reheat in a covered pan with 2 tbsp water until steaming hot (meat filling must reach 75 °C). Freezes well 1 month."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "محشي ملفوف بالرز واللحم المفروم",
   "url": "https://kitchen.sayidaty.net/node/36729/محشي-ملفوف-بالرز-واللحم-المفروم/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/19/195385b1e23546d9e5675fb072c28938_w360_h360.jpg",
   "status": "Verified: page opened and read (5 servings; also read node/10164 and the garlic-lemon version node/28394). Adapted: scaled to 2 adults, raw filling method and garlic-lemon-mint cooking liquid taken from the Sayidaty garlic version. Manal Alalem's site has no malfouf recipe (checked the full sitemap)."},
},
# ---------------------------------------------------------------- M15
{
 "id": "M15", "name": "Cajun Chicken with Lobia and White Rice", "arabic": "دجاج كاجن (بدون حار) مع لوبيا ورز أبيض",
 "cuisine": "American-Cajun style chicken; Egyptian lobia; Gulf rice", "category": "Main",
 "times": {"prep": "25 min (plus overnight soak for dried lobia)", "cook": "1 h", "total": "1 h 30 min"},
 "difficulty": "Easy to medium",
 "equipment": ["Griddle or frying pan", "Pot with lid (2.5 L) for lobia", "Medium pot for rice", "Separate raw-chicken board and knife", "Meat thermometer"],
 "meat": {"animal": "Chicken", "type": "Boneless", "cut": "Breast fillets, flattened to 1.5 cm (or boneless thigh fillets)", "skin": "Skinless",
          "weight": "400 g (2 fillets)", "prep": RAW_CHICKEN_PREP + " Rub with the Cajun mix and oil 20 minutes before cooking.", "method": "Pan-grilled",
          "note": "There is no Arabic source for Cajun chicken; breast fillet is the usual cut for this dish and is our suggestion."},
 "spice_note": "IMPORTANT: real Cajun seasoning is built on cayenne pepper and is hot. This is a NON-SPICY CAJUN MIX: sweet paprika, garlic powder, onion powder, dried oregano, dried thyme, a little cumin and black pepper. ZERO cayenne, zero chili. Do not buy a ready Cajun blend (all contain cayenne). Flavor is smoky-herby, not hot. This changes the dish from hot to mild by design.",
 "composite": True,
 "parts": [
  {"title": "Part 1: Lobia (black-eyed beans in tomato sauce)",
   "ingredients": [
    ("Black-eyed beans (lobia), dried", "150 g", "soaked overnight; or 400 g canned, drained"),
    ("Onion, chopped", "1 medium", ""),
    ("Garlic, chopped", "2 cloves", ""),
    ("Tomatoes, chopped", "2", ""),
    ("Tomato paste", "1 tbsp", ""),
    ("Vegetable oil", "2 tbsp", ""),
    ("Cumin, ground", "1/2 tsp", ""),
    ("Salt", "3/4 tsp", ""),
    ("Black pepper, ground", "1/4 tsp", ""),
    ("Hot water", "500 ml", "less if canned"),
    ("Parsley, chopped", "1 tbsp", ""),
   ],
   "prep_before": ["Dried lobia: soak overnight, drain, boil in fresh water 30 minutes until almost tender, drain."],
   "steps": [
    {"text": "Heat the oil; cook onion and garlic until golden.", "heat": "Medium", "time": "6 min", "done": "Golden"},
    {"text": "Add tomatoes and tomato paste; cook until thick.", "heat": "Medium", "time": "4 min", "done": "Jammy"},
    {"text": "Add the beans, cumin, salt, pepper and hot water. Cover and simmer until the beans are soft and the sauce is thick.", "heat": "Low", "time": "25 min (10 min if canned)", "done": "Beans soft, sauce coats them"},
    {"text": "Finish with parsley.", "heat": "Off", "time": "", "done": ""},
   ]},
  {"title": "Part 2: Non-spicy Cajun chicken",
   "ingredients": [
    ("Chicken breast fillets", "400 g", "see meat table"),
    ("MIX: sweet paprika", "2 tsp", "not hot, not 'Cajun' blend"),
    ("MIX: garlic powder", "1 tsp", ""),
    ("MIX: onion powder", "1 tsp", ""),
    ("MIX: dried oregano", "1/2 tsp", ""),
    ("MIX: dried thyme", "1/2 tsp", ""),
    ("MIX: cumin, ground", "1/4 tsp", ""),
    ("MIX: salt", "3/4 tsp", ""),
    ("MIX: black pepper", "1/4 tsp", ""),
    ("Olive oil", "2 tbsp", ""),
    ("Lemon wedges", "2", ""),
   ],
   "prep_before": ["Stir the mix together. Flatten the fillets, rub with oil and the mix; rest 20 minutes in the fridge."],
   "steps": [
    {"text": "Heat the griddle until very hot. Lay in the chicken; do not move it for 5 minutes, then turn.", "heat": "Medium-high", "time": "5 to 6 min per side", "done": "Internal 74 °C; dark red-brown crust; juices clear"},
    {"text": "Rest 5 minutes on a clean plate, then slice.", "heat": "Off", "time": "5 min", "done": ""},
   ]},
  white_rice_part(3),
 ],
 "timeline": ["0:00  Beans simmering (or canned later). Season chicken. Soak rice.", "0:30  Start the rice.", "0:40  Grill the chicken.", "0:55  Rest chicken, fluff rice, serve at 1:00."],
 "presentation": ["Rice on one side, lobia in its sauce beside it, sliced chicken fanned on top, lemon wedge, parsley."],
 "mistakes": ["Shop-bought Cajun seasoning: always contains cayenne. Make the mix above.", "Paprika burns on a too-hot pan and turns bitter; medium-high, not maximum.", "Dried beans not soaked stay hard."],
 "serving": ["Serve hot for 2."],
 "storage": ["Lobia keeps 3 days refrigerated (freezes 1 month). Chicken 2 days. Reheat until steaming hot."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "اللوبيا الناشفة بصوص معجون الطماطم",
   "url": "https://kitchen.sayidaty.net/node/38623/اللوبيا-الناشفة-بصوص-معجون-الطماطم/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/52/52fbfa26448e750c8ba071b568b86637_w360_h360.jpg",
   "status": "Verified (lobia): page opened and read (3 servings), scaled to 2. Cajun chicken: no Arabic source exists for a chili-free Cajun; the non-spicy mix is a household adaptation. " + WHITE_RICE_SRC},
},
# ---------------------------------------------------------------- M16
{
 "id": "M16", "name": "Grilled Chicken with Molokhia and White Rice", "arabic": "دجاج مشوي مع ملوخية ورز أبيض",
 "cuisine": "Egyptian", "category": "Main",
 "times": {"prep": "25 min", "cook": "1 h 10 min", "total": "1 h 35 min"},
 "difficulty": "Medium",
 "equipment": ["Pot (3 L) for stock and molokhia", "Oven tray or griddle for the chicken", "Small frying pan (garlic 'taqliya')", "Whisk", "Separate raw-chicken board and knife", "Meat thermometer"],
 "meat": {"animal": "Chicken", "type": "Bone-in", "cut": "Leg quarters, 2 (thigh + drumstick)", "skin": "Skin-on",
          "weight": "700 g", "prep": RAW_CHICKEN_PREP, "method": "Simmered first to make the stock for the molokhia, then grilled in the oven for color",
          "note": "The original boils a whole chicken; leg quarters are our suggestion for 2 adults and for grilling."},
 "spice_note": "No chili. Ground coriander and garlic are the whole flavor of molokhia. Black pepper 1/4 tsp. (Chili vinegar is sometimes served alongside in Egypt; it is not used here.)",
 "composite": True,
 "parts": [
  {"title": "Part 1: Chicken and stock",
   "ingredients": [
    ("Chicken leg quarters", "2 (700 g)", "see meat table"),
    ("Water", "1.2 L", ""),
    ("Onion, halved", "1", ""),
    ("Cardamom pods", "3", ""),
    ("Bay leaf", "1", ""),
    ("Cinnamon stick", "1 small", ""),
    ("Salt", "1 1/2 tsp", ""),
    ("Black pepper, ground", "1/4 tsp", ""),
    ("Olive oil (for grilling)", "1 tbsp", ""),
    ("Lemon juice (for grilling)", "1 tbsp", ""),
   ],
   "prep_before": ["Dry the chicken."],
   "steps": [
    {"text": "Put the chicken, water, onion, spices and salt in the pot. Boil, skim, then simmer.", "heat": "Low", "time": "35 min", "done": "Internal 74 °C"},
    {"text": "Lift the chicken onto an oven tray; brush with oil and lemon. Strain the stock; keep 800 ml.", "heat": "Off", "time": "3 min", "done": ""},
    {"text": "Grill the chicken in the oven until the skin is golden and crisp (do this while the molokhia cooks).", "heat": "Oven grill, 220 °C", "time": "12 to 15 min", "done": "Golden skin"},
   ]},
  {"title": "Part 2: Molokhia",
   "ingredients": [
    ("Molokhia leaves, finely minced (frozen block is fine)", "400 g", "fresh leaves need washing, drying and very fine chopping"),
    ("Hot chicken stock (Part 1)", "800 ml", ""),
    ("Garlic, crushed", "5 cloves", ""),
    ("Coriander, ground", "1 1/2 tbsp", ""),
    ("Ghee or butter", "2 tbsp", ""),
    ("Salt", "to taste", "the stock is salted"),
    ("Lemon wedges", "2", "for serving"),
   ],
   "prep_before": ["If frozen: do not thaw; it goes straight into hot stock."],
   "steps": [
    {"text": "Bring the stock to a boil. Add the molokhia and stir with the whisk until it melts into the stock. Lower the heat and simmer UNCOVERED. Do not boil hard and do not cover (it sinks and separates).", "heat": "Low", "time": "10 min", "done": "Smooth green soup, thick like cream"},
    {"text": "Taqliya: in the small pan fry the garlic in the ghee until pale gold, add the ground coriander and stir 20 seconds until fragrant.", "heat": "Medium", "time": "2 min", "done": "Golden garlic, coriander aromatic"},
    {"text": "Pour the sizzling taqliya into the molokhia, stir once, cook 2 more minutes, then turn off. Taste for salt.", "heat": "Low then Off", "time": "2 min", "done": "A strong garlic-coriander aroma"},
   ]},
  white_rice_part(3),
 ],
 "timeline": ["0:00  Chicken into the pot; simmer 35 min. Soak rice.", "0:35  Start the rice. Chicken out; stock strained; chicken into the oven.", "0:45  Molokhia into the stock; make taqliya.", "1:00  Rice rests; chicken golden. Serve at 1:05."],
 "presentation": ["Molokhia in a deep bowl, rice on a plate, grilled chicken quarter on top, lemon wedge. Each person spoons molokhia over the rice."],
 "mistakes": ["Covering or hard-boiling the molokhia makes it sink and go stringy. Low heat, uncovered, 10 minutes.", "Burnt garlic in the taqliya makes it bitter; pale gold only.", "Thin molokhia: too much stock. 800 ml for 400 g is right."],
 "serving": ["Serve hot for 2 with lemon and Arabic bread."],
 "storage": ["Molokhia keeps 2 days refrigerated; reheat gently without boiling. Freezes 1 month."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "ملوخية بالدجاج",
   "url": "https://kitchen.sayidaty.net/node/12733/ملوخية-بالدجاج/وصفات-طبخ/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/20/207877d5c4d6031e98f08e874fcc012a_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings; also read node/18644). Adapted: scaled to 2 adults, chicken grilled after boiling per the dish name. Shamlola has no molokhia-with-chicken page (sitemap checked); its lamb version was read for the taqliya method. " + WHITE_RICE_SRC},
},
]
