# -*- coding: utf-8 -*-
# HOME COOKBOOK, Salads S1..S9. Servings: 2 adults. Spice level 0/5.
SAY = "Sayidaty Kitchen (kitchen.sayidaty.net)"
MANAL = "Manal Alalem (manalonline.com)"

SALADS = [
# ---------------------------------------------------------------- S1
{
 "id": "S1", "name": "Fattoush", "arabic": "فتوش",
 "cuisine": "Levantine (Lebanese)", "category": "Salad",
 "times": {"prep": "15 min", "cook": "8 min (toasting the bread)", "total": "23 min"},
 "difficulty": "Easy",
 "equipment": ["Large salad bowl", "Small jar or bowl for dressing", "Chopping board and knife (vegetables)", "Baking tray or frying pan for the bread"],
 "meat": None,
 "spice_note": "Sumac gives a sour, lemony taste, not heat. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Romaine lettuce, chopped", "1/2 head (150 g)", ""),
   ("Tomatoes, diced", "2 medium", ""),
   ("Cucumber, diced", "1 medium", ""),
   ("Radishes, sliced thin", "3", ""),
   ("Green bell pepper (sweet), diced", "1/2", ""),
   ("Spring onions, sliced", "2", ""),
   ("Parsley, chopped", "3 tbsp", ""),
   ("Fresh mint leaves, torn", "2 tbsp", ""),
   ("Arabic bread (pita)", "1 loaf", "cut into 2 cm squares"),
   ("Olive oil (for the bread)", "1 tbsp", ""),
   ("DRESSING: olive oil", "3 tbsp", ""),
   ("DRESSING: lemon juice", "2 tbsp", ""),
   ("DRESSING: pomegranate molasses", "1 tbsp", ""),
   ("DRESSING: sumac", "1 tsp", "plus a pinch to finish"),
   ("DRESSING: salt", "1/2 tsp", ""),
   ("DRESSING: garlic, crushed (optional)", "1/2 clove", ""),
  ],
  "prep_before": ["Wash all vegetables and herbs; dry well in a salad spinner or on a towel (wet leaves make a watery salad).", "Cut the bread into squares."],
  "steps": [
   {"text": "Toss the bread squares with 1 tbsp olive oil, spread on a tray and toast in the oven until golden and crisp. (Or fry in a dry pan, stirring.)", "heat": "Oven 200 °C", "time": "6 to 8 min", "done": "Golden, crisp, snaps when bent"},
   {"text": "Shake the dressing ingredients together in the jar.", "heat": "", "time": "1 min", "done": "Thick and glossy"},
   {"text": "Put lettuce, tomato, cucumber, radish, pepper, spring onion, parsley and mint in the bowl.", "heat": "", "time": "2 min", "done": ""},
   {"text": "Just before serving pour the dressing over, toss, then add the toasted bread and toss once more. Sprinkle a pinch of sumac on top.", "heat": "", "time": "1 min", "done": "Bread still crisp"},
  ],
 }],
 "mistakes": ["Adding the bread early: it goes soggy. Add at the last moment.", "Dressing too early wilts the lettuce; dress at the table.", "Wet vegetables dilute the dressing; dry them."],
 "serving": ["Serve at once as a side to any rice or meat main. Enough for 2 as a side."],
 "storage": ["Chopped vegetables (undressed) keep 1 day covered in the fridge; toasted bread keeps 3 days in an airtight box. Dressed salad does not keep."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "سلطة فتوش",
   "url": "https://kitchen.sayidaty.net/node/13899/سلطة-فتوش/السلطات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/b3/b37d14c228c1f4120a3d0cf35e6ada70_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings). Adapted: scaled to 2 adults."},
},
# ---------------------------------------------------------------- S2
{
 "id": "S2", "name": "Walnut Salad", "arabic": "سلطة الجوز والرمان",
 "cuisine": "Levantine", "category": "Salad",
 "times": {"prep": "15 min", "cook": "3 min (toasting walnuts)", "total": "18 min"},
 "difficulty": "Easy",
 "equipment": ["Salad bowl", "Small dry frying pan", "Small jar for dressing"],
 "meat": None,
 "spice_note": "No spices beyond salt. No chili.",
 "house_rule": "House rule: no lemon juice on apple or fruit. The dressing goes on the greens; if apple is added, keep it in a separate small bowl, plain, and do not pour lemon on it.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Walnut halves", "60 g (1/2 cup)", ""),
   ("Rocket or baby spinach", "100 g (3 cups loosely packed)", ""),
   ("Cherry tomatoes, halved", "8", ""),
   ("Pomegranate seeds", "4 tbsp", "when in season"),
   ("Feta cheese, crumbled", "60 g", ""),
   ("Parsley, chopped", "2 tbsp", ""),
   ("DRESSING: olive oil", "2 tbsp", ""),
   ("DRESSING: pomegranate molasses", "1 tbsp", ""),
   ("DRESSING: lemon juice", "1 tbsp", "on the greens only, never on fruit"),
   ("DRESSING: salt", "1/4 tsp", ""),
   ("Green apple, sliced (optional, served separately, plain)", "1/2", "no lemon on it"),
  ],
  "prep_before": ["Wash and dry the greens. Halve the tomatoes. Remove the pomegranate seeds.", "If using apple, slice it just before serving and keep it plain in its own bowl."],
  "steps": [
   {"text": "Toast the walnuts in the dry pan, shaking often, until they smell nutty. Tip onto a plate to cool.", "heat": "Medium-low", "time": "3 min", "done": "Fragrant, slightly darker; do not let them blacken"},
   {"text": "Shake the dressing ingredients in the jar.", "heat": "", "time": "1 min", "done": ""},
   {"text": "Put greens, tomatoes, parsley and most of the pomegranate seeds in the bowl. Pour the dressing and toss.", "heat": "", "time": "2 min", "done": "Leaves lightly coated"},
   {"text": "Scatter feta, walnuts and the remaining seeds on top. Serve the plain apple slices alongside if using.", "heat": "", "time": "1 min", "done": ""},
  ],
 }],
 "mistakes": ["Burnt walnuts taste bitter; take them off the heat as soon as they smell toasted.", "Over-dressing: the greens should glisten, not sit in liquid."],
 "serving": ["Serve immediately as a side or light starter for 2."],
 "storage": ["Toasted walnuts keep 1 week in a jar. Dressed salad does not keep."],
 "source": {"site": SAY, "chef": "Lina Al-Hourani (Sayidaty Kitchen video recipe)", "recipe": "سلطة الجوز والرمان بالفيديو",
   "url": "https://kitchen.sayidaty.net/node/34868/سلطة-الجوز-والرمان-بالفيديو/السلطات/وصفات-الفيديو",
   "image": "https://kitchen.sayidaty.net/uploads/small/61/61b838ceb4c05f8c477404de21c829ec_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings; Arabic video on the page). Adapted: scaled to 2 adults, greens added, apple option kept plain (house rule)."},
},
# ---------------------------------------------------------------- S3
{
 "id": "S3", "name": "Corn Salad", "arabic": "سلطة الذرة",
 "cuisine": "International / Everyday", "category": "Salad",
 "times": {"prep": "10 min", "cook": "0 min", "total": "10 min (plus 15 min chilling)"},
 "difficulty": "Very easy",
 "equipment": ["Sieve", "Mixing bowl", "Chopping board and knife (vegetables)"],
 "meat": None,
 "spice_note": "Black pepper only. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Sweet corn, canned, drained", "1 can (285 g drained weight)", "or 250 g frozen corn, boiled 3 min and cooled"),
   ("Red onion, very finely chopped", "2 tbsp", "or 1 spring onion"),
   ("Cucumber, small dice", "1/2", ""),
   ("Cherry tomatoes, quartered", "6", ""),
   ("Fresh basil or parsley, chopped", "1 tbsp", ""),
   ("Apple cider vinegar", "1 tbsp", ""),
   ("Olive oil", "1 tbsp", ""),
   ("Salt", "1/4 tsp", ""),
   ("Black pepper, ground", "1 pinch", ""),
   ("Mayonnaise (optional, creamy version)", "2 tbsp", "the site's second version mixes corn with mayonnaise"),
  ],
  "prep_before": ["Drain the corn well in the sieve and shake dry.", "Dice the vegetables small so they match the corn kernels."],
  "steps": [
   {"text": "Mix vinegar, oil, salt and pepper in the bowl.", "heat": "", "time": "1 min", "done": ""},
   {"text": "Add corn, onion, cucumber, tomato and herbs. Toss. (For the creamy version stir in the mayonnaise.)", "heat": "", "time": "2 min", "done": "Evenly mixed"},
   {"text": "Chill 15 minutes and serve cold.", "heat": "Fridge", "time": "15 min", "done": "Cold"},
  ],
 }],
 "mistakes": ["Not draining the corn leaves a pool of liquid at the bottom.", "Raw onion too strong: rinse the chopped onion in cold water and drain."],
 "serving": ["Serve cold as a side to grilled chicken or rice dishes. Enough for 2."],
 "storage": ["Keeps 2 days covered in the fridge (1 day if mayonnaise was added)."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "سلطة الذرة الصحية",
   "url": "https://kitchen.sayidaty.net/node/24638/سلطة-الذرة-الصحية/السلطات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/cd/cd3b7d8e90b4590fffde89470e930dcc_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings). Adapted: scaled to 2 adults, cucumber and tomato added; mayonnaise option from node/21668."},
},
# ---------------------------------------------------------------- S4
{
 "id": "S4", "name": "Borgol Salad", "arabic": "سلطة البرغل",
 "cuisine": "Levantine (Turkish-Syrian kisir style)", "category": "Salad",
 "times": {"prep": "15 min", "cook": "10 min (soaking the bulgur)", "total": "25 min (plus 1 hour resting)"},
 "difficulty": "Easy",
 "equipment": ["Medium pot", "Sieve", "Large mixing bowl", "Chopping board and knife (vegetables)"],
 "meat": None,
 "spice_note": "Manal Alalem's original adds 1 tsp crushed chili. It is REMOVED. Sweet paprika and dried mint are kept for color and aroma. The salad keeps its taste; it is simply not hot.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Coarse bulgur (borgol khishin)", "150 g (1 cup)", ""),
   ("Water", "500 ml", "for soaking"),
   ("Bay leaf", "1", ""),
   ("Salt", "1/2 tsp + 1/4 tsp", ""),
   ("Onion, very finely chopped", "1/2 medium", ""),
   ("Garlic, crushed", "1 clove", ""),
   ("Dried mint", "1/2 tsp", ""),
   ("Sweet paprika", "1/2 tsp", ""),
   ("Black pepper, ground", "1 pinch", ""),
   ("Tomato paste", "1 tsp", ""),
   ("Pomegranate molasses", "1 tbsp", ""),
   ("Olive oil", "4 tbsp", ""),
   ("Spring onions, chopped", "2", ""),
   ("Parsley, chopped", "4 tbsp", ""),
   ("Tomato, small dice (optional)", "1", ""),
   ("Lemon juice", "1 tbsp", ""),
  ],
  "prep_before": ["Chop the onion very finely (it is eaten raw).", "Chop the parsley and spring onions."],
  "steps": [
   {"text": "Bring the water, bay leaf and 1/2 tsp salt to a rolling boil. Add the bulgur, stir a few seconds, then take the pot OFF the heat. Cover and leave 10 minutes to swell.", "heat": "High, then Off", "time": "10 min", "done": "Grains doubled in size, tender but chewy"},
   {"text": "Drain in the sieve, discard the bay leaf, spread on a tray and let cool completely.", "heat": "Off", "time": "10 min", "done": "Cool, dry, loose grains"},
   {"text": "In the large bowl put the onion, garlic, dried mint, paprika, black pepper and 1/4 tsp salt. Rub together with your fingertips for 1 minute so the onion absorbs the flavors. Add tomato paste and molasses; stir.", "heat": "", "time": "2 min", "done": "Onion softened and red"},
   {"text": "Add the cooled bulgur and knead it into the onion with your hands. Add the olive oil gradually, kneading, then the lemon juice.", "heat": "", "time": "3 min", "done": "Bulgur evenly colored and glossy"},
   {"text": "Fold in the spring onions, parsley and tomato. Cover and rest in the fridge at least 1 hour (better overnight) before serving.", "heat": "Fridge", "time": "1 hour", "done": "Flavors blended"},
  ],
 }],
 "mistakes": ["Boiling the bulgur: it turns mushy. Soak off the heat only.", "Skipping the resting time: the salad tastes raw and oniony.", "Hot chili flakes used: never; sweet paprika only."],
 "serving": ["Serve cold or at room temperature with lettuce leaves to scoop. Enough for 2 as a generous side."],
 "storage": ["Keeps 3 days covered in the fridge; it improves on day 2."],
 "source": {"site": MANAL, "chef": "Manal Alalem", "recipe": "سلطة البرغل",
   "url": "https://www.manalonline.com/سلطة-البرغل-رمضان-2013/",
   "image": "https://www.manalonline.com/images/crops/g16x9/سلطة-البرغل-رمضان-2013-v2.jpg",
   "status": "Verified: page opened and read (Arabic YouTube video embedded on the page). Adapted: scaled from 2 cups to 1 cup bulgur (2 adults), crushed chili removed."},
},
# ---------------------------------------------------------------- S5
{
 "id": "S5", "name": "Green Mix", "arabic": "سلطة خضراء",
 "cuisine": "Everyday / Levantine", "category": "Salad",
 "times": {"prep": "10 min", "cook": "0 min", "total": "10 min"},
 "difficulty": "Very easy",
 "equipment": ["Salad bowl", "Small jar for dressing", "Chopping board and knife (vegetables)"],
 "meat": None,
 "spice_note": "No spices. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Lettuce (romaine or iceberg), torn", "2 cups (120 g)", ""),
   ("Rocket leaves", "1 cup", ""),
   ("Cucumber, sliced", "1", ""),
   ("Cherry tomatoes, halved", "8", ""),
   ("Spring onions, sliced", "2", ""),
   ("Fresh mint or parsley", "1 tbsp", ""),
   ("DRESSING: lemon juice", "1 tbsp", ""),
   ("DRESSING: white vinegar", "1 tbsp", ""),
   ("DRESSING: olive oil", "2 tbsp", ""),
   ("DRESSING: garlic, crushed", "1/2 clove", ""),
   ("DRESSING: salt", "1/4 tsp", ""),
  ],
  "prep_before": ["Wash the greens in cold water and dry thoroughly."],
  "steps": [
   {"text": "Mix the dressing in the jar and shake.", "heat": "", "time": "1 min", "done": ""},
   {"text": "Put the greens, cucumber, tomatoes and onion in the bowl. Pour the dressing just before serving and toss gently.", "heat": "", "time": "2 min", "done": "Lightly coated, leaves crisp"},
  ],
 }],
 "mistakes": ["Dressing too early wilts the leaves.", "Too much vinegar: keep the lemon-vinegar-oil ratio 1:1:2."],
 "serving": ["The everyday side salad for any main. Enough for 2."],
 "storage": ["Washed, dried greens keep 2 days in a box lined with kitchen paper. Dressed salad does not keep."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "سلطة خضراء",
   "url": "https://kitchen.sayidaty.net/node/10077/سلطة-خضراء/السلطات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/5b/5bf4c2286f1092e6ce3c44681b04f282_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings). Adapted: scaled to 2 adults, cucumber added."},
},
# ---------------------------------------------------------------- S6
{
 "id": "S6", "name": "Greek Salad", "arabic": "سلطة يونانية",
 "cuisine": "Greek / Mediterranean", "category": "Salad",
 "times": {"prep": "12 min", "cook": "0 min", "total": "12 min"},
 "difficulty": "Very easy",
 "equipment": ["Salad bowl or platter", "Small bowl for dressing", "Chopping board and knife (vegetables)"],
 "meat": None,
 "spice_note": "Dried oregano for aroma only. Black pepper. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Tomatoes, cut in wedges", "2 large", ""),
   ("Cucumber, thick half-moons", "1", ""),
   ("Green bell pepper (sweet), rings", "1/2", ""),
   ("Red onion, thin rings", "1/4", ""),
   ("Kalamata or black olives", "10", ""),
   ("Feta cheese, in one block or large cubes", "100 g", ""),
   ("DRESSING: olive oil", "3 tbsp", ""),
   ("DRESSING: lemon juice", "1 tbsp", ""),
   ("DRESSING: red wine vinegar or white vinegar", "1 tsp", ""),
   ("DRESSING: dried oregano", "1/2 tsp", ""),
   ("DRESSING: salt", "1 pinch", "feta is salty"),
   ("DRESSING: black pepper", "1 pinch", ""),
  ],
  "prep_before": ["Cut the vegetables in large pieces; a Greek salad is chunky, not diced.", "Soak the onion rings in cold water 5 minutes to soften the bite; drain."],
  "steps": [
   {"text": "Whisk the dressing in the small bowl.", "heat": "", "time": "1 min", "done": ""},
   {"text": "Arrange tomato, cucumber, pepper, onion and olives on the platter. Pour over the dressing.", "heat": "", "time": "2 min", "done": ""},
   {"text": "Lay the feta on top, sprinkle with a little extra oregano and a thread of olive oil. Serve.", "heat": "", "time": "1 min", "done": ""},
  ],
 }],
 "mistakes": ["Cutting everything small turns it into a chopped salad; keep pieces large.", "Adding salt before tasting: feta and olives are already salty."],
 "serving": ["Serve with bread to soak up the juices. Enough for 2 as a side."],
 "storage": ["Best fresh. Undressed cut vegetables keep 1 day in the fridge."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "سلطة يونانية",
   "url": "https://kitchen.sayidaty.net/node/9585/سلطة-يونانية/السلطات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/6b/6bcceaf71f5c42495ab6c0de455b93ea_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings). Adapted: scaled to 2 adults, feta reduced to a sensible 100 g, sweet green pepper added."},
},
# ---------------------------------------------------------------- S7
{
 "id": "S7", "name": "Caesar Salad", "arabic": "سلطة سيزر بالدجاج",
 "cuisine": "International (American-Italian)", "category": "Salad",
 "times": {"prep": "15 min", "cook": "15 min", "total": "30 min"},
 "difficulty": "Easy",
 "equipment": ["Griddle or frying pan", "Separate raw-chicken board and knife", "Meat thermometer (recommended)", "Baking tray (croutons)", "Small bowl and whisk", "Large salad bowl"],
 "meat": {"animal": "Chicken", "type": "Boneless", "cut": "Breast fillet, flattened to 1.5 cm", "skin": "Skinless", "weight": "300 g (2 small breasts)",
          "prep": "Do not wash. Pat dry, flatten lightly, season with salt, black pepper and olive oil", "method": "Pan-grilled, rested, sliced",
          "note": "Cut follows the original (grilled chicken breast)."},
 "spice_note": "Black pepper only. The dressing uses mild mustard. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Chicken breast fillets", "300 g", "see meat table"),
   ("Olive oil (chicken)", "1 tbsp", ""),
   ("Salt (chicken)", "1/4 tsp", ""),
   ("Black pepper (chicken)", "1/4 tsp", ""),
   ("Romaine lettuce, chopped", "1 head (250 g)", ""),
   ("Parmesan cheese, grated or shaved", "4 tbsp", ""),
   ("Toast bread, cubed (croutons)", "2 slices", ""),
   ("Olive oil (croutons)", "1 tbsp", ""),
   ("DRESSING: mayonnaise", "3 tbsp", ""),
   ("DRESSING: parmesan, grated", "1 tbsp", ""),
   ("DRESSING: lemon juice", "1 tbsp", ""),
   ("DRESSING: garlic, crushed", "1/2 clove", ""),
   ("DRESSING: mild mustard", "1/2 tsp", ""),
   ("DRESSING: olive oil", "1 tbsp", ""),
   ("DRESSING: water", "1 tbsp", "to thin"),
   ("DRESSING: salt and black pepper", "1 pinch each", ""),
  ],
  "prep_before": ["Dry the chicken, flatten to an even thickness, rub with oil, salt and pepper (raw-meat board; wash hands and tools after).", "Wash and dry the lettuce. Cube the bread."],
  "steps": [
   {"text": "Toss the bread cubes with 1 tbsp olive oil and bake until golden. Set aside.", "heat": "Oven 200 °C", "time": "8 min", "done": "Crisp and golden"},
   {"text": "Heat the griddle pan until very hot. Lay in the chicken and do not move it. Turn once.", "heat": "Medium-high", "time": "5 to 6 min per side", "done": "Internal 74 °C; juices run clear; no pink when cut"},
   {"text": "Rest the chicken on a clean plate 5 minutes, then slice across the grain.", "heat": "Off", "time": "5 min", "done": ""},
   {"text": "Whisk all dressing ingredients until smooth and pourable.", "heat": "", "time": "2 min", "done": "Creamy, coats a spoon"},
   {"text": "Toss the lettuce with two-thirds of the dressing in the big bowl. Top with chicken, croutons and parmesan, and drizzle the remaining dressing.", "heat": "", "time": "2 min", "done": ""},
  ],
 }],
 "mistakes": ["Thick uneven chicken is raw in the middle and dry at the edges; flatten it first.", "Slicing chicken without resting loses the juices.", "Dressing the lettuce too early makes it limp."],
 "serving": ["A complete light meal for 2, or a side for 4."],
 "storage": ["Cooked chicken keeps 2 days refrigerated. Dressing keeps 3 days in a jar. Assemble fresh."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "سلطة سيزر بالدجاج",
   "url": "https://kitchen.sayidaty.net/node/7356/سلطة-سيزر-بالدجاج/السلطات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/41/411406613921305e8061eb1c5cde0331_w360_h360.jpg",
   "status": "Verified: page opened and read (2 servings). Adapted: grilling method written out from node/10832; oil in the dressing reduced."},
},
# ---------------------------------------------------------------- S8
{
 "id": "S8", "name": "Halloumi Salad", "arabic": "سلطة الحلوم المشوي",
 "cuisine": "Levantine / Mediterranean", "category": "Salad",
 "times": {"prep": "10 min", "cook": "6 min", "total": "16 min"},
 "difficulty": "Easy",
 "equipment": ["Non-stick or griddle pan", "Tongs", "Salad bowl", "Small jar for dressing"],
 "meat": None,
 "spice_note": "Black pepper and sumac only. No chili.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Halloumi, sliced 1 cm", "200 g", ""),
   ("Olive oil (for frying)", "1 tsp", ""),
   ("Rocket leaves", "2 cups (60 g)", ""),
   ("Lettuce, chopped", "1 cup", ""),
   ("Cherry tomatoes, halved", "8", ""),
   ("Cucumber, sliced", "1/2", ""),
   ("Red bell pepper (sweet), strips", "1/2", ""),
   ("Pomegranate seeds (optional)", "2 tbsp", ""),
   ("Fresh mint leaves", "6", ""),
   ("DRESSING: olive oil", "2 tbsp", ""),
   ("DRESSING: lemon juice", "1 tbsp", ""),
   ("DRESSING: pomegranate molasses", "1 tsp", ""),
   ("DRESSING: sumac", "1/2 tsp", ""),
   ("DRESSING: salt and black pepper", "1 pinch each", ""),
  ],
  "prep_before": ["Dry the halloumi slices with paper.", "Wash and dry the greens; cut the vegetables."],
  "steps": [
   {"text": "Brush the halloumi with 1 tsp oil and grill in the hot pan until golden on both sides.", "heat": "Medium-high", "time": "2 to 3 min per side", "done": "Golden grill marks, soft inside"},
   {"text": "Shake the dressing in the jar. Toss the greens, tomato, cucumber and pepper with it in the bowl.", "heat": "", "time": "2 min", "done": ""},
   {"text": "Lay the hot halloumi on top, scatter pomegranate seeds and mint, and serve at once.", "heat": "", "time": "1 min", "done": ""},
  ],
 }],
 "mistakes": ["Halloumi left to cool becomes rubbery; grill it last.", "Salting the salad heavily: halloumi is very salty."],
 "serving": ["A light lunch for 2 with bread, or a side for 4."],
 "storage": ["Eat at once. Undressed vegetables keep 1 day."],
 "source": {"site": SAY, "chef": "Sayidaty Kitchen (site recipe)", "recipe": "سلطة الحلوم المشوي",
   "url": "https://kitchen.sayidaty.net/node/37458/سلطة-الحلوم-المشوي/السلطات/وصفات",
   "image": "https://kitchen.sayidaty.net/uploads/small/d8/d8eddc4e55025953bac1e23a586956a9_w360_h360.jpg",
   "status": "Verified: page opened and read (4 servings). Adapted: scaled to 2 adults; sumac, molasses and rocket from chef Rami Al-Muqt's version (node/28808)."},
},
# ---------------------------------------------------------------- S9
{
 "id": "S9", "name": "Jer-Jer Salad", "arabic": "سلطة الجرجير",
 "cuisine": "Gulf / Levantine", "category": "Salad",
 "times": {"prep": "10 min", "cook": "0 min", "total": "10 min (plus 1 hour chilling the leaves)"},
 "difficulty": "Very easy",
 "equipment": ["Salad bowl", "Small bowl and whisk", "Chopping board and knife (vegetables)"],
 "meat": None,
 "spice_note": "Manal Alalem's original dressing includes 1/4 tsp crushed chili. It is REMOVED. Sumac and black pepper remain. Nothing else changes.",
 "parts": [{
  "title": None,
  "ingredients": [
   ("Rocket (jarjeer), washed, thick stems removed", "2 bunches (150 g)", ""),
   ("Tomatoes, sliced", "2 medium", ""),
   ("Cucumber, sliced", "1", ""),
   ("Onion, thin slices", "1/2 small", ""),
   ("Walnuts, roughly broken", "4 tbsp", ""),
   ("DRESSING: olive oil", "3 tbsp", ""),
   ("DRESSING: white vinegar", "1 tbsp", ""),
   ("DRESSING: lemon juice", "2 tbsp", ""),
   ("DRESSING: pomegranate molasses", "2 tsp", ""),
   ("DRESSING: sumac", "1/2 tsp", ""),
   ("DRESSING: salt", "1/4 tsp", ""),
   ("DRESSING: black pepper", "1 pinch", ""),
  ],
  "prep_before": ["Wash the rocket, wrap in a damp towel and chill 1 hour so the leaves are crisp (Manal's tip).", "Slice the vegetables."],
  "steps": [
   {"text": "Whisk all dressing ingredients until the molasses dissolves.", "heat": "", "time": "1 min", "done": "Smooth, reddish-brown"},
   {"text": "Arrange the rocket on a platter; scatter tomato, cucumber and onion, then the walnuts.", "heat": "", "time": "2 min", "done": ""},
   {"text": "Pour the dressing over just before serving.", "heat": "", "time": "", "done": ""},
  ],
 }],
 "mistakes": ["Soggy rocket: it was dressed too early or not dried.", "Thick rocket stems are bitter and tough; pick the leaves."],
 "serving": ["The classic partner to rice dishes such as Kabsa, Bukhari and Mandi. Enough for 2."],
 "storage": ["Washed, dried rocket keeps 2 days in a towel-lined box. Dressing keeps 3 days in a jar."],
 "source": {"site": MANAL, "chef": "Manal Alalem", "recipe": "سلطة الجرجير",
   "url": "https://www.manalonline.com/سلطة-الجرجير/",
   "image": "https://www.manalonline.com/images/crops/g16x9/سلطة-الجرجير-v2.webp",
   "status": "Verified: page opened and read. Adapted: crushed chili removed; quantities set for 2 adults."},
},
]
